### ISSUE TITLE
Logfile bloat 6GB+, possibly when bitcoind is stopped

### ISSUE THREAD

**Issue by Stadicus** [lightningnetwork/lnd#1004]
### Background

I run LND on debuglevel "info" resulting about 5 MB log increase of `syslog`. From time to time, this log just explodes, as it did today, growing to 7GB in just 16 hours. A possible cause could be the shutdown / restart of bitcoind.

### Your environment

* version of `lnd`:  
  official release binary 0.4-beta (lnd-linux-arm-v0.4-beta.tar.gz)  
  I did not build from master myself yet, as I want to further develop my [RaspiBolt guide](https://github.com/Stadicus/guides/blob/master/raspibolt/README.md) guide that uses the downloadable binary.

* operating system:  
  `Linux RaspiBolt 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux`

* version of `btcd`, `bitcoind`, or other backend  
  `Bitcoin Core Daemon version v0.16.0`

* any other relevant environment details:
  Raspberry Pi with 16 GB SD card + external hdd, Raspbian 
  set up as described in this [RaspiBolt guide](https://github.com/Stadicus/guides/blob/master/raspibolt/README.md)

### Steps to reproduce

This happened several times already. I had to manually purge the log files (I kept them as a backup) to run the system normally again. 

### Expected behaviour

Even if bitcoind shuts down / restarts, this must not cause LND to develop log tourette syndrome like this (least on debuglevel `info`). I would expect LND to recognize this and try to periodically reconnect. This is not even manageable with log rotation.

### Actual behaviour

This is running on a Raspberry Pi with a 16 GB SD card, thus quickly filling the whole card and bringing the system down.

Problems started here in syslog:
```
Apr  1 12:29:53 localhost lnd[4300]: 2018-04-01 12:29:53.103 [INF] CRTR: New channel discovered! Link connects 032271efcb35188ef00e3f28469a2bb18b50a5f2f325bd130bdac341af24e9b5f0 and 034660651be3b640eea0f89a2ba1d1419a7ef95a852edc10c24d3aaac642791392 with ChannelPoint(807a38527e4c7880829c96abfb53005665e973cc7b5bb1327fc1e58293110535:0): chan_id=567472244782268416, capacity=0.00002 BTC
Apr  1 12:29:53 localhost lnd[4300]: 2018-04-01 12:29:53.120 [INF] CRTR: Updated vertex data for node=034660651be3b640eea0f89a2ba1d1419a7ef95a852edc10c24d3aaac642791392
Apr  1 12:29:59 localhost lnd[4300]: 2018-04-01 12:29:59.323 [INF] DISC: Broadcasting batch of 45 new announcements
Apr  1 12:30:00 localhost systemd[1]: Stopping Bitcoin daemon...
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.081 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.081 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.081 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.082 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.082 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.082 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.082 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.082 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.082 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.083 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.083 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.083 [ERR] LNWL: EOF
Apr  1 12:30:07 localhost lnd[4300]: 2018-04-01 12:30:07.083 [ERR] LNWL: EOF
...
```
There are **millions of rows** like that (just check the millisecond timestamps).

If I skip to the end of the logfile, I get a lot of longer error messages (almost **2000 lines per second**):
```
Apr  1 17:03:59 localhost lnd[4300]: goroutine 7620013 [select, 43 minutes]:
Apr  1 17:03:59 localhost lnd[4300]: github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.(*BitcoindNotifier).RegisterBlockEpochNtfn.func1(0x47ebdd40, 0x1164a000)
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:660 +0x11c
Apr  1 17:03:59 localhost lnd[4300]: created by github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.(*BitcoindNotifier).RegisterBlockEpochNtfn
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:656 +0x1fc
Apr  1 17:03:59 localhost lnd[4300]: goroutine 7615307 [select, 43 minutes]:
Apr  1 17:03:59 localhost lnd[4300]: github.com/lightningnetwork/lnd/chainntnfs.(*ConcurrentQueue).Start.func1(0x11748070)
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/queue.go:54 +0x31c
Apr  1 17:03:59 localhost lnd[4300]: created by github.com/lightningnetwork/lnd/chainntnfs.(*ConcurrentQueue).Start
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/queue.go:47 +0x2c
Apr  1 17:03:59 localhost lnd[4300]: goroutine 7620139 [select, 43 minutes]:
Apr  1 17:03:59 localhost lnd[4300]: github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0x2d8e69c0)
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:177 +0x130
Apr  1 17:03:59 localhost lnd[4300]: created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:150 +0x78
Apr  1 17:03:59 localhost lnd[4300]: goroutine 7616214 [select, 43 minutes]:
Apr  1 17:03:59 localhost lnd[4300]: github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.(*BitcoindNotifier).RegisterBlockEpochNtfn.func1(0x18458810, 0x1164a000)
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:660 +0x11c
Apr  1 17:03:59 localhost lnd[4300]: created by github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify.(*BitcoindNotifier).RegisterBlockEpochNtfn
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:656 +0x1fc
Apr  1 17:03:59 localhost lnd[4300]: goroutine 7618333 [select, 43 minutes]:
Apr  1 17:03:59 localhost lnd[4300]: github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0x21a86240)
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:177 +0x130
Apr  1 17:03:59 localhost lnd[4300]: created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:150 +0x78
Apr  1 17:03:59 localhost lnd[4300]: goroutine 7619988 [select, 43 minutes]:
Apr  1 17:03:59 localhost lnd[4300]: github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0x1569f1a0)
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:177 +0x130
Apr  1 17:03:59 localhost lnd[4300]: created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:150 +0x78
Apr  1 17:03:59 localhost lnd[4300]: goroutine 7615113 [select, 43 minutes]:
Apr  1 17:03:59 localhost lnd[4300]: github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0x3cdf0cf0)
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:177 +0x130
Apr  1 17:03:59 localhost lnd[4300]: created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
Apr  1 17:03:59 localhost lnd[4300]: #011/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:150 +0x78
```

Current content of /etc/var:
```
admin /var/log ฿ date
Mon  2 Apr 20:52:06 CEST 2018

admin /var/log ฿ ls -lah
-rw-r-----  1 root adm   66M Apr  2 20:51 syslog
-rw-r-----  1 root adm  6.1G Apr  2 06:25 syslog.1
-rw-r-----  1 root adm  4.5M Apr  1 06:25 syslog.2
-rw-r-----  1 root adm  4.3M Mar 31 06:25 syslog.3
-rw-r-----  1 root adm   16M Mar 30 06:25 syslog.4
-rw-r-----  1 root adm  1.3M Mar 29 06:25 syslog.5
```

Anything special you want me to grep?

**Comment by aakselrod** [comment]
This is actually fixed in master by https://github.com/lightningnetwork/lnd/commit/c653b62832fec23ed240b94c467672b2b87b399e

**Comment by aakselrod** [comment]
One thing to keep in mind is that even after the fix, if you're using cookie authentication and restart `bitcoind`, it won't currently reload the cookie file in order to get new credentials. This will be added in an upcoming fix.

**Comment by Roasbeef** [comment]
> If I skip to the end of the logfile, I get a lot of longer error messages 

That looks like a complete goroutine dump? 

Also we'll actually _rotate_ logs files by default, but I guess the `syslog` will just capture everything.

**Comment by aakselrod** [comment]
The 0.4.1 binary has the fix to the `[ERR] LNWL: EOF` issue.
