### ISSUE TITLE
lnd crashes while syncing channels with panic: runtime error: invalid memory address or nil pointer dereference (segmentation fault)

### ISSUE THREAD

**Issue by Horndev** [lightningnetwork/lnd#1124]
### Background

After a clean stop of lnd (via lnrpc stop), and then restarting lnd, the node runs for a few minutes, but then crashes with the message and dump: 

```
2018-04-24 10:12:44.022 [INF] HSWC: ChannelLink(1e49eb55a996b60dde39686e36cdc7e3039bf8b49454093265367b6ba7a28bac:0) has exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8b07ff]

goroutine 40072 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).evaluateHTLCView(0xc420271200, 0xc421ef4030, 0xc42a2fd518, 0xc42a2fd510, 0x43, 0x1, 0xc421dd7f80)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2392 +0x1cf
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).computeView(0xc420271200, 0xc421ef4030, 0x1, 0xc421ef4030, 0xc42403b020, 0xc42a2fde80, 0xc42a2fd5d0, 0x429d69)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3267 +0x179
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).validateCommitmentSanity(0xc420271200, 0x14, 0x20, 0x1, 0x0, 0x40c32e, 0xc420271368)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3357 +0x116
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc420271200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2851 +0x224
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc433670780, 0x3, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1440 +0x9d
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc433670780)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:879 +0x6cf
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:391 +0x14e
```

### Your environment

* lnd 0.4.1-beta
* 4.13.0-1011-azure 14-Ubuntu SMP Thu Feb 15 16:15:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind 0.16.0

### Steps to reproduce

Did not happen more than once (yet)

I had 65 open channels, on restart, received the above message.  
Full log of the session is attached (logging level only at info).

[lndlog.seg.txt](https://github.com/lightningnetwork/lnd/files/1945042/lndlog.seg.txt)

**Comment by halseth** [comment]
Possible same crash hit during integration tests: https://travis-ci.org/lightningnetwork/lnd/jobs/374638021

```
	lnd_test.go:100: lnd finished with error (stderr):
		exit status 2
		panic: runtime error: invalid memory address or nil pointer dereference
		[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8edce6]
		
		goroutine 205 [running]:
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).evaluateHTLCView(0xc420420fc0, 0xc4201b4990, 0xc4207154b0, 0xc4207154a8, 0x5, 0x910001, 0x0)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2404 +0x226
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).computeView(0xc420420fc0, 0xc4201b4990, 0x1, 0xc4201b4990, 0xc420715570, 0xc420715578, 0x42c179, 0xc400000008)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3282 +0x17c
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).validateCommitmentSanity(0xc420420fc0, 0x5, 0xa, 0x1, 0x0, 0x0, 0xc420310e00)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3372 +0x124
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc420420fc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2866 +0x247
		github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc4204b0b40, 0x0, 0x0)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1424 +0x9d
		github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc4204b0b40)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:859 +0xb4c
		created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:388 +0x150
		
	lnd_test.go:100: lnd finished with error (stderr):
		exit status 2
		panic: runtime error: invalid memory address or nil pointer dereference
		[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8edeb4]
		
		goroutine 350 [running]:
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).evaluateHTLCView(0xc42009d9e0, 0xc420729530, 0xc4207274b0, 0xc4207274a8, 0x5, 0x440001, 0x8)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2424 +0x3f4
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).computeView(0xc42009d9e0, 0xc420729530, 0x1, 0xc420729530, 0x10987f0, 0xc420727578, 0x42c179, 0xc400000008)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3282 +0x17c
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).validateCommitmentSanity(0xc42009d9e0, 0xa, 0x5, 0xc42000e201, 0x0, 0x5a, 0x165)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3372 +0x124
		github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc42009d9e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2866 +0x247
		github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc4204ae960, 0x0, 0x0)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1424 +0x9d
		github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc4204ae960)
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:859 +0xb4c
		created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
			/home/travis/gopath/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:388 +0x150
		
    --- FAIL: TestLightningNetworkDaemon/switch_circuit_persistence (49.12s)
    	lnd_test.go:69: Failed: (switch circuit persistence): exited with error: 
    		*errors.errorString Node restart failed: context deadline exceeded
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:7750 (0xba321d)
    			testSwitchCircuitPersistence: t.Fatalf("Node restart failed: %v", err)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:94 (0xb7056b)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:9240 (0xbb8b3a)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 (0x4f66e0)
    			tRunner: fn(t)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337 (0x45ecf1)
    			goexit: BYTE	$0x90	// NOP
```

logs: https://file.io/vQQbgU

**Comment by halseth** [comment]
[logs.tar.gz](https://github.com/lightningnetwork/lnd/files/1973425/logs.tar.gz)

**Comment by halseth** [comment]
crashing node is `output-35-Dave-03e4b9a9.log`

**Comment by alexbosworth** [comment]
[panic-at-the-utxo.txt](https://github.com/lightningnetwork/lnd/files/2003208/panic-at-the-utxo.txt)
@halseth I hit this panic as well, logs attached

**Comment by halseth** [comment]
Related: https://github.com/lightningnetwork/lnd/issues/1247

**Comment by enorrmann** [comment]
panic force closing a channel

nil pointer dereference
https://pastebin.com/raw/iByJZm1C

and log
https://pastebin.com/raw/RgUbzjh8
