### ISSUE TITLE
panic: htlc index mismatch

### ISSUE THREAD

**Issue by enorrmann** [lightningnetwork/lnd#1247]
### Background

crashes at startup with panic

### Your environment

0.4.1-beta commit=28b12116e42c83149b6c6b93b70d669a0702bd2d
Linux instance-1 4.13.0-1013 x86_64 x86_64 x86_64 GNU/Linux
bitcoind 0.16

https://pastebin.com/raw/8ChgyieB
and log
https://pastebin.com/raw/nPgFrk8u

**Comment by halseth** [comment]
@enorrmann Thanks for reporting this! Can you reproduce this reliably on startup?

**Comment by halseth** [comment]
One possible clue from the logs is that some of the HTLCs have different `addCommitHeightRemote` on the remote commitment and the pending remote commitment.

For instance:
```
2018-05-15 00:06:43.582 [DBG] LNWL: ChannelPoint(c7bfdbd3c9c3b3c1b30f7965550bba5834ec2f4efb327b5080d4709117942e20:0), starting remote commitment: (*lnwallet.commitment)(0xc4200bc6c0)({
 height: (uint64) 9,
 isOurs: (bool) false,
 ourMessageIndex: (uint64) 8,
 theirMessageIndex: (uint64) 1,
 ourHtlcIndex: (uint64) 8,
 theirHtlcIndex: (uint64) 0,
...
 outgoingHTLCs: ([]lnwallet.PaymentDescriptor) (len=7 cap=8) {
  (lnwallet.PaymentDescriptor) {
   ...
   LogIndex: (uint64) 1,
   HtlcIndex: (uint64) 1,
   ParentIndex: (uint64) 0,
   ...
   addCommitHeightRemote: (uint64) 9,
   addCommitHeightLocal: (uint64) 9,
   removeCommitHeightRemote: (uint64) 0,
   removeCommitHeightLocal: (uint64) 0,
```
and 
```
2018-05-15 00:06:43.806 [DBG] LNWL: ChannelPoint(c7bfdbd3c9c3b3c1b30f7965550bba5834ec2f4efb327b5080d4709117942e20:0), pending remote commitment: (*lnwallet.commitment)(0xc4200bc780)({
 height: (uint64) 10,
 isOurs: (bool) false,
 ourMessageIndex: (uint64) 9,
 theirMessageIndex: (uint64) 1,
 ourHtlcIndex: (uint64) 9,
 theirHtlcIndex: (uint64) 0,
 ...
 outgoingHTLCs: ([]lnwallet.PaymentDescriptor) (len=8 cap=8) {
  (lnwallet.PaymentDescriptor) {
   ...
   LogIndex: (uint64) 1,
   HtlcIndex: (uint64) 1,
   ParentIndex: (uint64) 0,
   ...
   addCommitHeightRemote: (uint64) 10,
   addCommitHeightLocal: (uint64) 0,
   removeCommitHeightRemote: (uint64) 0,
   removeCommitHeightLocal: (uint64) 0,
```

**Comment by halseth** [comment]
@enorrmann If you are able to reproduce, could you apply this diff and post the resulting logs? Thanks!

```diff
diff --git a/lnwallet/channel.go b/lnwallet/channel.go
index 1ddb2657..ffbb5f76 100644
--- a/lnwallet/channel.go
+++ b/lnwallet/channel.go
@@ -1772,8 +1772,11 @@ func (lc *LightningChannel) restoreStateLogs(
 			// is found.
 			if payDesc.HtlcIndex != lc.localUpdateLog.htlcCounter {
 				panic(fmt.Sprintf("htlc index mismatch: "+
-					"%v vs %v", payDesc.HtlcIndex,
-					lc.localUpdateLog.htlcCounter))
+					"%v vs %v.\ncommit diff: %v\nlocalUpdateLog: %v",
+					payDesc.HtlcIndex,
+					lc.localUpdateLog.htlcCounter,
+					pendingRemoteCommitDiff,
+					lc.localUpdateLog))
 			}
 			lc.localUpdateLog.appendHtlc(payDesc)
 		} else {

```

**Comment by enorrmann** [comment]
I'm running the patched code, but I'm unable to reproduce, because of another, perhaps unrelated bug

nil pointer dereference
https://pastebin.com/raw/iByJZm1C

and log
https://pastebin.com/raw/RgUbzjh8

**Comment by halseth** [comment]
@enorrmann  Yeah, that is weird. Did you try to close the channel at some point?

**Comment by enorrmann** [comment]
I think I tried to close some unresponsive channels, before the first error

**Comment by enorrmann** [comment]
applied, then

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9006e3]

goroutine 1 [running]:
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).stateStep(0xc4202b8340, 0x13cd42, 0x4a, 0xc4202cc270, 0x3, 0x3)
        /home/enorrmann/go/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:469 +0x133
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).advanceState(0xc4202b8340, 0x13cd42, 0x0, 0x0, 0x0, 0x2, 0x0)
        /home/enorrmann/go/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:650 +0x17f
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).Start(0xc4202b8340, 0x0, 0x0)
        /home/enorrmann/go/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:246 +0x2fa
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).Start(0xc420130690, 0x0, 0x0)
        /home/enorrmann/go/src/github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:437 +0xb54
main.(*server).Start(0xc4200a92c0, 0xedf6bc, 0x2e)
        /home/enorrmann/go/src/github.com/lightningnetwork/lnd/server.go:580 +0xf5
main.lndMain(0x0, 0x0)
        /home/enorrmann/go/src/github.com/lightningnetwork/lnd/lnd.go:588 +0x1adb
main.main()
        /home/enorrmann/go/src/github.com/lightningnetwork/lnd/lnd.go:633 +0x26
```

**Comment by halseth** [comment]
sorry about that, try this instead:
```difff
diff --git a/contractcourt/channel_arbitrator.go b/contractcourt/channel_arbitrator.go
index cd6fc2a9..65c80423 100644
--- a/contractcourt/channel_arbitrator.go
+++ b/contractcourt/channel_arbitrator.go
@@ -437,37 +437,40 @@ func (c *ChannelArbitrator) stateStep(triggerHeight uint32,
 		//
 		// TODO(roasbeef): need to report to switch that channel is
 		// inactive, should close link
-		closeSummary, err := c.cfg.ForceCloseChan()
-		if err != nil {
-			log.Errorf("ChannelArbitrator(%v): unable to "+
-				"force close: %v", c.cfg.ChanPoint, err)
-			return StateError, closeTx, err
-		}
-		closeTx = closeSummary.CloseTx
+		if c.cfg.ForceCloseChan != nil {
+			closeSummary, err := c.cfg.ForceCloseChan()
+			if err != nil {
+				log.Errorf("ChannelArbitrator(%v): unable to "+
+					"force close: %v", c.cfg.ChanPoint, err)
+				return StateError, closeTx, err
+			}
+			closeTx = closeSummary.CloseTx
 
-		// With the close transaction in hand, broadcast the
-		// transaction to the network, thereby entering the post
-		// channel resolution state.
-		log.Infof("Broadcasting force close transaction, "+
-			"ChannelPoint(%v): %v", c.cfg.ChanPoint,
-			newLogClosure(func() string {
-				return spew.Sdump(closeTx)
-			}))
+			// With the close transaction in hand, broadcast the
+			// transaction to the network, thereby entering the post
+			// channel resolution state.
+			log.Infof("Broadcasting force close transaction, "+
+				"ChannelPoint(%v): %v", c.cfg.ChanPoint,
+				newLogClosure(func() string {
+					return spew.Sdump(closeTx)
+				}))
+
+			// At this point, we'll now broadcast the commitment
+			// transaction itself.
+			if err := c.cfg.PublishTx(closeTx); err != nil {
+				log.Errorf("ChannelArbitrator(%v): unable to broadcast "+
+					"close tx: %v", c.cfg.ChanPoint, err)
+				if err != lnwallet.ErrDoubleSpend {
+					return StateError, closeTx, err
+				}
+			}
 
-		// At this point, we'll now broadcast the commitment
-		// transaction itself.
-		if err := c.cfg.PublishTx(closeTx); err != nil {
-			log.Errorf("ChannelArbitrator(%v): unable to broadcast "+
-				"close tx: %v", c.cfg.ChanPoint, err)
-			if err != lnwallet.ErrDoubleSpend {
-				return StateError, closeTx, err
+			if err := c.cfg.MarkCommitmentBroadcasted(); err != nil {
+				log.Errorf("ChannelArbitrator(%v): unable to "+
+					"mark commitment broadcasted: %v",
+					c.cfg.ChanPoint, err)
 			}
-		}
 
-		if err := c.cfg.MarkCommitmentBroadcasted(); err != nil {
-			log.Errorf("ChannelArbitrator(%v): unable to "+
-				"mark commitment broadcasted: %v",
-				c.cfg.ChanPoint, err)
 		}
 
 		// We go to the StateCommitmentBroadcasted state, where we'll

```

**Comment by enorrmann** [comment]
after this last patch lnd is up and running .. will continue testing

**Comment by enorrmann** [comment]
it is crashing again
https://pastebin.com/raw/xFfRcSQV
and log
http://pasted.co/95f458de

**Comment by halseth** [comment]
@enorrmann Hmmm, did you apply the patch I posted in https://github.com/lightningnetwork/lnd/issues/1247#issuecomment-389144855? Doesn't seem like your newest log include the extra information I added.

**Comment by halseth** [comment]
Inspecting your last logs I think I have been able to detect the bug, will push a possible fix shortly :)

**Comment by enorrmann** [comment]
[lnd.log.tar.gz](https://github.com/lightningnetwork/lnd/files/2009797/lnd.log.tar.gz)
sorry, forgot to re-patch..
here is the log from the pached lnd

**Comment by bockha** [comment]
I had a htlc mismatch panic right now just after startup.
### go environment
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bitcoind-core/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bitcoind-core/gocode"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build217880149=/tmp/go-build -gno-record-gcc-switches"
```

### crash log
```
2018-12-11 19:17:19.052 [INF] LTND: Version: 0.5.1-beta commit=v0.5.1-beta-106-g349551373d7fd571c2a917908e7155c6c6f9706a, build=production, logging=default
2018-12-11 19:17:19.052 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-12-11 19:17:19.054 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2018-12-11 19:17:19.277 [INF] LTND: Primary chain is set to: bitcoin
......
2018-12-11 19:11:42.985 [INF] HSWC: Trimming open circuits for chan_id=1322709:3:0, start_htlc_id=3
2018-12-11 19:11:42.986 [INF] HSWC: Adding live link chan_id=81b214482bcf86727b2b248d49abc8065ae8d79bf790b2f95a121fffacf19166, short_chan_id=1322709:3:0
2018-12-11 19:11:42.986 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(6691f1acff1f125af9b290f79bd7e85a06c8ab498d242b7b7286cf2b4814b281:0)
2018-12-11 19:11:42.987 [INF] HSWC: HTLC manager for ChannelPoint(6691f1acff1f125af9b290f79bd7e85a06c8ab498d242b7b7286cf2b4814b281:0) started, bandwidth=16509258900 mSAT
2018-12-11 19:11:42.987 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(6691f1acff1f125af9b290f79bd7e85a06c8ab498d242b7b7286cf2b4814b281:0)
2018-12-11 19:11:42.992 [INF] SRVR: Negotiated chan series queries with 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2
2018-12-11 19:11:42.993 [INF] DISC: Creating new gossipSyncer for peer=0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2
2018-12-11 19:11:42.994 [INF] HSWC: Received re-establishment message from remote side for channel(6691f1acff1f125af9b290f79bd7e85a06c8ab498d242b7b7286cf2b4814b281:0)
2018-12-11 19:11:42.994 [INF] DISC: gossipSyncer(0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2): requesting new chans from height=1447251 and 4293520044 blocks after
2018-12-11 19:11:42.995 [INF] DISC: gossipSyncer(0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2): filtering chan range: start_height=1447251, num_blocks=4293520044
2018-12-11 19:11:42.995 [INF] DISC: gossipSyncer(0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2): sending final chan range chunk, size=51
2018-12-11 19:11:43.013 [INF] HSWC: Removing channel link with ChannelID(d73b9fea0280345b26116e23e3395f6badb54975613759a1f2b71169fa5c8905)
2018-12-11 19:11:43.013 [INF] HSWC: ChannelLink(04895cfa6911b7f2a15937617549b5ad6b5f39e3236e11265b348002ea9f3bd7:1) is starting
2018-12-11 19:11:43.015 [INF] HSWC: Trimming open circuits for chan_id=1446472:48:1, start_htlc_id=0
2018-12-11 19:11:43.015 [INF] HSWC: Adding live link chan_id=d73b9fea0280345b26116e23e3395f6badb54975613759a1f2b71169fa5c8905, short_chan_id=1446472:48:1
2018-12-11 19:11:43.015 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(04895cfa6911b7f2a15937617549b5ad6b5f39e3236e11265b348002ea9f3bd7:1)
2018-12-11 19:11:43.015 [INF] HSWC: HTLC manager for ChannelPoint(04895cfa6911b7f2a15937617549b5ad6b5f39e3236e11265b348002ea9f3bd7:1) started, bandwidth=7856500000 mSAT
2018-12-11 19:11:43.016 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(04895cfa6911b7f2a15937617549b5ad6b5f39e3236e11265b348002ea9f3bd7:1)
2018-12-11 19:11:43.016 [INF] SRVR: Negotiated chan series queries with 03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415
2018-12-11 19:11:43.016 [INF] DISC: Creating new gossipSyncer for peer=03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415
2018-12-11 19:11:43.017 [INF] HSWC: Received re-establishment message from remote side for channel(04895cfa6911b7f2a15937617549b5ad6b5f39e3236e11265b348002ea9f3bd7:1)
2018-12-11 19:11:43.017 [INF] DISC: gossipSyncer(03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415): requesting new chans from height=1447251 and 4293520044 blocks after
2018-12-11 19:11:43.017 [INF] DISC: gossipSyncer(03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415): filtering chan range: start_height=1447251, num_blocks=4293520044
2018-12-11 19:11:43.017 [INF] DISC: gossipSyncer(03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415): sending final chan range chunk, size=51
2018-12-11 19:11:43.017 [INF] HSWC: Received re-establishment message from remote side for channel(fcc7dec9a2eb72a742e21605720208b8953b97629b498f991c9e086838d6542e:1)
2018-12-11 19:11:43.018 [INF] SRVR: Established connection to: 23.237.77.12:9735
2018-12-11 19:11:43.018 [INF] SRVR: Finalizing connection to 02312627fdf07fbdd7e5ddb136611bdde9b00d26821d14d94891395452f67af248, inbound=false
2018-12-11 19:11:43.067 [INF] PEER: NodeKey(0277622bf4c497475960bf91bd3c673a4cb4e9b589cebfde9700c197b3989cc1b8) loading ChannelPoint(50e8b35a8b129c8329b7b622e1824a6cd7369d0ece53be40920c6a49f5d4989f:0)
2018-12-11 19:11:43.087 [INF] PEER: NodeKey(03a13a469bae4785e27fae24e7664e648cfdb976b97f95c694dea5e55e7d302846) loading ChannelPoint(5f94b13a01e9f0153cd6e1fb3576a3575844fd76b1ffa4e90e798c65f7cb42fa:0)
panic: htlc index mismatch: 57 vs 58

goroutine 5924 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc0000e2f00, 0xc000c7d380, 0xc000c7d440, 0xc000c7d500, 0xc0000e3000, 0xc00093c8a0, 0x0, 0x0)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1826 +0xa5b
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc0000e2f00, 0xc00094fa78, 0xc00094f9f8, 0x0, 0xc000acfcc0)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1706 +0x480
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel(0x1274580, 0xc0000b2ba0, 0x7fbecd7cf3a8, 0xc0000b4e00, 0xc000860600, 0xc000acfc80, 0xc000c7ff40, 0x1)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1399 +0x5c6
main.(*peer).loadActiveChannels(0xc0009ca000, 0xc00000e798, 0x1, 0x1, 0x2, 0x2)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/peer.go:384 +0x124
main.(*peer).Start(0xc0009ca000, 0x117c668, 0xc0004abb00)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/peer.go:316 +0x6fb
main.(*server).peerInitializer(0xc0004abb00, 0xc0009ca000)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/server.go:2399 +0x10d
created by main.(*server).peerConnected
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/server.go:2334 +0x409
```
