### ISSUE TITLE
panic: htlc index mismatch: 4 vs 6

### ISSUE THREAD

**Issue by hpbock** [lightningnetwork/lnd#1415]
### Background

panic: htlc index mismatch: 4 vs 6

### Your environment

* [INF] LTND: Version 0.4.2-beta commit=7cf5ebe2650b6798182e10be198c7ffc1f1d6e19
* Linux odroid 4.14.47-139 #1 SMP PREEMPT Sun Jun 3 20:08:16 -03 2018 armv7l armv7l armv7l GNU/Linux
* bitcoind V0.16.1
* fails as well on a raspberry pi 3

### Steps to reproduce

Start LND and wait for inbound connection from 86.123.35.199.

### Expected behaviour

It should not crash.

### Actual behaviour
```
2018-06-18 16:27:43.943 [INF] SRVR: New inbound connection from 86.123.35.199:43214
panic: htlc index mismatch: 4 vs 6

goroutine 419934 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0x1142c4d0, 0x11a3e000, 0x11a3e1b0, 0x11a3e240, 0x1142c580, 0x38026360, 0x0, 0x0)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1806 +0x788
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0x1142c4d0, 0x348c4c58, 0x348c4bf4, 0x130c6ee0, 0x77c6c8)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1686 +0x3b4
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel(0xae7068, 0x113683c0, 0xb363ec70, 0x114742a0, 0x117ba500, 0x113f6104, 0x0, 0x1)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1379 +0x59c
main.(*peer).loadActiveChannels(0x40434000, 0x26f06ba0, 0x1, 0x2, 0x2, 0x2)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/peer.go:313 +0xac
main.(*peer).Start(0x40434000, 0x2635b920, 0x0)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/peer.go:295 +0x5a4
main.(*server).peerConnected(0x11224270, 0xaed108, 0x2635b920, 0x0, 0xf17500)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:1487 +0x204
main.(*server).InboundPeerConnected(0x11224270, 0xaed108, 0x2635b920)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:1563 +0x544
main.(*server).InboundPeerConnected-fm(0xaed108, 0x2635b920)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:534 +0x2c
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).listenHandler
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:494 +0x1e4
```

**Comment by Roasbeef** [comment]
Was this channel created _after_ your updated, or _before_? As a bug related to this was recently resolved and packaged w/ 0.4.2, but only applies for channels created _after_ that version.

**Comment by hpbock** [comment]
The [channel](https://1ml.com/channel/576807098504577025) was created with V0.4.1-beta before the update to V0.4.2-beta.

**Comment by Roasbeef** [comment]
I see, so then that's the issue. This has been fixed in the newer versions, but for now you can apply this patch to get around the issue (as the channel is borked on disk, but new commits won't get into this invalid state):
```go
diff --git a/lnwallet/channel.go b/lnwallet/channel.go
index 50bd723b..8a1e30e1 100644
--- a/lnwallet/channel.go
+++ b/lnwallet/channel.go
@@ -1804,9 +1804,9 @@ func (lc *LightningChannel) restoreStateLogs(
 			// TODO(halseth): remove when cause of htlc entry bug
 			// is found.
 			if payDesc.HtlcIndex != lc.localUpdateLog.htlcCounter {
-				panic(fmt.Sprintf("htlc index mismatch: "+
+				return fmt.Errorf("htlc index mismatch: "+
 					"%v vs %v", payDesc.HtlcIndex,
-					lc.localUpdateLog.htlcCounter))
+					lc.localUpdateLog.htlcCounter)
 			}
 
 			lc.localUpdateLog.appendHtlc(payDesc)
```

**Comment by hpbock** [comment]
With this patch i get another panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42bdfc]

goroutine 88078 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).Stop(0x0)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1453 +0x14
main.(*peer).loadActiveChannels(0x34174000, 0x24f7e248, 0x1, 0x2, 0x2, 0x2)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/peer.go:317 +0x918
main.(*peer).Start(0x34174000, 0x156ba480, 0x0)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/peer.go:295 +0x5a4
main.(*server).peerConnected(0x112244e0, 0xaed0d0, 0x156ba480, 0x0, 0xf17500)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:1487 +0x204
main.(*server).InboundPeerConnected(0x112244e0, 0xaed0d0, 0x156ba480)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:1563 +0x544
main.(*server).InboundPeerConnected-fm(0xaed0d0, 0x156ba480)
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/server.go:534 +0x2c
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).listenHandler
        /home/lnd-mainnet/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:494 +0x1e4
```

**Comment by halseth** [comment]
@hpbock Try applying the diff in this PR: https://github.com/lightningnetwork/lnd/pull/1418

**Comment by hpbock** [comment]
With PR #1418 the startup fails quickly with this message:
```
2018-06-19 14:25:21.876 [ERR] UTXN: Failed to sweep first-stage HTLC (CLTV-delayed) output cb9d4f780fba25c50a4f7c696bb3075b5f8db6201286be36c8f23c3391d6ad73:0
2018-06-19 14:25:21.878 [ERR] UTXN: Failed to graduate outputs at height=528208: -26: 66: min relay fee not met
2018-06-19 14:25:23.836 [INF] NTFN: Cancelling epoch notification, epoch_id=2
2018-06-19 14:25:23.836 [ERR] SRVR: unable to start server: -26: 66: min relay fee not met
```

**Comment by Roasbeef** [comment]
You'll need to lower the min relay fee of your target node.

**Comment by bockha** [comment]
Running my bitcoind core with `minrelaytxfee=0`and then starting `lnd` solved the min relay fee problem. Now `lnd`faials to start with this error message:

```
2018-06-21 15:18:28.359 [ERR] SRVR: unable to start server: transaction output has negative value of -36905
```

**Comment by wpaulino** [comment]
Closing as the original issue has already been resolved.
