### ISSUE TITLE
panic during handling peer start

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [lightningnetwork/lnd#148]
`moli` reported in Slack:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa3ead5]

goroutine 59 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnReq).ID(0x0, 0xc6159e)
        /home/moli/work/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:78 +0x5
main.(*server).peerConnected(0xc430576000, 0x1130720, 0xc42044a580, 0x0, 0xc420071000)
        /home/moli/work/src/github.com/lightningnetwork/lnd/server.go:431 +0x391
main.(*server).inboundPeerConnected(0xc430576000, 0x1130720, 0xc42044a580)
        /home/moli/work/src/github.com/lightningnetwork/lnd/server.go:471 +0x3de
main.(*server).(main.inboundPeerConnected)-fm(0x1130720, 0xc42044a580)
        /home/moli/work/src/github.com/lightningnetwork/lnd/server.go:209 +0x3e
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).listenHandler
        /home/moli/work/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:349 +0x30d
```

**Comment by Roasbeef** [comment]
Fixed by #149
