### ISSUE TITLE
lnd panic and refuses to start (failed sending fundingLocked: shutting down unable to send)

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1568]
`version 0.4.2-beta commit=bc5bfeb479d5123ad3c9cfc8bf9636bb1535802e`

first got a panic:
```
2018-07-16 14:54:45.359 [INF] LTND: Payment received: (*channeldb.Invoice)(0xc425fcb5c0)({
 Memo: ([]uint8) (len=7 cap=7) {
  00000000  64 65 70 6f 73 69 74                              |deposit|
 },
 Receipt: ([]uint8) {
 },
 PaymentRequest: ([]uint8) (len=205 cap=205) {
  00000000  6c 6e 62 63 31 30 75 31  70 64 35 65 76 76 77 70  |lnbc10u1pd5evvwp|
  00000010  70 35 6e 6c 6a 65 72 63  32 75 65 63 68 61 36 6e  |p5nljerc2uecha6n|
  00000020  39 77 37 38 73 72 68 6b  36 70 79 6e 32 65 34 61  |9w78srhk6pyn2e4a|
  00000030  35 6b 68 39 61 37 39 34  6d 74 6e 79 6c 79 35 7a  |5kh9a794mtnyly5z|
  00000040  34 30 67 34 6d 71 64 71  76 76 33 6a 68 71 6d 6d  |40g4mqdqvv3jhqmm|
  00000050  6e 64 39 36 71 63 71 7a  79 73 78 71 7a 66 76 64  |nd96qcqzysxqzfvd|
  00000060  33 67 79 32 36 6c 66 6b  70 64 75 73 77 68 30 6c  |3gy26lfkpduswh0l|
  00000070  33 73 74 36 66 67 34 33  35 32 74 63 72 65 79 32  |3st6fg4352tcrey2|
  00000080  6e 35 35 78 68 78 32 33  34 73 61 34 6d 67 35 34  |n55xhx234sa4mg54|
  00000090  61 6d 6e 70 71 70 33 6d  74 34 77 76 6a 6e 78 34  |amnpqp3mt4wvjnx4|
  000000a0  37 70 76 30 65 68 78 65  38 74 6b 67 61 30 35 34  |7pv0ehxe8tkga054|
  000000b0  61 63 6d 73 35 33 77 6e  70 38 71 64 70 72 61 68  |acms53wnp8qdprah|
  000000c0  6b 66 6b 74 6d 63 71 78  35 77 6a 35 79           |kfktmcqx5wj5y|
 },
 CreationDate: (time.Time) 2018-07-16 14:54:06.258222648 +0000 UTC,
 SettleDate: (time.Time) 2018-07-16 14:54:45.340523419 +0000 UTC m=+293298.304054393,
 Terms: (channeldb.ContractTerm) {
  PaymentPreimage: ([32]uint8) (len=32 cap=32) {
   00000000  18 65 e2 4a 31 25 bb 44  8c 44 82 74 63 d5 2c c8  |.e.J1%.D.D.tc.,.|
   00000010  36 2a cf 06 be 0d e5 2e  a1 fd 20 f2 12 73 0e a1  |6*........ ..s..|
  },
  Value: (lnwire.MilliSatoshi) 1000000 mSAT,
  Settled: (bool) true
 },
 AddIndex: (uint64) 5010,
 SettleIndex: (uint64) 2526,
 AmtPaid: (lnwire.MilliSatoshi) 1000000 mSAT
})

2018-07-16 14:54:45.370 [INF] HSWC: ChannelLink(531305:1438:1) settling 9fe591e15cce2fdd4caef1e03bdb4124d59af696b97be2d76b993e4a0aaf4576 as exit hop
2018-07-16 14:54:45.558 [INF] HSWC: Sent 0 satoshis and received 1000 satoshis in the last 10 seconds (0.300000 tx/sec)
2018-07-16 14:54:46.675 [INF] DISC: Broadcasting batch of 6 new announcements
2018-07-16 14:55:01.642 [INF] CRTR: Updated vertex data for node=033bdb9bf6b4ee1aedc87252d7748ac040507089544eb6ba072bb2e17c0d616ed1
2018-07-16 14:55:05.550 [INF] HSWC: Sent 0 satoshis and received 0 satoshis in the last 10 seconds (0.100000 tx/sec)
2018-07-16 14:55:06.127 [WRN] HSWC: Accepting duplicate payment for hash=9fe591e15cce2fdd4caef1e03bdb4124d59af696b97be2d76b993e4a0aaf4576
2018-07-16 14:55:06.137 [INF] LTND: Payment received: (*channeldb.Invoice)(<nil>)
2018-07-16 14:55:06.139 [INF] HSWC: ChannelLink(531305:1438:1) settling 9fe591e15cce2fdd4caef1e03bdb4124d59af696b97be2d76b993e4a0aaf4576 as exit hop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0xc8551e]
                                                                                                                                 goroutine 1570 [running]:
main.(*invoiceRegistry).invoiceEventNotifier(0xc420a164d0)
        /home/lnd/gocode/src/github.com/lightningnetwork/lnd/invoiceregistry.go:147 +0xae
created by main.(*invoiceRegistry).Start
        /home/lnd/gocode/src/github.com/lightningnetwork/lnd/invoiceregistry.go:76 +0x5c
```

then it was issues sweeping when starting up:

```2018-07-17 06:37:55.349 [ERR] UTXN: Failed to re-register for kindergarten sweep transaction at height=531727: -22: TX rejected: transaction 725e7b9ebf2a123586e7849e0fee604be0b89810280b57603f99e1dc8eb3c7f8 has insufficient priority (3839.404011461318 <= 5.76e+07)```

```2018-07-17 06:37:55.363 [ERR] FNDG: failed to handle fundingconfirmation: failed sending fundingLocked: shutting down unable to send```

full log when trying to start
http://paste.ubuntu.com/p/wS6xd5sy2T/

### Background

Describe your issue here.

### Your environment

* version of `lnd`
* which operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by robtex** [comment]
emergency-patched it like this to make it start

```diff --git a/utxonursery.go b/utxonursery.go
index ff190fa..14cdd39 100644
--- a/utxonursery.go
+++ b/utxonursery.go
@@ -741,7 +741,8 @@ func (u *utxoNursery) regraduateClass(classHeight uint32) error {
                        utxnLog.Errorf("Failed to re-register for kindergarten "+
                                "sweep transaction at height=%d: %v",
                                classHeight, err)
-                       return err
+//                       return err
+                       return nil;
                }
        }```

**Comment by robtex** [comment]
probably should have another patch though... doesn't feel good, but the node runs fine
