### ISSUE TITLE
lnd panic at reception of payment

### ISSUE THREAD

**Issue by robtex** [lightningnetwork/lnd#1604]
```lnd version 0.4.2-beta commit=6dff599d213be4182a70c8eab4cac8a36d3c15e4```

```2018-07-22 16:31:18.725 [INF] CRTR: Updated vertex data for node=03df95ed69a109deeb71d3dabe9b9a289ab561fa731c8fc853d1c70847597933e3
2018-07-22 16:31:21.352 [INF] CRTR: Updated vertex data for node=020d41c5a32f06d7addc7378f2d4a6596358d8716a3eb5d5bbdd894a82a1fdd00c
2018-07-22 16:31:29.971 [WRN] HSWC: Accepting duplicate payment for hash=b3f288d034efb06b10863ab0ba20f9d9f1d65d9478cdbc2d903b7e7485133d44
2018-07-22 16:31:29.980 [INF] LTND: Payment received: (*channeldb.Invoice)(<nil>)
2018-07-22 16:31:29.980 [INF] HSWC: ChannelLink(528193:2000:0) settling b3f288d034efb06b10863ab0ba20f9d9f1d65d9478cdbc2d903b7e7485133d44 as exit hop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0xc87a3e]
goroutine 1516 [running]:
main.(*invoiceRegistry).invoiceEventNotifier(0xc4202ae4d0)
        /home/lnd/gocode/src/github.com/lightningnetwork/lnd/invoiceregistry.go:147 +0xae
created by main.(*invoiceRegistry).Start
        /home/lnd/gocode/src/github.com/lightningnetwork/lnd/invoiceregistry.go:76 +0x5c

```

**Comment by githorray** [comment]
Can confirm, panic. ;-)

**Comment by robtex** [comment]
good news, it seems to be fixed in
 `lnd version 0.4.2-beta commit=bca926d6af69b117eb6afa0e50ec2dc32d2899d4`
