### ISSUE TITLE
listchaintxns command makes lnd crash

### ISSUE THREAD

**Issue by xsb** [lightningnetwork/lnd#1928]
### Background

My mainnet lnd node crashes when I try to list chain transactions, other actions work just fine.

```
$ lncli listchaintxns
[lncli] rpc error: code = Unavailable desc = transport is closing
```

The node has a pending channel that hasn't confirmed in days. No other channels are active at this moment.

Detected after upgrading from `0.5.0-beta-rc1` to `0.5.0-beta`. No idea if it happened with the previous version.

### Your environment

Version:

```
Version 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
Active chain: Bitcoin (network=mainnet)
Checking for schema update: latest_version=6, db_version=6
```

OS:

Debian on arm64

```
Linux rock64 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2e #1 SMP Sat Jul 21 20:18:03 UTC 2018 aarch64 GNU/Linux
```

Backend:

```
Bitcoin Core version v0.16.2
```

### Steps to reproduce

1) Run `lncli listchaintxns`

CLI error:

```
[lncli] rpc error: code = Unavailable desc = transport is closing
```

Stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75c2d4]

goroutine 44674 [running]:
main.(*rpcServer).GetTransactions(0x40002f2d20, 0xc89c80, 0x4010c362d0, 0x14a2440, 0x40002f2d20, 0x4013676a40, 0x40002b4e70)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:3021 +0x1b4
github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler.func1(0xc89c80, 0x4010c362d0, 0x8fb6c0, 0x14a2440, 0x1, 0x1, 0x0, 0x0)        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6271 +0x74
github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0xc89c80, 0x4010c362d0, 0x8fb6c0, 0x14a2440, 0x4013676a20, 0$4013676a40, 0x4011096610, 0x59cd3c, 0x50, 0x99ebe0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:126 +0x104
github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler(0x9f6880, 0x40002f2d20, 0xc89c80, 0x4010c362d0, 0x4010813180, 0x40002$ac40, 0x0, 0x0, 0x98e2a0, 0x49820)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6273 +0x130
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0x400047c000, 0xc8f300, 0x4010896300, 0x4010786000, 0x$0002f2e40, 0x1460270, 0x4011096600, 0x0, 0x0)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x78c
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0x400047c000, 0xc8f300, 0x4010896300, 0x4010786000, 0x401$096600)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0xf5c
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0x40000390b0, 0x400047c000, 0xc8f300, 0x401089630$, 0x4010786000)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x84
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0x84
```

### Expected behaviour

The output should show the list of chain transactions that my node did in the past.

### Actual behaviour

The daemon crashes.

**Comment by guggero** [comment]
This is a duplicate of #1915

**Comment by xsb** [comment]
True, sorry. And thanks for the fix @guggero.
