### ISSUE TITLE
LND crashes on rpc listchaintxns

### ISSUE THREAD

**Issue by stridentbean** [lightningnetwork/lnd#2037]
### Background

While trying to remove funds from my lnd wallet and check if the transactions is confirmed lnd crashes.

### Your environment

* 0.5.0-beta commit=3b2c807288b1b7f40d609533c1e96a510ac5fa6d
* Linux lnd 4.14.62-65.117.amzn1.x86_64 #1 SMP Fri Aug 10 20:03:52 UTC 2018 x86_64 Linux
* bitcoind 0.17.0
* running on docker on aws
* testnet

### Steps to reproduce

1. Generate an address on testnet (wallet A)
2. Send funds to new address
3. Run walletbalance from cli and confirm transactions is confirmed
4. Create address on another wallet (wallet B)
5. Send coins from wallet A to wallet B (I used 10% of confirmed coins)
6. Run walletbalance on wallet A and observe 90% of funds are unconfirmed
7. Run listchaintxns on wallet A and observe segfault and lnd restarting

segfault error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcf36bd]

goroutine 8676390 [running]:
main.(*rpcServer).GetTransactions(0xc0000bb8c0, 0x1210060, 0xc0008a3a40, 0x1a33658, 0xc0000bb8c0, 0xc000b61040, 0xc0001b5110)
	/go/src/github.com/lightningnetwork/lnd/rpcserver.go:3021 +0x20d
github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler.func1(0x1210060, 0xc0008a3a40, 0xe99c40, 0x1a33658, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6271 +0x89
github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0x1210060, 0xc0008a3a40, 0xe99c40, 0x1a33658, 0xc000b61020, 0xc000b61040, 0xc000edab50, 0x40e398, 0x50, 0xf3d720)
	/go/src/github.com/lightningnetwork/lnd/macaroons/service.go:126 +0x153
github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler(0xf95740, 0xc0000bb8c0, 0x1210060, 0xc0008a3a40, 0xc00146fc70, 0xc000546b40, 0x0, 0x0, 0xc00087a8c0, 0x10)
	/go/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6273 +0x158
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000478140, 0x1215740, 0xc001282000, 0xc0008cc300, 0xc0000bba70, 0x19f1450, 0xc0006d1590, 0x0, 0x0)
	/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x8ec
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000478140, 0x1215740, 0xc001282000, 0xc0008cc300, 0xc0006d1590)
	/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1308
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00045b780, 0xc000478140, 0x1215740, 0xc001282000, 0xc0008cc300)
	/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x9f
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0xa1
```

cli error
```
[lncli] rpc error: code = Unavailable desc = transport is closing
```

### Expected behaviour

listchaintxns should list unconfirmed transaction or at least all confirmed transactions. I'm not sure how this will play with lightningnetwork/lnd#1984. 

### Actual behaviour

Segfault and lnd restarts (it may just crash, but docker causes a restart)

**Comment by wpaulino** [comment]
This has been fixed on the latest version of master, so I would suggest updating. See https://github.com/lightningnetwork/lnd/pull/1916.
