### ISSUE TITLE
Bug, index out of range, channeldb/db.go:409

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [lightningnetwork/lnd#204]
User `jimmymow` reported:
```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchClosedChannels.func1.1(0x40150f3, 0x25, 0x25, 0x4015118, 0x0, 0x0, 0x0, 0xc420284478)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/channeldb/db.go:409 +0x228
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*Bucket).ForEach(0xc420126700, 0xc4205138f8, 0x3, 0x3)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/bucket.go:361 +0xff
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchClosedChannels.func1(0xc420284460, 0x19f78f0, 0xc420284460)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/channeldb/db.go:426 +0xa9
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*DB).View(0xc420316780, 0xc4201939a8, 0x0, 0x0)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/db.go:626 +0x9f
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchClosedChannels(0xc4202a3680, 0x19f8701, 0xc420292fc0, 0x1e249d0, 0x0, 0x0, 0xc420074230)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/channeldb/db.go:427 +0x7f
main.(*breachArbiter).Start(0xc420292fc0, 0x0, 0x0)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/breacharbiter.go:126 +0x4ea
main.(*server).Start(0xc420154180, 0x1, 0x1)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/server.go:363 +0x117
main.lndMain(0x0, 0x0)
    /Users/jackmallers/goprojects/src/github.com/lightningnetwork/lnd/lnd.go:190 +0xf39
main.main()
```

**Comment by Roasbeef** [comment]
A recent schema change took place when adding the latest additions to the `pendingchannels` RPC. As a result, if you keep the same database, and had entries in your `closedChannel` bucket, then this issue could arise. 

Closing.
