### ISSUE TITLE
LND crashes randomly - iOS app environment

### ISSUE THREAD

**Issue by weaklysubjective** [lightningnetwork/lnd#2076]
### Background

Sometimes when lnd starts up, it repeatedly crashes with the following log. Short of deleting and reinstalling the app (ios), no other workaround exists.

Even though it reports "out of memory" , there is enough memory to run the app, and there is also 1.5 gb storage available on the device. 

**No reason why it should attempt to allocate 268MB as reported** 

To recap, the app and LND both work without trouble mostly. This happens only every once in a while , and when it does, it doesn't go away without a delete and reinstall of the app.

The simnet was wiped as well and when this crash happened, and it  had roughly 200 blocks !

LOG
===
2018-10-19 21:25:49.166 [INF] LNWL: Opened wallet
Wallet successfully unlocked
2018-10-19 21:25:49.169 [INF] LTND: Primary chain is set to: bitcoin
2018-10-19 21:25:49.186 [INF] BTCN: Loaded 0 addresses from file '/var/mobile/Containers/Data/Application/C239D7B8-1D31-4CF0-9C06-FD9688C25C28/Documents/Lnd/data/chain/bitcoin/simnet/peers.json'
2018-10-19 21:25:49.187 [INF] BTCN: Waiting for block headers to sync, then will start cfheaders sync...
**runtime: out of memory: cannot allocate 268435456-byte block (274104320 in use)
fatal error: out of memory**

goroutine 74 [runnable]:
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/connmgr.(*ConnManager).NewConnReq(0x10cac4510)
	go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/connmgr/connmanager.go:361
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/connmgr.(*ConnManager).Start
	go/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcd/connmgr/connmanager.go:522 +0x1a8

### Your environment

* version of `lnd` - 0.5beta
* which operating system (`uname -a` on *Nix)  -- iOS
* version of `btcd`, `bitcoind`, or other backend -- btcd

### Steps to reproduce

Unable to reproduce often as desired, but happens repeatedly once in a while until app reinstalled.

**Comment by halseth** [comment]
How do you compile/run lnd? What's the commit?

**Comment by weaklysubjective** [comment]
Compile with gomobile , built out as a framework ...

Commit info:

commit f4305097e1638f6f8958dfa9eec941d8bf80246e
Merge: b96745e a75b0c8
Author: Olaoluwa Osuntokun <laolu32@gmail.com>
Date:   Fri Sep 21 17:13:01 2018 -0700

    Merge pull request #1295 from joostjager/forget
    
    rpc: add support for a `forgetchannel` RPC only enabled w/ the debug flag

**Comment by weaklysubjective** [comment]
Just now erased  and reinstalled app, it works fine , even though number of btc simnet blocks increased to 350 (up 150 from the time the crash was reported).

**Comment by weaklysubjective** [comment]
How about for test purposes on mobile i crank down N to 16384 ? 
Interested in your opinion whether a lower N would be production worthy ?

**Comment by Roasbeef** [comment]
That isn't compatible with the current version. You won't be able to use
the seed with lnd. We set a sane value to make brute forcing very
expensive.

On Oct 19, 2018 4:11 PM, "weaklysubjective" <notifications@github.com>
wrote:

How about for test purposes on mobile i crank down N to 16384 ?
Interested in your opinion whether a lower N would be production worthy ?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/2076#issuecomment-431524138>,
or mute the thread

**Comment by Roasbeef** [comment]
Biometrics generally aren't very secure, as they're typically usernames,
not passwords.

On Oct 19, 2018 4:25 PM, "weaklysubjective" <notifications@github.com>
wrote:

Thanks guys.
Thoughts for a future day - we could have a build for mobile with a lower
threshold, as apps are already secured by biometrics :-)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/2076#issuecomment-431526034>,
or mute the thread

**Comment by weaklysubjective** [comment]
Hi roasbeef, if lnd allocates 300MB or so for scrypt, should most of it be released after the wallet is unlocked ? I ask because, the wallet is being unlocked successfully, but its when LND proceeds to process blocks that it crashes. I can't get it work for a while now as it keeps crashing after the first ever time. Any suggestions ?(short of noseedbackup )

**Comment by Roasbeef** [comment]
Go will slowly release un used pages back to the OS

On Oct 19, 2018 6:57 PM, "weaklysubjective" <notifications@github.com>
wrote:

Hi roasbeef, if lnd allocates 300MB or so for scrypt, should most of it be
released after the wallet is unlocked ? I ask because, the wallet is being
unlocked successfully, but its when LND proceeds to process blocks that it
crashes. I can't get it work for a while now as it keeps crashing after the
first ever time. Any suggestions ?(short of noseedbackup )

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/lightningnetwork/lnd/issues/2076#issuecomment-431539700>,
or mute the thread

**Comment by weaklysubjective** [comment]
Hi Guys, Another update for what its worth. After your last comment @roasbeef I looked into the code a bit more and found "./vendor/github.com/btcsuite/btcwallet/snacl/snacl.go" after deriving key is ALREADY attempting to release the go heap back to the operating system (as below).  App still crashed. 
So i researched a bit more and found that even though the Free call releases the heap , the heap itself requires "scavenging" to return the memory back to the operating system. So I set the scavenge=1 GODEBUG variable hoping that it would scavenge really really quickly (in nano seconds) and return the memory back for the second iteration of scrypt. That did *not* cut it either. 
Continuing my research i noticed i was on Go 1.10.x and that a newer upgrade Go 1.11. was available. Upgraded to the newer go version, got rid off GODEBUG scavenge  variable, retained the code below, and voila , calls to scrypt started to work and as expected memory was released. 

While i write this, my testing is still fragile and may yet break, but thought i'd provide an update anyway. 

In summary, btcsuite code (it may well be your code @roasbeef), appears to realize the issue of go "hoarding" released heap and not giving it back to OS for future alloc. And the code below is forcing the heap release and not waiting 5-7 minutes for the garbage collector 
Of course for me it worked only when i upgraded to go 1.11.x

// I'm not a fan of forced garbage collections, but scrypt allocates a
        // ton of memory and calling it back to back without a GC cycle in
        // between means you end up needing twice the amount of memory.  For
        // example, if your scrypt parameters are such that you require 1GB and
        // you call it twice in a row, without this you end up allocating 2GB
        // since the first GB probably hasn't been released yet.
        debug.FreeOSMemory()
