### ISSUE TITLE
ERROR:grpc._channel:Exception iterating requests! value must be iterable calling to sendToRoute

### ISSUE THREAD

**Issue by ranchalp** [lightningnetwork/lnd#2129]
### Background

Following the python example in the gRPC api when calling sendToRoute, the gRPC returns an error of the value not being iterable.

### Your environment

lnd version 0.5.0-beta commit=a3edcf9cd537ea37a502efc91d262e7017a99e6b
Linux Aegon 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
btcd version 0.12.0-beta

### Steps to reproduce:
run code in https://api.lightning.community/?python#sendtoroute

for example:

```python
import rpc_pb2 as ln
import rpc_pb2_grpc as lnrpc
import grpc
import os
import codecs
import constants

os.environ["GRPC_SSL_CIPHER_SUITES"] = 'HIGH+ECDSA'

cert = open(os.path.expanduser('~/.lnd/tls.cert'), 'rb').read()
creds = grpc.ssl_channel_credentials(cert)
channel = grpc.secure_channel(constants.ALICE_RPC, creds)
stub = lnrpc.LightningStub(channel)
with open(os.path.expanduser(constants.ALICE_MACAROON), 'rb') as f:
    macaroon_bytes = f.read()
    macaroon = codecs.encode(macaroon_bytes, 'hex')

end_point =constants.NODE_REMOTE

amt_value = constants.AMT_VALUE
fee_limit = ln.FeeLimit(fixed=100)
request = ln.QueryRoutesRequest(
    pub_key=end_point,
    amt=amt_value,
    num_routes=1,
    final_cltv_delta=9,
    fee_limit=fee_limit,
)
response = stub.QueryRoutes(request, metadata=[('macaroon', macaroon)])
# # response = ''
# response = stub.WalletBalance(ln.WalletBalanceRequest(), metadata=[('macaroon', macaroon)])
print(response)
pay_hash = constants.PAY_HASH_C
#pay_hash = constants.PAY_HASH_F
pay_hash_bytes= pay_hash.decode('hex')

def request_generator():
    # Initialization code here.
    while True:
        # Parameters here can be set as arguments to the generator.
        request2 = ln.SendToRouteRequest(
            payment_hash=pay_hash_bytes,
            payment_hash_string = pay_hash,
            routes=response,
        )
        yield request2
        # Do things between iterations here.
            
request_iterable = request_generator()

for response2 in stub.SendToRoute(request_iterable, metadata=[('macaroon', macaroon)]):
    print(response2)
```

### Expected behaviour

{ 
    "payment_error": <string>,
    "payment_preimage": <bytes>,
    "payment_route": <Route>,
}

### Actual behaviour
ERROR:grpc._channel:Exception iterating requests!
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/grpc/_channel.py", line 192, in consume_request_iterator
    request = next(request_iterator)
  File "probe_channel.py", line 56, in request_generator
    routes=response,
TypeError: Value must be iterable
Traceback (most recent call last):
  File "probe_channel.py", line 63, in <module>
    for response2 in stub.SendToRoute(request_iterable, metadata=[('macaroon', macaroon)]):
  File "/home/user/.local/lib/python2.7/site-packages/grpc/_channel.py", line 367, in next
    return self._next()
  File "/home/user/.local/lib/python2.7/site-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"

**Comment by ranchalp** [comment]
Solved, the routes must not be `response` but rather `response.__getattribute__('routes')`, which is iterable.

**Comment by ranchalp** [comment]
`response`
