### ISSUE TITLE
Segfault on WSL

### ISSUE THREAD

**Issue by sipsorcery** [lightningnetwork/lnd#2218]
### Background

lnd segfaults on WSL.

Note following same install instructions and using the same configuration on an Ubuntu 18.04 Virtual Machine seems to work correctly.

### Your environment

* version of `lnd`: HEAD #8924d8fb20eb2abfd9cc93c6cc7eb6951184cb88
* which operating system (`uname -a` on *Nix): Windows 10
* version of `btcd`, `bitcoind`, or other backend: bitcoind
* any other relevant environment details: Windows Subsystem for Linux 18.04

### Steps to reproduce

* Installed as per instructions @ https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md
* ~/gocode/src/github.com/lightningnetwork/lnd$ lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=admin --bitcoind.rpcpass=password --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

### Actual behaviour
```
aaron@pcdodo:~/gocode/src/github.com/lightningnetwork/lnd$ lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=bitcoind --bitcoind.rpcuser=admin --bitcoind.rpcpass=password --bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332 --bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
2018-11-25 18:38:55.338 [WRN] LTND: open /home/aaron/.lnd/lnd.conf: no such file or directory
2018-11-25 18:38:55.339 [INF] LTND: Version: 0.5.0-beta commit=v0.5-beta-347-gfd5b24fb4ebc3af3ad4be789c9b0c295110c7985, build=production, logging=default
2018-11-25 18:38:55.339 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-11-25 18:38:55.344 [INF] CHDB: Checking for schema update: latest_version=6, db_version=6
2018-11-25 18:38:55.358 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2018-11-25 18:38:55.358 [INF] RPCS: password RPC server listening on 127.0.0.1:10009
2018-11-25 18:38:55.358 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2018-11-25 18:39:07.159 [INF] LNWL: Opened wallet
2018-11-25 18:39:07.231 [INF] LTND: Primary chain is set to: bitcoin
2018-11-25 18:39:07.236 [INF] LTND: Initializing bitcoind backed fee estimator
2018-11-25 18:39:07.236 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:28332
2018-11-25 18:39:07.236 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:28333
2018-11-25 18:39:07.238 [DBG] LNWL: Using minimum fee rate of 253 sat/kw
2018-11-25 18:39:08.142 [INF] LNWL: The wallet has been unlocked without a time limit
2018-11-25 18:39:08.143 [INF] LTND: LightningWallet opened
2018-11-25 18:39:08.147 [INF] LNWL: Catching up block hashes to height 1445190, this will take a while...
2018-11-25 18:39:08.154 [INF] HSWC: Restoring in-memory circuit state from disk
2018-11-25 18:39:08.157 [INF] LNWL: Caught up to height 10000
2018-11-25 18:39:08.158 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
2018-11-25 18:39:08.163 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2018-11-25 18:39:08.169 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2018-11-25 18:39:08.174 [INF] LTND: Waiting for chain backend to finish sync, start_height=1445190
2018-11-25 18:39:23.374 [INF] LNWL: Caught up to height 20000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7544fa]

goroutine 114 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr.putSyncedTo(0x0, 0x0, 0xc420936140, 0x1, 0xc420936140)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr/db.go:1832 +0x3a
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr.(*Manager).SetSyncedTo(0xc4202b21c0, 0x0, 0x0, 0xc420936140, 0x0, 0x0)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr/sync.go:62 +0x93
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).syncWithChain(0xc420360000, 0x0, 0x0)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/wallet.go:511 +0x65a
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications.func1(0xc420360000)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/chainntfns.go:32 +0x2f
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/chainntfns.go:99 +0x9cf
```

**Comment by wpaulino** [comment]
Faulty line points to https://github.com/btcsuite/btcwallet/blob/6d43b2e29b5eef0f000a301ee6fbd146db75d118/waddrmgr/db.go#L1832. Looks like the `walletdb.ReadWriteBucket` being passed in is `nil`.

**Comment by sipsorcery** [comment]
Latest source:

```
2018-12-03 22:00:04.683 [INF] LNWL: Caught up to height 760000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7544fa]

goroutine 76 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr.putSyncedTo(0x0, 0x0, 0xc4208aba00, 0x1, 0xc4208aba00)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr/db.go:1832 +0x3a
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr.(*Manager).SetSyncedTo(0xc42032e1c0, 0x0, 0x0, 0xc4208aba00, 0x0, 0x0)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/waddrmgr/sync.go:62 +0x93
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).syncWithChain(0xc4205cc000, 0x0, 0x0)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/wallet.go:511 +0x65a
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications.func1(0xc4205cc000)
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/chainntfns.go:32 +0x2f
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications
        /home/aaron/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/chainntfns.go:99 +0x9cf
```

**Comment by molxyz** [comment]
@sipsorcery Hi, 

I'm wondering if WSL is not capable of handling lightning and bitcoin nodes on the same environment because I used to run bitcoind and c-lightning nodes on testnet, and bitcoind could fully sync but c-lightning could never sync to the current blockheight. This wasn't the case when I put the nodes on a VPS server which had the same Ubuntu version 16.04.  I do have Ubuntu Bionic for my WSL currently, haven't tried to run bitcoind + lnd on it, but it seems to me WSL is for compiling software and not a suitable environment to run nodes. 

I've installed linux commands for windows such as `make, git, curl`, etc , been compiling LND, btcd on cmd.exe and running btcd, bitcoind, lnd in native windows10.  I'm wondering if you get btcd and lnd updated to the latest commit, and run them in windows, not WSL, your issues might be solved?

**Comment by sipsorcery** [comment]
@molxyz I would agree that WSL is not likely to be a great option for running long running daemons. But it is a very useful environment for experimenting. I have various vm's for bits and pieces do find it handier to use WSL in a not insignificant number of cases.

In relation to this particular issue I suspect the devs would like to be aware of any segfaults even if it's only as an fyi. I did eventually get my LND to sync up to the current block height (I'd estimate it segfaulted 30 or more times during while doing so). Once synced I didn't have any further issues.
