### ISSUE TITLE
panic due to htlc mismatch on startup

### ISSUE THREAD

**Issue by bockha** [lightningnetwork/lnd#2316]
### Background

lnd panics right after startup with an ```htlc mismatch``` message with regard to channel [1425812594046205952](https://1ml.com/testnet/channel/1425812594046205952). If I block the connection to the remote host via iptables, lnd starts up without crash.

Is this channel with over six months too old or broken due to issues with earlier versions of lnd? 

### Your environment

* Version: 0.5.1-beta commit=v0.5.1-beta-154-g71444e74acc9896d31205bd16b70fd0f85fc691b, build=production, logging=default
* Linux iuno010389 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* bitcoind 0.16.3
* $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bitcoind-core/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bitcoind-core/gocode"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build434632927=/tmp/go-build -gno-record-gcc-switches"

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

```
2018-12-11 19:23:50.217 [INF] LTND: Version: 0.5.1-beta commit=v0.5.1-beta-154-g71444e74acc9896d31205bd16b70fd0f85fc691b, build=production, logging=default
2018-12-11 19:23:50.217 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-12-11 19:23:50.218 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2018-12-11 19:23:50.401 [INF] LTND: Primary chain is set to: bitcoin
2018-12-11 19:23:50.427 [INF] LTND: Initializing bitcoind backed fee estimator
2018-12-11 19:23:50.427 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:28332
2018-12-11 19:23:50.427 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:28331
2018-12-11 19:23:51.885 [INF] LNWL: Opened wallet
2018-12-11 19:23:53.181 [INF] LNWL: The wallet has been unlocked without a time limit
2018-12-11 19:23:53.184 [INF] LTND: LightningWallet opened
2018-12-11 19:23:53.312 [INF] HSWC: Restoring in-memory circuit state from disk
2018-12-11 19:23:53.502 [INF] HSWC: Payment circuits loaded: num_pending=160, num_open=17
2018-12-11 19:23:53.522 [INF] HSWC: Trimming open circuits for chan_id=1325502:122:0, start_htlc_id=0
2018-12-11 19:23:53.522 [INF] HSWC: Trimming open circuits for chan_id=1322709:3:0, start_htlc_id=3
2018-12-11 19:23:53.522 [INF] HSWC: Trimming open circuits for chan_id=1326331:244:0, start_htlc_id=3
2018-12-11 19:23:53.523 [INF] HSWC: Trimming open circuits for chan_id=1325231:42:0, start_htlc_id=2
2018-12-11 19:23:53.523 [INF] HSWC: Trimming open circuits for chan_id=1325235:129:0, start_htlc_id=0
2018-12-11 19:23:53.523 [INF] HSWC: Trimming open circuits for chan_id=1322694:16:0, start_htlc_id=21
2018-12-11 19:23:53.524 [INF] HSWC: Trimming open circuits for chan_id=1325187:94:0, start_htlc_id=0
2018-12-11 19:23:53.524 [INF] HSWC: Trimming open circuits for chan_id=1325182:147:0, start_htlc_id=6
2018-12-11 19:23:53.524 [INF] HSWC: Trimming open circuits for chan_id=1316483:85:1, start_htlc_id=1
2018-12-11 19:23:53.525 [INF] HSWC: Trimming open circuits for chan_id=1322706:5:0, start_htlc_id=3
2018-12-11 19:23:53.525 [INF] HSWC: Trimming open circuits for chan_id=1414767:68:1, start_htlc_id=0
2018-12-11 19:23:53.525 [INF] HSWC: Trimming open circuits for chan_id=1446472:48:1, start_htlc_id=0
2018-12-11 19:23:53.526 [INF] HSWC: Trimming open circuits for chan_id=1325918:13:0, start_htlc_id=0
2018-12-11 19:23:53.526 [INF] HSWC: Trimming open circuits for chan_id=1296769:103:0, start_htlc_id=58
2018-12-11 19:23:53.660 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2018-12-11 19:23:53.661 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
.....
2018-12-11 19:23:58.911 [INF] CMGR: Server listening on [::]:19735
2018-12-11 19:23:59.031 [INF] SRVR: Initializing peer network bootstrappers!
2018-12-11 19:23:59.032 [INF] SRVR: Creating DNS peer bootstrapper with seeds: [[test.nodes.lightning.directory soa.nodes.lightning.directory]]
2018-12-11 19:23:59.033 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[test.nodes.lightning.directory soa.nodes.lightning.directory]]
2018-12-11 19:23:59.062 [INF] SRVR: Established connection to: 85.216.75.225:19735
2018-12-11 19:23:59.063 [INF] SRVR: Finalizing connection to 03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415, inbound=false
2018-12-11 19:23:59.086 [INF] SRVR: Established connection to: 176.9.89.217:2000
2018-12-11 19:23:59.086 [INF] SRVR: Finalizing connection to 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2, inbound=false
2018-12-11 19:23:59.087 [INF] PEER: NodeKey(03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415) loading ChannelPoint(fcc7dec9a2eb72a742e21605720208b8953b97629b498f991c9e086838d6542e:1)
2018-12-11 19:23:59.088 [INF] SRVR: Established connection to: 35.158.243.90:9735
2018-12-11 19:23:59.088 [INF] SRVR: Finalizing connection to 0277622bf4c497475960bf91bd3c673a4cb4e9b589cebfde9700c197b3989cc1b8, inbound=false
2018-12-11 19:23:59.092 [INF] HSWC: Removing channel link with ChannelID(2e54d63868089e1c998f499b62973b95b80802720516e242a772eba2c9dec7fd)
2018-12-11 19:23:59.093 [INF] HSWC: ChannelLink(fcc7dec9a2eb72a742e21605720208b8953b97629b498f991c9e086838d6542e:1) is starting
2018-12-11 19:23:59.095 [INF] SRVR: Established connection to: 5.102.147.62:9735
2018-12-11 19:23:59.095 [INF] SRVR: Finalizing connection to 03a13a469bae4785e27fae24e7664e648cfdb976b97f95c694dea5e55e7d302846, inbound=false
2018-12-11 19:23:59.095 [INF] HSWC: Trimming open circuits for chan_id=1414767:68:1, start_htlc_id=0
2018-12-11 19:23:59.095 [INF] HSWC: Adding live link chan_id=2e54d63868089e1c998f499b62973b95b80802720516e242a772eba2c9dec7fd, short_chan_id=1414767:68:1
2018-12-11 19:23:59.108 [INF] PEER: NodeKey(03adf1a17ab83438f23bc6c3b87ed8664757923988d5907c469840ddba1a7d1415) loading ChannelPoint(04895cfa6911b7f2a15937617549b5ad6b5f39e3236e11265b348002ea9f3bd7:1)
2018-12-11 19:23:59.110 [INF] SRVR: Established connection to: 86.61.67.183:9735
2018-12-11 19:23:59.118 [INF] SRVR: Finalizing connection to 03fd0aebde8713e9c311f22468d3d0524e788b1ef57f4cda41bf5b5a2300fc5cd6, inbound=false
2018-12-11 19:23:59.118 [INF] PEER: NodeKey(0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2) loading ChannelPoint(6691f1acff1f125af9b290f79bd7e85a06c8ab498d242b7b7286cf2b4814b281:0)
2018-12-11 19:23:59.110 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(fcc7dec9a2eb72a742e21605720208b8953b97629b498f991c9e086838d6542e:1)
2018-12-11 19:23:59.110 [INF] HSWC: HTLC manager for ChannelPoint(fcc7dec9a2eb72a742e21605720208b8953b97629b498f991c9e086838d6542e:1) started, bandwidth=5130856000 mSAT
2018-12-11 19:23:59.120 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(fcc7dec9a2eb72a742e21605720208b8953b97629b498f991c9e086838d6542e:1)
2018-12-11 19:23:59.131 [INF] PEER: NodeKey(0277622bf4c497475960bf91bd3c673a4cb4e9b589cebfde9700c197b3989cc1b8) loading ChannelPoint(50e8b35a8b129c8329b7b622e1824a6cd7369d0ece53be40920c6a49f5d4989f:0)
2018-12-11 19:23:59.138 [INF] PEER: NodeKey(03a13a469bae4785e27fae24e7664e648cfdb976b97f95c694dea5e55e7d302846) loading ChannelPoint(5f94b13a01e9f0153cd6e1fb3576a3575844fd76b1ffa4e90e798c65f7cb42fa:0)
2018-12-11 19:23:59.145 [INF] HSWC: Removing channel link with ChannelID(d73b9fea0280345b26116e23e3395f6badb54975613759a1f2b71169fa5c8905)
2018-12-11 19:23:59.145 [INF] HSWC: ChannelLink(04895cfa6911b7f2a15937617549b5ad6b5f39e3236e11265b348002ea9f3bd7:1) is starting
panic: htlc index mismatch: 57 vs 58

goroutine 2900 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc0006d0a00, 0xc000234240, 0xc000234300, 0xc0002343c0, 0xc0006d0b00, 0xc0007de1e0, 0x0, 0x0)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1826 +0xa5b
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc0006d0a00, 0xc000533a78, 0xc0005339f8, 0x0, 0xc000966c00)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1706 +0x480
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel(0x127a360, 0xc0000b4c60, 0x7fde456fb188, 0xc0002b0000, 0xc000230900, 0xc000966a40, 0xc0004be040, 0x1)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1399 +0x5c6
main.(*peer).loadActiveChannels(0xc000dc2000, 0xc0000b24d0, 0x1, 0x1, 0x2, 0x2)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/peer.go:384 +0x124
main.(*peer).Start(0xc000dc2000, 0x11820e8, 0xc00024aa80)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/peer.go:316 +0x6fb
main.(*server).peerInitializer(0xc00024aa80, 0xc000dc2000)
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/server.go:2395 +0x10d
created by main.(*server).peerConnected
        /home/bitcoind-core/gocode/src/github.com/lightningnetwork/lnd/server.go:2330 +0x409
```

**Comment by Roasbeef** [comment]
> Is this channel with over six months too old or broken due to issues with earlier versions of lnd?

It may have been this occurred back then, as to our knowledge new channels cannot entire this state. As we've fixed bugs w.r.t what we write to disk to save the state of a channel so we can restore it. Will leave the investigation up to @halseth, thanks for the report!
