### ISSUE TITLE
lnd crash (SIGSEGV) when doing listchaintxns

### ISSUE THREAD

**Issue by jogc** [lightningnetwork/lnd#2353]
Was trying to do a 'lncli listchaintxns' when it happened

lnd: lnd-linux-amd64-v0.5-beta

Dec 20 08:48:18 X lnd[607]: 2018-12-20 08:48:18.400 [INF] DISC: Removing gossipSyncer for peer=0385d85c436b26e161e8ed6bc85447887b1759de110053e89e0022c8ee1d33fbde
Dec 20 08:48:22 X lnd[607]: 2018-12-20 08:48:22.754 [INF] DISC: gossipSyncer(02b3877314aff657216ceac039244fe94e7116af10cfffac0232fefa5903c62a58): fetching chan anns for 1 chans
Dec 20 08:48:22 X lnd[607]: 2018-12-20 08:48:22.754 [INF] DISC: gossipSyncer(02b3877314aff657216ceac039244fe94e7116af10cfffac0232fefa5903c62a58): rate limiting gossip replies, responding in 4.998774295s
Dec 20 08:48:22 X lnd[607]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 20 08:48:22 X lnd[607]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xceb18d]
Dec 20 08:48:22 X lnd[607]: goroutine 49864887 [running]:
Dec 20 08:48:22 X lnd[607]: main.(*rpcServer).GetTransactions(0xc0009edef0, 0x1204760, 0xc01d2e9920, 0x1a24318, 0xc0009edef0, 0xc01cdde440, 0xc0002d1a40)
Dec 20 08:48:22 X lnd[607]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:3021 +0x20d
Dec 20 08:48:22 X lnd[607]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler.func1(0x1204760, 0xc01d2e9920, 0xe8f6a0, 0x1a24318, 0x1, 0x1, 0x0, 0x0)
Dec 20 08:48:22 X lnd[607]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6271 +0x89
Dec 20 08:48:22 X lnd[607]: github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0x1204760, 0xc01d2e9920, 0xe8f6a0, 0x1a24318, 0xc01cdde420, 0xc01cdde440, 0xc001abdb50, 0x40c478, 0x50, 0xf32b80)
Dec 20 08:48:22 X lnd[607]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:126 +0x153
Dec 20 08:48:22 X lnd[607]: github.com/lightningnetwork/lnd/lnrpc._Lightning_GetTransactions_Handler(0xf8aa60, 0xc0009edef0, 0x1204760, 0xc01d2e9920, 0xc006dcd860, 0xc0010e0100, 0x0, 0x0, 0xc0010ae860, 0x10)
Dec 20 08:48:22 X lnd[607]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:6273 +0x158
Dec 20 08:48:22 X lnd[607]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000432780, 0x1209e40, 0xc0008ad680, 0xc0146cbb00, 0xc000702030, 0x19e2130, 0xc003211440, 0x0, 0x0)
Dec 20 08:48:22 X lnd[607]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x8ec
Dec 20 08:48:22 X lnd[607]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000432780, 0x1209e40, 0xc0008ad680, 0xc0146cbb00, 0xc003211440)
Dec 20 08:48:22 X lnd[607]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1308
Dec 20 08:48:22 X lnd[607]: github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0114a7560, 0xc000432780, 0x1209e40, 0xc0008ad680, 0xc0146cbb00)
Dec 20 08:48:22 X lnd[607]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x9f

**Comment by jogc** [comment]
Thanks, I'll close
