### ISSUE TITLE
SIGSEGV: segmentation violation - establishPersistentConnections

### ISSUE THREAD

**Issue by lispmeister** [lightningnetwork/lnd#2427]
### Background

LND crashes with signal SIGSEGV: segmentation violation

### Your environment

* version of `lnd`
lnd-linux-armv7-v0.5.1-beta-rc1

* which operating system (`uname -a` on *Nix)
Linux 4.14.87-153 SMP PREEMPT armv7l armv7l armv7l
This is an `18.04.1 LTS (GNU/Linux 4.14.87-153 armv7l)` running on an ODROID-HC2.

* version of `btcd`, `bitcoind`, or other backend
bitcoin-0.17.1-arm-linux-gnueabihf

* any other relevant environment details
Server hardware is an ODROID-HC2 with 2GB of RAM.

### Steps to reproduce
Install release v0.5.1-beta-rc1. 
Use the following lnd.conf:
```
[Application Options]
debuglevel=info
#debughtlc=true
maxpendingchannels=5
alias= XXXXXX [LND]
color=#68F442
restlisten=localhost:8080
[Bitcoin]
bitcoin.active=1
# enable either testnet or mainnet
#bitcoin.testnet=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6
```
The LND process gets as far as `Server listening on` and then crashes:
```
Jan  6 17:26:29  lnd[29960]: 2019-01-06 17:26:29.198 [INF] CRTR: Graph pruning complete: 69 channels were closed since height 557204
Jan  6 17:26:29  lnd[29960]: 2019-01-06 17:26:29.225 [INF] CMGR: Server listening on [::]:9735
Jan  6 17:26:29  lnd[29960]: 2019-01-06 17:26:29.243 [INF] LTND: Shutdown complete
Jan  6 17:26:29  lnd[29960]: panic: runtime error: invalid memory address or nil pointer dereference
Jan  6 17:26:29  lnd[29960]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x7c5544]
Jan  6 17:26:29  lnd[29960]: goroutine 1 [running]:
Jan  6 17:26:29  lnd[29960]: main.(*server).establishPersistentConnections.func1(0x15c0a80, 0x1bc2000, 0x0, 0x0, 0x1bc2028, 0x21)
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/server.go:1649 +0x18
Jan  6 17:26:29  lnd[29960]: github.com/lightningnetwork/lnd/channeldb.(*LightningNode).ForEachChannel.func1(0x15c0a80, 0xb06b54, 0x15c0a80)
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2017 +0x420
Jan  6 17:26:29  lnd[29960]: github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).View(0x1666000, 0x1f14be0, 0x0, 0x0)
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:699 +0x84
Jan  6 17:26:29  lnd[29960]: github.com/lightningnetwork/lnd/channeldb.(*LightningNode).ForEachChannel(0x15c0980, 0x0, 0x193c780, 0x0, 0x0)
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2029 +0xa0
Jan  6 17:26:29  lnd[29960]: main.(*server).establishPersistentConnections(0x1810270, 0x0, 0x0)
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/server.go:1644 +0x2a4
Jan  6 17:26:29  lnd[29960]: main.(*server).Start(0x1810270, 0x9c1c2a, 0x2e)
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/server.go:991 +0x1dc
Jan  6 17:26:29  lnd[29960]: main.lndMain(0x0, 0x0)
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/lnd.go:417 +0xf00
Jan  6 17:26:29  lnd[29960]: main.main()
Jan  6 17:26:29  lnd[29960]: #011/Users/johan/golang/src/github.com/lightningnetwork/lnd/lnd.go:449 +0x14
Jan  6 17:26:29  systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan  6 17:26:29  systemd[1]: lnd.service: Failed with result 'exit-code'.
```

### Expected behaviour
LND should boot up, restore state and connect to peers.

### Actual behaviour
LND crashes when trying to establish persistent connections.

**Comment by lispmeister** [comment]
Seems I spoke too soon. The bug described above surfaced again. I built LND from `master`.
Steps to reproduce:
1. Install go1.11.4 for ARM
2. Setup go environment as described in LND's `INSTALL.md`
3. 
```
go get -d github.com/lightningnetwork/lnd
cd $GOPATH/src/github.com/lightningnetwork/lnd
make && make install
```
The most recent commit on `master` was:
`commit 5c41243f35d3d4459d272eeebedda692172c2d41 (HEAD -> master, origin/master, origin/HEAD)`

Log entry for the crash (same hardware as described above):
```
Jan  9 00:03:39  lnd[22320]: 2019-01-09 00:03:39.684 [INF] CRTR: Graph pruning complete: 120 channels were closed since height 557471
Jan  9 00:03:39  lnd[22320]: 2019-01-09 00:03:39.712 [INF] CMGR: Server listening on [::]:9735
Jan  9 00:03:39  lnd[22320]: 2019-01-09 00:03:39.722 [INF] RPCS: Stopping RPC Server
Jan  9 00:03:39  lnd[22320]: 2019-01-09 00:03:39.751 [INF] LTND: Shutdown complete
Jan  9 00:03:39  lnd[22320]: panic: runtime error: invalid memory address or nil pointer dereference
Jan  9 00:03:39  lnd[22320]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x81ced0]
Jan  9 00:03:39  lnd[22320]: goroutine 1 [running]:
Jan  9 00:03:39  lnd[22320]: main.(*server).establishPersistentConnections.func1(0x194de80, 0x190c5a0, 0x0, 0x0, 0x190c5c8, 0x21)
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/src/github.com/lightningnetwork/lnd/server.go:1684 +0x18
Jan  9 00:03:39  lnd[22320]: github.com/lightningnetwork/lnd/channeldb.(*LightningNode).ForEachChannel.func1(0x194de80, 0xb797e4, 0x194de80)
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2026 +0x420
Jan  9 00:03:39  lnd[22320]: github.com/coreos/bbolt.(*DB).View(0x1992120, 0x2f16620, 0x0, 0x0)
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/pkg/mod/github.com/coreos/bbolt@v0.0.0-20180223184059-7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/db.go:701 +0x84
Jan  9 00:03:39  lnd[22320]: github.com/lightningnetwork/lnd/channeldb.(*LightningNode).ForEachChannel(0x194dd80, 0x0, 0x1abb460, 0x0, 0x0)
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2038 +0xa0
Jan  9 00:03:39  lnd[22320]: main.(*server).establishPersistentConnections(0x1800a80, 0x0, 0x0)
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/src/github.com/lightningnetwork/lnd/server.go:1679 +0x2a4
Jan  9 00:03:39  lnd[22320]: main.(*server).Start(0x1800a80, 0xa33600, 0x2e)
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/src/github.com/lightningnetwork/lnd/server.go:1024 +0x21c
Jan  9 00:03:39  lnd[22320]: main.lndMain(0x0, 0x0)
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/src/github.com/lightningnetwork/lnd/lnd.go:387 +0xd38
Jan  9 00:03:39  lnd[22320]: main.main()
Jan  9 00:03:39  lnd[22320]: #011/home/admin/gocode/src/github.com/lightningnetwork/lnd/lnd.go:413 +0x14
Jan  9 00:03:39  systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan  9 00:03:39  systemd[1]: lnd.service: Failed with result 'exit-code'.
```

**Comment by wpaulino** [comment]
@lispmeister until the proper fix is in, you can get your node back up and running with the following patch:

```diff --git a/server.go b/server.go
index c3378839..4efc67d3 100644
--- a/server.go
+++ b/server.go
@@ -1677,6 +1677,10 @@ func (s *server) establishPersistentConnections() error {
 		_ *channeldb.ChannelEdgeInfo,
 		policy, _ *channeldb.ChannelEdgePolicy) error {
 
+		if policy == nil {
+			return nil
+		}
+
 		pubStr := string(policy.Node.PubKeyBytes[:])
 
 		// Add all unique addresses from channel graph/NodeAnnouncements

```

**Comment by lispmeister** [comment]
Thanks @wpaulino, that's seems like an obvious temporary workaround. Will give that a try.

I'm willing to dive in and prepare a PR with a proper fix if someone could provide a suggestion how this issue should be fixed. I'm not sure I understand the root cause.

**Comment by darklow** [comment]
I also got same error on latest `v0.5.2-beta-rc6`. Applying temporary fix and recompiling allowed to start node again.
