### ISSUE TITLE
Integration tests fail sometimes after latest update

### ISSUE THREAD

**Issue by BitfuryLightning** [lightningnetwork/lnd#243]
go version: go1.7.1 linux/amd64
lnd version:  24db310aefd5913dd6e56de22dd474e65d1f0d6b
btcd verision:  f8c02aff4e7a807ba0c1349e2db03695d8e790e8

Sometimes (20%)
```
$ go test -v -tags rpctest
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon/basic_funding_flow
=== RUN   TestLightningNetworkDaemon/disconnecting_target_peer
=== RUN   TestLightningNetworkDaemon/graph_topology_notifications
=== RUN   TestLightningNetworkDaemon/funding_flow_persistence
=== RUN   TestLightningNetworkDaemon/channel_force_closure
=== RUN   TestLightningNetworkDaemon/channel_balance
--- FAIL: TestLightningNetworkDaemon (50.07s)
	lnd_test.go:3077: Running 18 integration tests
    --- PASS: TestLightningNetworkDaemon/basic_funding_flow (0.63s)
    --- PASS: TestLightningNetworkDaemon/disconnecting_target_peer (0.75s)
    --- PASS: TestLightningNetworkDaemon/graph_topology_notifications (5.65s)
    --- PASS: TestLightningNetworkDaemon/funding_flow_persistence (18.41s)
    --- PASS: TestLightningNetworkDaemon/channel_force_closure (8.75s)
    --- FAIL: TestLightningNetworkDaemon/channel_balance (5.00s)
    	lnd_test.go:66: Failed: (channel balance): exited with error: 
    		*errors.errorString unable to open channel: Unable to sync destNode chain: Timeout while waiting for blockchain sync
    		/home/twenty/gocode/src/github.com/lightningnetwork/lnd/lnd_test.go:146 (0x48e539)
    			openChannelAndAssert: t.Fatalf("unable to open channel: %v", err)
    		/home/twenty/gocode/src/github.com/lightningnetwork/lnd/lnd_test.go:658 (0x49200b)
    			testChannelBalance: amount, 0)
    		/home/twenty/gocode/src/github.com/lightningnetwork/lnd/lnd_test.go:88 (0x48dabb)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/twenty/gocode/src/github.com/lightningnetwork/lnd/lnd_test.go:3081 (0x4aa679)
    			TestLightningNetworkDaemon.func2: ht.RunTestCase(testCase, lndHarness)
    		/usr/local/go/src/testing/testing.go:610 (0x47dd31)
    			tRunner: fn(t)
    		/usr/local/go/src/runtime/asm_amd64.s:2086 (0x45e851)
    			goexit: BYTE	$0x90	// NOP
=== RUN   TestAddSerializedKidsToList
--- PASS: TestAddSerializedKidsToList (0.00s)
=== RUN   TestSerializeKidOutput
--- PASS: TestSerializeKidOutput (0.00s)
FAIL
exit status 1
FAIL	github.com/lightningnetwork/lnd	50.112s

Sometimes (30%)
test freezes and than exist after timeout

$ go test -v -tags rpctest
=== RUN   TestLightningNetworkDaemon
SIGQUIT: quit
PC=0x45fa89 m=0

goroutine 0 [idle]:
runtime.epollwait(0x5, 0x7ffc130a9688, 0xffffffff00000080, 0xfffffffc, 0xffffffff00000000, 0xfffffffc, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:525 +0x19
runtime.netpoll(0x10d4c01, 0x0)
	/usr/local/go/src/runtime/netpoll_epoll.go:67 +0x93
runtime.findrunnable(0xc420020000, 0x0)
	/usr/local/go/src/runtime/proc.go:2003 +0x28c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2120 +0x14c
runtime.park_m(0xc4201e4000)
	/usr/local/go/src/runtime/proc.go:2183 +0x123
runtime.mcall(0x7ffc130a9e00)
	/usr/local/go/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc4204d4180, 0xbd8e15, 0x1a, 0xd65600, 0xc4203f7d20)
	/usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc4204d4180)
	/usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc4204d4180, 0xc420039e30)
	/usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0xd669e0, 0x10c66e0, 0x3, 0x3, 0xc4200106c0)
	/usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc420039ef8, 0xc4204d40c0)
	/usr/local/go/src/testing/testing.go:743 +0x85
main.main()
	github.com/lightningnetwork/lnd/_test/_testmain.go:58 +0xc6

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 372 [syscall, 9 minutes]:
syscall.Syscall(0x0, 0xd, 0xc4201c4000, 0x200, 0x200, 0xc4201c4000, 0x7fb2244811a8)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xd, 0xc4201c4000, 0x200, 0x200, 0x7fb2244c34b0, 0x0, 0x6)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0xd, 0xc4201c4000, 0x200, 0x200, 0x0, 0xc42008c000, 0xc420074d00)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x49
os.(*File).read(0xc4204ccd90, 0xc4201c4000, 0x200, 0x200, 0x4eae2b, 0xa9e720, 0x200)
	/usr/local/go/src/os/file_unix.go:228 +0x4f
os.(*File).Read(0xc4204ccd90, 0xc4201c4000, 0x200, 0x200, 0x40eb4c, 0x10d4d60, 0xc420025e20)
	/usr/local/go/src/os/file.go:101 +0x59
bytes.(*Buffer).ReadFrom(0xc4201ca540, 0x1096080, 0xc4204ccd90, 0xc420025e88, 0x42dc01, 0xc420025e60)
	/usr/local/go/src/bytes/buffer.go:176 +0x155
io.copyBuffer(0x1094540, 0xc4201ca540, 0x1096080, 0xc4204ccd90, 0x0, 0x0, 0x0, 0x0, 0xc420016eb0, 0xc420074d00)
	/usr/local/go/src/io/io.go:384 +0x323
io.Copy(0x1094540, 0xc4201ca540, 0x1096080, 0xc4204ccd90, 0x0, 0xc420025f80, 0x4047cd)
	/usr/local/go/src/io/io.go:360 +0x68
os/exec.(*Cmd).writerDescriptor.func1(0x1, 0xc420025fa8)
	/usr/local/go/src/os/exec/exec.go:253 +0x4d
os/exec.(*Cmd).Start.func1(0xc4204fe160, 0xc4201c0a20)
	/usr/local/go/src/os/exec/exec.go:370 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:371 +0x4db

goroutine 18 [syscall, 9 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc4201b8c0c)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4201b8c00)
	/usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/lightningnetwork/lnd.(*networkHarness).SetUp(0xc4204fc000, 0xc4204c6960, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:758 +0x166
github.com/lightningnetwork/lnd.TestLightningNetworkDaemon(0xc4204d4240)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/lnd_test.go:3073 +0x4a3
testing.tRunner(0xc4204d4240, 0xd65600)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 382 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fb22443e798, 0x72, 0x7)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201905a0, 0x72, 0xc4202c0af0, 0xc4200101c0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201905a0, 0x1098280, 0xc4200101c0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420190540, 0xc4203f0000, 0x8000, 0x8000, 0x0, 0x1098280, 0xc4200101c0)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4204cc028, 0xc4203f0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc4201d1140)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc4201d1140, 0xc4204fc2d8, 0x9, 0x9, 0xc4202c0ce0, 0x944e09, 0xc4201a69f8)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x1094480, 0xc4201d1140, 0xc4204fc2d8, 0x9, 0x9, 0x9, 0x10d5940, 0xc4204e8340, 0xd66810)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1094480, 0xc4201d1140, 0xc4204fc2d8, 0x9, 0x9, 0xc4202c0d56, 0xc4205161e0, 0xc4204119e0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2.readFrameHeader(0xc4204fc2d8, 0x9, 0x9, 0x1094480, 0xc4201d1140, 0x0, 0x0, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4204fc2a0, 0x0, 0x0, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2/frame.go:492 +0x8e
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc4201a6750, 0xc4205161e0, 0xc420516100, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http_util.go:506 +0x2f
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc42052d080)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:1039 +0x112
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:247 +0xd16

goroutine 389 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc42014d400, 0xc4201c0290, 0x5, 0x5, 0x0, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/transport.go:143 +0x69a
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc420090480, 0xc4201c0290, 0x5, 0x5, 0xc420090550, 0xffffffff, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/transport.go:333 +0x5c
io.ReadAtLeast(0x1095300, 0xc420090480, 0xc4201c0290, 0x5, 0x5, 0x5, 0x4d5b1b, 0x0, 0xc0000000)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1095300, 0xc420090480, 0xc4201c0290, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc4201c0280, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/rpc_util.go:243 +0x6f
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.recv(0xc4201c0280, 0x109dc00, 0x10f1e28, 0xc420090480, 0x0, 0x0, 0xb54140, 0xc420016c30, 0x7fffffff, 0x0, ...)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/rpc_util.go:339 +0x4d
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc420077080, 0xb54140, 0xc420016c30, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/stream.go:386 +0x120
github.com/lightningnetwork/lnd/lnrpc.(*lightningSubscribeChannelGraphClient).Recv(0xc420010e80, 0x7fb224487d28, 0xc420010778, 0x10f1e28)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:3444 +0x62
github.com/lightningnetwork/lnd.(*lightningNode).lightningNetworkWatcher.func2(0xc4201cd950, 0xd65588, 0xc42001a900)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:401 +0x14d
created by github.com/lightningnetwork/lnd.(*lightningNode).lightningNetworkWatcher
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:432 +0xee

goroutine 23 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fb22443e858, 0x72, 0x4)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420526760, 0x72, 0xc4202b78c8, 0xc4200101c0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420526760, 0x1098280, 0xc4200101c0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420526700, 0xc4201d2000, 0x4000, 0x4000, 0x0, 0x1098280, 0xc4200101c0)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42002c030, 0xc4201d2000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420516810, 0x7fb224485b10, 0xc42002c030, 0x5, 0xc42002c030, 0xc41fff3610)
	/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc42051c700, 0xd67317, 0xc42051c800, 0x5ffb51)
	/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc42051c700, 0xc420085000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc4204d8ba0)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc4204d8ba0, 0xc4201b8b30, 0x2, 0x8, 0xc4202b7d50, 0x410a78, 0x10)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket.(*Conn).readFull(0xc420408000, 0xc4201b8b30, 0x2, 0x8, 0xc42000c620, 0x6)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket/conn.go:542 +0x8d
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket.(*Conn).advanceFrame(0xc420408000, 0xc4201b8aa0, 0x200, 0xc4201e9800)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket/conn.go:566 +0x96
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket.(*Conn).NextReader(0xc420408000, 0xc4202b7f20, 0x405e34, 0xa969a0, 0xc4204d8d20, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket/conn.go:706 +0x57
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket.(*Conn).ReadMessage(0xc420408000, 0x0, 0xc4204d8d20, 0x600, 0x600, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/websocket/conn.go:769 +0x2f
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient.(*Client).wsInHandler(0xc4204e2140)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient/infrastructure.go:410 +0x6a
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient.(*Client).start
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient/infrastructure.go:1038 +0x182

goroutine 24 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient.(*Client).wsOutHandler(0xc4204e2140)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient/infrastructure.go:446 +0x290
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient.(*Client).start
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcrpcclient/infrastructure.go:1039 +0x1a4

goroutine 25 [chan receive, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/rpctest.(*memWallet).chainSyncer(0xc4203f83f0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/rpctest/memwallet.go:203 +0x62
created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/rpctest.(*memWallet).Start
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/rpctest/memwallet.go:160 +0x3f

goroutine 373 [syscall, 9 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x1cb6, 0xc420082000, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4201a7710, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/wait_waitid.go:28 +0xbc
os.(*Process).wait(0xc4201a7710, 0xc4204e8d00, 0x4, 0xc42002bfa8)
	/usr/local/go/src/os/exec_unix.go:22 +0xab
os.(*Process).Wait(0xc4201a7710, 0xc4204d88a0, 0xc420522690, 0xc42002bfa8)
	/usr/local/go/src/os/doc.go:49 +0x2b
os/exec.(*Cmd).Wait(0xc4204fe160, 0x4047cd, 0xa969a0)
	/usr/local/go/src/os/exec/exec.go:434 +0x6d
github.com/lightningnetwork/lnd.(*lightningNode).Start.func1(0xc4201cd950, 0xc4204d84e0, 0xc4201ca540)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:222 +0x36
created by github.com/lightningnetwork/lnd.(*lightningNode).Start
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:230 +0x1a1

goroutine 366 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*Stream).Header(0xc4204118c0, 0xd667e8, 0xc4202b9b90, 0x10a1a80)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/transport.go:252 +0x299
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.recvResponse(0x7fb224487d28, 0xc420010778, 0x0, 0x0, 0x109dc00, 0x10f1e28, 0x0, 0x0, 0x0, 0x0, ...)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/call.go:63 +0xaa
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.invoke(0x7fb224487d28, 0xc420010778, 0xbd70e5, 0x18, 0xb15760, 0x10f1e28, 0xb8f020, 0xc4201d0840, 0xc420500900, 0x0, ...)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/call.go:265 +0xa09
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.Invoke(0x7fb224487d28, 0xc420010778, 0xbd70e5, 0x18, 0xb15760, 0x10f1e28, 0xb8f020, 0xc4201d0840, 0xc420500900, 0x0, ...)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/call.go:146 +0x19c
github.com/lightningnetwork/lnd/lnrpc.(*lightningClient).GetInfo(0xc4204cc008, 0x7fb224487d28, 0xc420010778, 0x10f1e28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:3140 +0xd2
github.com/lightningnetwork/lnd.(*lightningNode).Start(0xc4201cda40, 0xc4204d84e0, 0xc4201b8c00, 0xc42002afa8)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:259 +0x5f7
github.com/lightningnetwork/lnd.(*networkHarness).SetUp.func2(0xc4201b8c00, 0xc4204fc000, 0xc4201f6120)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:753 +0x6a
created by github.com/lightningnetwork/lnd.(*networkHarness).SetUp
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:757 +0x155

goroutine 378 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc4200741a0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/clientconn.go:869 +0x63e
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*ClientConn).resetAddrConn
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/clientconn.go:602 +0x6e2

goroutine 377 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc42052c480)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:1112 +0x5e6
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:277 +0x12dd

goroutine 384 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc420212000)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/clientconn.go:869 +0x63e
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*ClientConn).resetAddrConn
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/clientconn.go:602 +0x6e2

goroutine 383 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc42052d080)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:1112 +0x5e6
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:277 +0x12dd

goroutine 376 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fb22443e6d8, 0x72, 0x6)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420191fe0, 0x72, 0xc42003caf0, 0xc4200101c0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420191fe0, 0x1098280, 0xc4200101c0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420191f80, 0xc42023c000, 0x8000, 0x8000, 0x0, 0x1098280, 0xc4200101c0)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4204cc000, 0xc42023c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc4201d0780)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc4201d0780, 0xc4204fc118, 0x9, 0x9, 0x9, 0x18, 0x28)
	/usr/local/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0x1094480, 0xc4201d0780, 0xc4204fc118, 0x9, 0x9, 0x9, 0x410a78, 0x30, 0xc42003cd00)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1094480, 0xc4201d0780, 0xc4204fc118, 0x9, 0x9, 0x71e78d4dd1826801, 0x7100000000000000, 0x2)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2.readFrameHeader(0xc4204fc118, 0x9, 0x9, 0x1094480, 0xc4201d0780, 0x0, 0x0, 0xc4201a64e0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4204fc0e0, 0x1099380, 0xc4201a64e0, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/golang.org/x/net/http2/frame.go:492 +0x8e
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc4201a6150, 0xc4201a64e0, 0xc4201a6400, 0x0, 0x0)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http_util.go:506 +0x2f
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc42052c480)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:1039 +0x112
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/transport/http2_client.go:247 +0xd16

goroutine 388 [select, 9 minutes]:
github.com/lightningnetwork/lnd.(*lightningNode).lightningNetworkWatcher(0xc4201cd950)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:445 +0xec3
created by github.com/lightningnetwork/lnd.(*lightningNode).Start
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/networktest.go:275 +0x6e4

goroutine 390 [select, 9 minutes]:
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.newClientStream.func3(0x10a1a80, 0xc42052d080, 0xc420090480, 0xc420077080)
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/stream.go:236 +0x426
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.newClientStream
	/home/twenty/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/stream.go:256 +0xce0

rax    0xfffffffffffffffc
rbx    0x10d4ce8
rcx    0xffffffffffffffff
rdx    0x80
rdi    0x5
rsi    0x7ffc130a9688
rbp    0x7ffc130a9c88
rsp    0x7ffc130a9648
r8     0xc420036f76
r9     0xc420016df8
r10    0xffffffff
r11    0x246
r12    0x0
r13    0xf1
r14    0xc
r15    0x0
rip    0x45fa89
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/lightningnetwork/lnd	600.006s
```

**Comment by halseth** [comment]
Thanks! We are currently hunting flakes :) If you add the ` -logoutput` flag to the command, you'll find text files (`output*.txt`) containing the node logs, which can be useful for debugging.

**Comment by Roasbeef** [comment]
I think both of those flakes should be fixed at this point int he latest version of master. Can you verify that you don't encounter these flakes anymore? Thanks for the report!

**Comment by Roasbeef** [comment]
I've been watching our builds, and I believe the recent set of bug fixes and concurrency related bug fixes have addressed the issue itself. 

Closing for now due to inactivity, if I see these pop up within the builds I'll re-open this. Thanks for reporting!
