### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by tmconnors** [lightningnetwork/lnd#2574]
### Background

LND encounters an error and the docker container crashes. 

```
  2019-01-29T16:29:46Z lnd UNKNOWN[10147] panic: runtime error: slice bounds out of range
```

### Your environment

Casa Node:
Raspberry Pi
LND: 0.5.1
Bitcoind: 0.17.0, is synced. 

### Expected behaviour

LND boots properly. 

### Actual behaviour

```
  2019-01-29T16:29:46Z lnd UNKNOWN[10147] panic: runtime error: slice bounds out of range
2019-01-29T16:29:46Z lnd UNKNOWN[10147] 
2019-01-29T16:29:46Z lnd UNKNOWN[10147] goroutine 1 [running]:
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*leafPageElement).key(...)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/page.go:120
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).nsearch.func2(0xb803, 0xab100)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:334 +0x94
2019-01-29T16:29:46Z lnd UNKNOWN[10147] sort.Search(0xd24c, 0x4245334, 0x552bc)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/usr/local/go/src/sort/search.go:66 +0x54
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).nsearch(0x424553c, 0x61db5410, 0x8, 0x8)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:333 +0xa8
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).search(0x424553c, 0x61db5410, 0x8, 0x8, 0x206, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:263 +0x154
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).searchPage(0x424553c, 0x61db5410, 0x8, 0x8, 0x5fc64000)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:314 +0x108
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).search(0x424553c, 0x61db5410, 0x8, 0x8, 0x1230, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:271 +0x130
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).searchPage(0x424553c, 0x61db5410, 0x8, 0x8, 0x5f76a000)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:314 +0x108
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).search(0x424553c, 0x61db5410, 0x8, 0x8, 0xd36, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:271 +0x130
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Cursor).seek(0x424553c, 0x61db5410, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x1f9, 0x1f9, ...)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/cursor.go:159 +0xa0
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).Get(0x4b419c0, 0x61db5410, 0x8, 0x8, 0xa8ce26f, 0x72b3f1b6, 0x46a2a6c1)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:260 +0x9c
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/channeldb.fetchChanEdgeInfo(0x4b419c0, 0x61db5410, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/channeldb/graph.go:3063 +0x44
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).ChannelView.func1.1(0x61db53ec, 0x24, 0x24, 0x61db5410, 0x8, 0x8, 0x8, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2731 +0xe4
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*Bucket).ForEach(0x4b41960, 0x4245ca0, 0xa, 0xa)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/bucket.go:388 +0xfc
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).ChannelView.func1(0x2eb8e00, 0xb1875c, 0x2eb8e00)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2722 +0x110
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt.(*DB).View(0x302a280, 0x4245ce4, 0x0, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/vendor/github.com/coreos/bbolt/db.go:699 +0x84
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).ChannelView(0x2de6e80, 0x4898780, 0x88d9d, 0x0, 0x0, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2702 +0x60
2019-01-29T16:29:46Z lnd UNKNOWN[10147] github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start(0x2e66000, 0x0, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/routing/router.go:385 +0x228
2019-01-29T16:29:46Z lnd UNKNOWN[10147] main.(*server).Start(0x2d7c340, 0x9d3614, 0x2e)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/server.go:971 +0x150
2019-01-29T16:29:46Z lnd UNKNOWN[10147] main.lndMain(0x0, 0x0)
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/lnd.go:417 +0xf00
2019-01-29T16:29:46Z lnd UNKNOWN[10147] main.main()
2019-01-29T16:29:46Z lnd UNKNOWN[10147] #011/go/src/github.com/lightningnetwork/lnd/lnd.go:449 +0x14
```

**Comment by Roasbeef** [comment]
Looks like disk corruption on your rasp pi. If it's a Casa node would report it to them to see if they have any further insight.

**Comment by miketwenty1** [comment]
@Roasbeef 

I'm getting a different error now.. 
"Index out of range" 

2019-02-21 04:45:27.897 [INF] LTND: Shutdown complete
panic: runtime error: index out of range
 
```
goroutine 1 [running]:
github.com/coreos/bbolt.(*leafPageElement).key(...)
    /home/ubuntuuser/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/page.go:120
github.com/coreos/bbolt.(*Cursor).keyValue(0xc0003209c0, 0x1b9f200, 0x0, 0x0, 0x1, 0xc010688f60, 0x0, 0x1)
    /home/ubuntuuser/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/cursor.go:350 +0x1b8
github.com/coreos/bbolt.(*Cursor).First(0xc0003209c0, 0x0, 0x0, 0x1b9f200, 0x0, 0x0, 0x10)
    /home/ubuntuuser/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/cursor.go:44 +0x12e
github.com/coreos/bbolt.(*Bucket).ForEach(0xc0106cda80, 0xc000320a28, 0x10, 0x10)
    /home/ubuntuuser/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/bucket.go:387 +0x94
github.com/lightningnetwork/lnd/channeldb.(*DB).fetchNodeChannels(0xc0001ee720, 0xc0106cda80, 0x20, 0x20, 0xc0106cda80, 0x0, 0x0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:386 +0x79
github.com/lightningnetwork/lnd/channeldb.fetchChannels.func1.1.1(0x7fbe36a90020, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:623 +0xc2
github.com/coreos/bbolt.(*Bucket).ForEach(0xc0106cda40, 0xc000320c28, 0x21, 0x21)
    /home/ubuntuuser/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/bucket.go:388 +0x10c
github.com/lightningnetwork/lnd/channeldb.fetchChannels.func1.1(0x7fbe35709bdc, 0x21, 0x21, 0x7fbe35709bfd, 0x38, 0x38, 0x38, 0x0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:607 +0x11b
github.com/coreos/bbolt.(*Bucket).ForEach(0xc0001e2980, 0xc000320d40, 0x3, 0x3)
    /home/ubuntuuser/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/bucket.go:388 +0x10c
github.com/lightningnetwork/lnd/channeldb.fetchChannels.func1(0xc00043c2a0, 0x1212030, 0xc00043c2a0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:601 +0x141
github.com/coreos/bbolt.(*DB).View(0xc0002f2600, 0xc000320e00, 0x0, 0x0)
    /home/ubuntuuser/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/db.go:719 +0x90
github.com/lightningnetwork/lnd/channeldb.fetchChannels(0xc0001ee720, 0x0, 0x1212028, 0x0, 0xc00000d680, 0xa41230, 0xc0001e2580)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:583 +0x84
github.com/lightningnetwork/lnd/channeldb.(*DB).FetchAllOpenChannels(0xc0001ee720, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/channeldb/db.go:547 +0x32
github.com/lightningnetwork/lnd/htlcswitch.(*circuitMap).trimAllOpenCircuits(0xc0001e2580, 0x0, 0x0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/circuit_map.go:387 +0x35
github.com/lightningnetwork/lnd/htlcswitch.NewCircuitMap(0xc0004c22d0, 0xc0004c22d0, 0x10, 0x10, 0xf5e980)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/circuit_map.go:205 +0x97
github.com/lightningnetwork/lnd/htlcswitch.New(0xc0001bd8c0, 0x130fe80, 0xc000440078, 0xc0004c2290, 0xc0001ee720, 0x13139c0, 0x1b9f200, 0xc0004c22a0, 0xc000520f30, 0x131e5a0, ...)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/htlcswitch/switch.go:288 +0xd2
main.newServer(0xc000064ce0, 0x1, 0x1, 0xc0001ee720, 0xc0000b7ad0, 0xc0001bd8c0, 0x0, 0x0, 0x0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/server.go:329 +0xe9e
main.lndMain(0x0, 0x0)
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/lnd.go:308 +0xb74
main.main()
    /home/ubuntuuser/gocode/src/github.com/lightningnetwork/lnd/lnd.go:418 +0x26

```

Any help would be greatly appreciated.
