### ISSUE TITLE
Panic: invalid page type: 3773: 10

### ISSUE THREAD

**Issue by Husogutr** [lightningnetwork/lnd#2626]
### Background
I can not properly start `lnd`. Once I launched it I had never shut it down until now. So next proper launch will be the second one. Also had never done a single succesful payment because of issue #2596. I'd be happy to pull that issue forward, but I can't call `decodepayreq` to see if `route_hints` filed is blank - my `lnd` simply won't start.

### Environment
- OS: Raspbian Stretch Lite November 2018
- lnd: v0.5.2-beta commit=v0.5.2-beta-rc6
- bitcoind: 0.17.1

### Steps to reproduce
`lnd` output right after succesful wallet unlocking:
```
2019-02-10 12:32:42.959 [INF] LNWL: Opened wallet
2019-02-10 12:32:43.943 [INF] LTND: Primary chain is set to: bitcoin
2019-02-10 12:32:44.080 [INF] LTND: Initializing bitcoind backed fee estimator
2019-02-10 12:32:44.080 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:28332
2019-02-10 12:32:44.080 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:28333
2019-02-10 12:32:56.716 [INF] LNWL: The wallet has been unlocked without a time limit
2019-02-10 12:32:56.728 [INF] LTND: LightningWallet opened
2019-02-10 12:32:56.839 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=false)! NOTE: Ensure the backend node is proxying over Tor as well
2019-02-10 12:32:56.955 [INF] HSWC: Restoring in-memory circuit state from disk
2019-02-10 12:32:57.032 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
2019-02-10 12:32:57.169 [INF] HSWC: Trimming open circuits for chan_id=561826:912:0, start_htlc_id=0
2019-02-10 12:32:57.170 [INF] HSWC: Trimming open circuits for chan_id=561859:2489:1, start_htlc_id=0
2019-02-10 12:32:57.287 [INF] LTND: Shutdown complete
panic: invalid page type: 3773: 10

goroutine 1 [running]:
github.com/coreos/bbolt.(*Cursor).search(0x1ee3578, 0x1ee35f0, 0x29, 0x29, 0xebd, 0x0)
	/Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v0.0.0-20180223184059-7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/cursor.go:250 +0x2c4
github.com/coreos/bbolt.(*Cursor).searchPage(0x1ee3578, 0x1ee35f0, 0x29, 0x29, 0x63a75000)
	/Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v0.0.0-20180223184059-7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/cursor.go:308 +0x114
github.com/coreos/bbolt.(*Cursor).search(0x1ee3578, 0x1ee35f0, 0x29, 0x29, 0xed6, 0x0)
	/Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v0.0.0-20180223184059-7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/cursor.go:265 +0x130
github.com/coreos/bbolt.(*Cursor).seek(0x1ee3578, 0x1ee35f0, 0x29, 0x29, 0x0, 0x0, 0xad, 0xad, 0x0, 0xad, ...)
	/Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v0.0.0-20180223184059-7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/cursor.go:159 +0xa0
github.com/coreos/bbolt.(*Bucket).Delete(0x1c56620, 0x1ee35f0, 0x29, 0x29, 0x63d39171, 0xad)
	/Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v0.0.0-20180223184059-7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/bucket.go:319 +0xb4
github.com/lightningnetwork/lnd/channeldb.putLightningNode(0x1c564c0, 0x1c56580, 0x1c56620, 0x1f02300, 0x1c56620, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:2899 +0x724
github.com/lightningnetwork/lnd/channeldb.addLightningNode(0x1f02380, 0x1f02300, 0x6, 0x6)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:381 +0x10c
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).SetSourceNode.func1(0x1f02380, 0xb4d4ac, 0x1f02380)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:345 +0xd8
github.com/coreos/bbolt.(*DB).Update(0x1cf0b40, 0x1ee36ec, 0x0, 0x0)
	/Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v0.0.0-20180223184059-7ee3ded59d4835e10f3e7d0f7603c42aa5e83820/db.go:670 +0x84
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).SetSourceNode(0x1c7b2c8, 0x1f02300, 0x47, 0x24de7f3)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:329 +0x5c
main.newServer(0x1da77a8, 0x1, 0x1, 0x1c77640, 0x1e52000, 0x1db46e0, 0x0, 0x0, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/server.go:510 +0x1400
main.lndMain(0x0, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:307 +0x960
main.main()
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnd.go:449 +0x14
```

### Expected behaviour
```
[INF] LTND: LightningWallet opened
[INF] SRVR: Proxying all network traffic via Tor (stream_isola$
[INF] HSWC: Restoring in-memory circuit state from disk
[INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
[INF] HSWC: Trimming open circuits for chan_id=561826:912:0, s$
[INF] HSWC: Trimming open circuits for chan_id=561859:2489:1, $
[INF] RPCS: RPC server listening on 127.0.0.1:10009
[INF] RPCS: gRPC proxy started at 127.0.0.1:8080
```
and so on.

### Actual behaviour
```
[INF] LTND: LightningWallet opened
[INF] SRVR: Proxying all network traffic via Tor (stream_isola$
[INF] HSWC: Restoring in-memory circuit state from disk
[INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
[INF] HSWC: Trimming open circuits for chan_id=561826:912:0, s$
[INF] HSWC: Trimming open circuits for chan_id=561859:2489:1, $
[INF] LTND: Shutdown complete
```

**Comment by Roasbeef** [comment]
Looks like rasp pi disk corruption.
