### ISSUE TITLE
LND nodes seems to crash on this logs:

### ISSUE THREAD

**Issue by vamp111** [lightningnetwork/lnd#2874]
screen stalled on: ?/5****** Lightning Filtering Blockchain

lnd 0.5.2-beta  and bitcoin 0.17.0.1 on a RaspiBlitz  1.1

After normal restart with command: `sudo reboot` stalls on the above mentioned screen

can access via SSH, but not with RTL

log displays the following LND errors: 

Apr 02 11:50:11 FreeTradeBulgaria lnd[12459]: /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190123033236-ba03278a64bc/wallet/wallet.go:186 +0x124
Apr 02 11:50:11 FreeTradeBulgaria lnd[12459]: goroutine 115 [IO wait]:
Apr 02 11:50:11 FreeTradeBulgaria systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

here the complete log file:

*** RASPIBLITZ LOGS ***
blitzversion: 1.1
chainnetwork: bitcoin / main
11:50:51 up 2:29, 2 users, load average: 0.74, 0.90, 0.87

*** CHAINNETWORK SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2019-04-02 09:22:44 BST; 2h 28min ago
Process: 834 ExecStart=/usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitcoin/.bitcoin/bitcoind.pid (code=exited, status=0/SUCCESS)
Main PID: 849 (bitcoind)
CGroup: /system.slice/bitcoind.service
└─849 /usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/home/bitcoin/.bitcoi…id

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

*** LAST 5 ERROR LOGS ***
-- No entries --

*** LAST 20 INFO LOGS ***
2019-04-02T08:52:18Z Imported mempool transactions from disk: 15003 succeeded, 3981 failed, 0 expired, 2 already there
2019-04-02T08:55:37Z UpdateTip: new best=000000000000000000008ecdc3d8a551c22ea5c7fe0c342d7fac187da895a9ff height=569857 version=0x20c00000 log2_work=90.502789 tx=397720030 date='2019-04-02T08:55:22Z' progress=1.000000 cache=11.0MiB(96939txo) warning='41 of last 100 blocks have unexpected version'
2019-04-02T09:13:22Z UpdateTip: new best=00000000000000000017520034dcc4081bb9d461ae451de21f2b872ae8348bee height=569858 version=0x20000000 log2_work=90.502811 tx=397722520 date='2019-04-02T09:13:11Z' progress=1.000000 cache=12.6MiB(108395txo) warning='41 of last 100 blocks have unexpected version'
2019-04-02T09:28:03Z UpdateTip: new best=00000000000000000006ea1899f07aee21f600172a928f1fab8a75a43f712d1a height=569859 version=0x20000000 log2_work=90.502834 tx=397724786 date='2019-04-02T09:27:32Z' progress=1.000000 cache=14.0MiB(121839txo) warning='41 of last 100 blocks have unexpected version'
2019-04-02T09:31:51Z Pre-allocating up to position 0x200000 in rev01582.dat
2019-04-02T09:31:51Z UpdateTip: new best=000000000000000000210f90433e99bb11a5af2516ad9281e67a71c5925cd4d7 height=569860 version=0x20400000 log2_work=90.502856 tx=397727605 date='2019-04-02T09:31:28Z' progress=1.000000 cache=14.9MiB(130189txo) warning='41 of last 100 blocks have unexpected version'
2019-04-02T09:32:19Z UpdateTip: new best=000000000000000000147cd80895cd94e5df7e9222cfcec17efab148a580acff height=569861 version=0x20000000 log2_work=90.502879 tx=397727606 date='2019-04-02T09:31:47Z' progress=1.000000 cache=14.9MiB(130319txo) warning='41 of last 100 blocks have unexpected version'
2019-04-02T09:33:23Z UpdateTip: new best=00000000000000000018c7b1eb50ff05e28f5ee2118e5b5838ac815a306893de height=569862 version=0x20400000 log2_work=90.502901 tx=397728418 date='2019-04-02T09:33:02Z' progress=1.000000 cache=15.0MiB(131171txo) warning='42 of last 100 blocks have unexpected version'
2019-04-02T09:36:29Z UpdateTip: new best=0000000000000000000776e21afb2632735f1453c4e495400d747d495eef1192 height=569863 version=0x20800000 log2_work=90.502924 tx=397730945 date='2019-04-02T09:35:56Z' progress=1.000000 cache=15.5MiB(135491txo) warning='43 of last 100 blocks have unexpected version'
2019-04-02T10:08:37Z Potential stale tip detected, will try using extra outbound peer (last tip update: 1928 seconds ago)
2019-04-02T10:08:37Z New outbound peer connected: version: 70015, blocks=569863, peer=18
2019-04-02T10:09:06Z New outbound peer connected: version: 70015, blocks=569863, peer=19
2019-04-02T10:10:25Z UpdateTip: new best=00000000000000000003aca514677299b999e8af5d23a3900f666a82c761a8b6 height=569864 version=0x20000000 log2_work=90.502946 tx=397733687 date='2019-04-02T10:09:38Z' progress=1.000000 cache=17.3MiB(151909txo) warning='43 of last 100 blocks have unexpected version'
2019-04-02T10:16:43Z UpdateTip: new best=000000000000000000060da071c540140a799ae8882011ab264275158e6863fc height=569865 version=0x20000000 log2_work=90.502969 tx=397736434 date='2019-04-02T10:16:45Z' progress=1.000000 cache=18.1MiB(160085txo) warning='43 of last 100 blocks have unexpected version'
2019-04-02T10:30:28Z UpdateTip: new best=000000000000000000232172c1c149101269e5579d66024c0980f51fc84f98d3 height=569866 version=0x20000000 log2_work=90.502992 tx=397738854 date='2019-04-02T10:30:13Z' progress=1.000000 cache=19.1MiB(168908txo) warning='43 of last 100 blocks have unexpected version'
2019-04-02T10:32:28Z UpdateTip: new best=000000000000000000230bbf6cdf5920eebf0a607aa06216b95d1a7f8b70f1e8 height=569867 version=0x20000000 log2_work=90.503014 tx=397741768 date='2019-04-02T10:31:58Z' progress=1.000000 cache=19.6MiB(173867txo) warning='43 of last 100 blocks have unexpected version'
2019-04-02T10:32:30Z Pre-allocating up to position 0x300000 in rev01582.dat
2019-04-02T10:32:31Z UpdateTip: new best=00000000000000000018eda4c4f51c471b3232fd842d60106897a59829ce5c48 height=569868 version=0x20c00000 log2_work=90.503037 tx=397744157 date='2019-04-02T10:32:26Z' progress=1.000000 cache=19.9MiB(176585txo) warning='43 of last 100 blocks have unexpected version'
2019-04-02T10:35:33Z Pre-allocating up to position 0x2000000 in blk01582.dat
2019-04-02T10:35:34Z UpdateTip: new best=0000000000000000002a9eaa22dbfd5a8bbe26ebf324ee93e2823537bf5f56c4 height=569869 version=0x20c00000 log2_work=90.503059 tx=397746876 date='2019-04-02T10:35:01Z' progress=1.000000 cache=20.3MiB(180054txo) warning='44 of last 100 blocks have unexpected version'

*** LND SYSTEMD STATUS ***
● lnd.service - LND Lightning Daemon
Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Tue 2019-04-02 11:50:11 BST; 40s ago
**Process: 12459 ExecStart=/usr/local/bin/lnd --externalip=${publicIP} (code=exited, status=2)
Main PID: 12459 (code=exited, status=2)

Apr 02 11:50:11 FreeTradeBulgaria systemd[1]: lnd.service: Unit entered failed state.
Apr 02 11:50:11 FreeTradeBulgaria systemd[1]: lnd.service: Failed with result 'exit-code'.**

*** LAST 5 LND ERROR LOGS ***
-- Logs begin at Tue 2019-04-02 11:19:32 BST, end at Tue 2019-04-02 11:50:51 BST. --
Apr 02 11:50:11 FreeTradeBulgaria lnd[12459]: /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190123033236-ba03278a64bc/wallet/wallet.go:186 +0x124
Apr 02 11:50:11 FreeTradeBulgaria lnd[12459]: goroutine 115 [IO wait]:
Apr 02 11:50:11 FreeTradeBulgaria systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 02 11:50:11 FreeTradeBulgaria systemd[1]: lnd.service: Unit entered failed state.
Apr 02 11:50:11 FreeTradeBulgaria systemd[1]: lnd.service: Failed with result 'exit-code'.

*** LAST 20 LND INFO LOGS ***
2019-04-02 11:50:10.005 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=620552268222758912, mflags=00000001, cflags=00000001, update_time=2019-04-02 10:55:10 +0100 BST) from 35.238.153.25:9735
2019-04-02 11:50:10.005 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=596936957446717440, mflags=00000001, cflags=00000000, update_time=2019-04-02 10:54:10 +0100 BST) from 207.180.244.165:9735
2019-04-02 11:50:10.005 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=623015174282346496) from 18.221.23.28:9735
2019-04-02 11:50:10.006 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=613574767413493760, mflags=00000001, cflags=00000011, update_time=2019-04-02 10:55:40 +0100 BST) from 104.248.84.249:9735
2019-04-02 11:50:10.006 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612467559116636161, mflags=00000001, cflags=00000000, update_time=2019-04-02 10:58:19 +0100 BST) from 138.68.14.104:9735
2019-04-02 11:50:10.006 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=623577024758808576, mflags=00000001, cflags=00000011, update_time=2019-04-02 10:55:31 +0100 BST) from 195.95.225.243:9735
2019-04-02 11:50:10.006 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=622736997815549952) from 54.37.22.216:9735
2019-04-02 11:50:10.006 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=602040890391396352, mflags=00000001, cflags=00000001, update_time=2019-04-02 10:59:26 +0100 BST) from 178.128.202.182:9735
2019-04-02 11:50:10.007 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=608498322164023296) from 213.174.156.70:9735
2019-04-02 11:50:10.007 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=607885894227263489) from 138.201.60.38:9735
2019-04-02 11:50:10.007 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=620496193137344512, mflags=00000001, cflags=00000001, update_time=2019-04-02 10:53:09 +0100 BST) from 46.229.165.141:9735
2019-04-02 11:50:10.007 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=626408267199610881) from 74.108.13.152:9735
2019-04-02 11:50:10.007 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=623531944745566208, mflags=00000001, cflags=00000001, update_time=2019-04-02 10:53:59 +0100 BST) from 213.91.178.177:9735
2019-04-02 11:50:10.008 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=621347215038152704) from 13.58.72.252:9735
2019-04-02 11:50:10.008 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=611811150733705216) from 35.238.153.25:9735
2019-04-02 11:50:10.008 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=596936957446717440, mflags=00000001, cflags=00000011, update_time=2019-04-02 10:41:50 +0100 BST) from 207.180.244.165:9735
2019-04-02 11:50:10.008 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=623015174282346496, mflags=00000001, cflags=00000010, update_time=2019-04-02 11:15:48 +0100 BST) from 18.221.23.28:9735
2019-04-02 11:50:10.008 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=612467559116636161, mflags=00000001, cflags=00000001, update_time=2019-04-02 11:11:48 +0100 BST) from 138.68.14.104:9735
2019-04-02 11:50:10.008 [DBG] PEER: Received ChannelAnnouncement(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=605545034027040768) from 104.248.84.249:9735
2019-04-02 11:50:10.009 [DBG] PEER: Received ChannelUpdate(chain_hash=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, short_chan_id=622736997815549952, mflags=00000000, cflags=00000010, update_time=2019-04-02 11:12:08 +0100 BST) from 54.37.22.216:9735

*** LAST 20 RTL LOGS ***
-- No entries --

Please if someone had similar issues let me know, its 2nd day like this, I dont know what to do to get it fixed!

**Comment by Roasbeef** [comment]
Looks like disk corruption maybe? Unclean shutdown issues were fixed by #2842.

**Comment by vamp111** [comment]
@Roasbeef  sometimes I manage to reach the normal screen, full connection to the bitcoinid but 0 to peers in LN,  any suggestions what I can do?

**Comment by Roasbeef** [comment]
@vamp111 if it's able to start up fully, and you're confident its on the latest state, then you can close the channels.
