### ISSUE TITLE
unknown service lnrpc.WalletUnlocker when doing gRPC calls

### ISSUE THREAD

**Issue by reynico** [lightningnetwork/lnd#2875]
### Background
Trying to generate a seed and/or unlock the wallet using gRPC with the following code:
```
import codecs
import grpc
import os
import rpc_pb2 as ln
import rpc_pb2_grpc as lnrpc
with open(os.path.expanduser('~/.lnd/admin.macaroon'), 'rb') as macaroon:
    macaroon_bytes = macaroon.read()
    macaroon = codecs.encode(macaroon_bytes, 'hex')

with open(os.path.expanduser('~/.lnd/tls.cert'), 'rb') as tls_cert:
    cert = tls_cert.read()

os.environ['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA'


def metadata_callback(context, callback):
    callback([('macaroon', macaroon)], None)


ssl_creds = grpc.ssl_channel_credentials(cert)
auth_creds = grpc.metadata_call_credentials(metadata_callback)
combined_creds = grpc.composite_channel_credentials(ssl_creds, auth_creds)
channel = grpc.secure_channel('localhost:10009', combined_creds)
stub = lnrpc.WalletUnlockerStub(channel)
request = ln.GenSeedRequest()
response = stub.GenSeed(request)
```
Results on:
```
>>> response = stub.GenSeed(request)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/lndrpc/lndrpc/local/lib/python2.7/site-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ubuntu/lndrpc/lndrpc/local/lib/python2.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "unknown service lnrpc.WalletUnlocker"
        debug_error_string = "{"created":"@1554227345.648404860","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"unknown service lnrpc.WalletUnlocker","grpc_status":12}"
>
```
But some other call works as expected:
```
>>> stub = lnrpc.LightningStub(channel)
>>> stub.GetInfo(ln.GetInfoRequest())
identity_pubkey: ""
alias: ""
num_peers: 1
block_height: 569911
block_hash: ""
synced_to_chain: true
best_header_timestamp: 1554226178
version: "0.5.2-99-beta commit=queue/v1.0.1-196-g8087ea4c4c12c762363b00e3feddc7c3d963aeb6"
chains {
  chain: "bitcoin"
  network: "mainnet"
}
```
### Your environment
* LND version: 0.5.2-99-beta commit=queue/v1.0.1-196-g8087ea4c4c12c762363b00e3feddc7c3d963aeb6
* OS: Linux ip-10-2-11-69 4.15.0-1034-aws #36-Ubuntu SMP Tue Mar 5 23:17:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Python: Python 2.7.15rc1

### Steps to reproduce
Followed this guide: https://dev.lightning.community/guides/python-grpc/
Took API call reference from: https://api.lightning.community/#genseed

**Comment by reynico** [comment]
As a side note, `lncli unlock` works perfect.

**Comment by wpaulino** [comment]
The `WalletUnlocker` service is only available until you unlock the wallet. After that point, you'll only be able to interact with the `Lightning` service.

**Comment by reynico** [comment]
Great, thanks!
