### ISSUE TITLE
SIGSEGV during startup and chain sync (lnd 0.3 alpha)

### ISSUE THREAD

**Issue by aantonop** [lightningnetwork/lnd#297]
I'm getting a segmentation fault soon after startup, failing to sync chain in neutrino mode:
```
2017-08-29 17:03:28.893 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2017-08-29 17:03:28.893 [INF] LTND: Waiting for chain backend to finish sync, start_height=1180427
2017-08-29 17:03:28.893 [INF] RPCS: gRPC proxy started at localhost:8080
2017-08-29 17:03:35.648 [INF] CMGR: DNS discovery failed on seed testnet-seed.bitcoin.schildbach.de: lookup testnet-seed.bitcoin.schildbach.de: Temporary failure in name resolution
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x86f086]

goroutine 31 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).current(0xc4204d4b60, 0xc4200115f4)
	/home/aantonop/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:713 +0x146
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).handleInvMsg(0xc4204d4b60, 0xc420016ac0)
	/home/aantonop/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:762 +0x773
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0xc4204d4b60)
	/home/aantonop/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:331 +0x3ae
created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).Start
	/home/aantonop/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:207 +0x114
```

**Comment by aakselrod** [comment]
This panic should go away with the newest code; though this may not fully fix the issue. Can you please update and try again? Thanks!

**Comment by Roasbeef** [comment]
Closing due to ref'd commit.

**Comment by griffero** [comment]
I'm getting the same error here while unlocking the wallet. The only difference is that I'm not syncing chain in neutrino mode.

```
2017-12-15 13:54:06.087 [INF] HSWC: HTLC manager for ChannelPoint(a26a76be46cbe3f1fbfa11aaaaa8f256eedd6cf94135b34266b52ba3364e9abb:0) started, bandwidth=996380000 mSAT
2017-12-15 13:54:06.087 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(a26a76be46cbe3f1fbfa11aaaaa8f256eedd6cf94135b34266b52ba3364e9abb:0)
2017-12-15 13:54:06.096 [INF] SRVR: Established connection to: 79.214.223.73:9735
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1803e66]

goroutine 328 [running]:
main.(*peer).logWireMessage(0xc4201ec840, 0x20e1a80, 0xc420a0e000, 0x20e1a01)
	/Users/cristobal/gocode/src/github.com/lightningnetwork/lnd/peer.go:930 +0x8d6
main.(*peer).readNextMessage(0xc4201ec840, 0x0, 0xc42027bce8, 0xc42027be78, 0xc42027bce8)
	/Users/cristobal/gocode/src/github.com/lightningnetwork/lnd/peer.go:457 +0x167
main.(*peer).readHandler(0xc4201ec840)
	/Users/cristobal/gocode/src/github.com/lightningnetwork/lnd/peer.go:656 +0x1b9
created by main.(*peer).Start
	/Users/cristobal/gocode/src/github.com/lightningnetwork/lnd/peer.go:286 +0x847
```

**Comment by halseth** [comment]
Hey, ensure you are running with latest update, should be fixed by https://github.com/lightningnetwork/lnd/commit/ce6dee6ee4c3d4b161db65058c8afa4f541bae1f
