### ISSUE TITLE
Security handshake failed odroid

### ISSUE THREAD

**Issue by elvisLutta** [lightningnetwork/lnd#3215]
### Background

Hey, I'm trying to make a simnet lightning node running on an odroid to connect to a raspberry pi but i keep getting the error security handshake failed.

### Environment

* version of `lnd`
lncli version 0.6.1-beta commit=v0.6.1-beta-21-g863bf2f91b245afd58c8edc078a171a55e48f931

* which operating system
Linux odroid 4.14.5-92 #1 SMP PREEMPT Mon Dec 11 15:48:15 UTC 2017 armv7l armv7l armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
btcd version 0.12.0-beta

### Steps to reproduce

Heres the code:
```
import threading
import time

import grpc
import os
import rpc_pb2 as ln
import rpc_pb2_grpc as lnrpc
import codecs
import pyqrcode
import RPi.GPIO as GPIO

from guizero import App, Text, TextBox, PushButton, Picture

def generate_bill():
    response = stub.WalletBalance(ln.WalletBalanceRequest())
    request = ln.Invoice(memo="App Invoice", value=100)
    response = stub.AddInvoice(request)
    big_code = pyqrcode.create(response.payment_request)
    big_code.png('qr_code.png', scale=6, module_color=[0, 0, 0, 128], background=[0xff, 0xff, 0xff])
    my_qr.image="qr_code.png"
    my_qr.visible=True
    myhash = response.r_hash
    my_hashtext.value = codecs.encode(myhash, 'hex').decode('ascii')
    pay_counter.value=1
    pay_counter.repeat(1000, pay_countdown)

def relay_on():
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(pin, GPIO.OUT)
    GPIO.output(pin, GPIO.HIGH)

def relay_off():
    GPIO.output(pin, GPIO.LOW)
    GPIO.cleanup()
    
def pay_countdown():
    pay_counter.value = int(pay_counter.value) + 1
    invoice = stub.LookupInvoice(ln.PaymentHash(r_hash_str=my_hashtext.value))
    if invoice.settled:
        pay_counter.cancel(pay_countdown)
        pay_counter.after(10,paid)
    if int(pay_counter.value) > 3000:
        pay_counter.value = 1
        pay_counter.cancel(pay_countdown)
        pay_counter.after(10,generate_bill)
        
def paid():
    pay_counter.visible = False
    my_qr.image="complete.jpg"
    my_qr.visible=True
    pay_counter.after(2000,start_use)
        
def start_use():
    use_counter.value=20
    use_counter.visible=True
    my_qr.visible = False
    relay_on()
    welcome_message.value = "Use for this amount of time:"
    use_counter.repeat(1000, use_countdown)
    
def use_countdown():
    use_counter.value = int(use_counter.value) - 1
    if int(use_counter.value) <1:
        use_counter.cancel(use_countdown)
        use_counter.visible = False
        welcome_message.value = "Pay to use"
        relay_off()
        use_counter.after(10,generate_bill)
        
app = App(bg="#13084c", title="App", width=500, height=500)
welcome_message = Text(app, text="Pay to use", size=20, font="Times New Roman", color="blue")
pay_counter =Text(app, text="1", size=10, font="Times New Roman", color="blue", visible=False )
use_counter =Text(app, text="1", size=30, font="Times New Roman", color="blue", visible=False)
my_qr = Picture(app, image="complete.jpg", width=250,height=250, visible=False)
my_hashtext = Text(app, text="hash", size=10, font="Times New Roman", color="blue", visible=False)
with open(os.path.expanduser('~/App/lnd/admin.macaroon'), 'rb') as f:
    macaroon_bytes = f.read()
    macaroon = codecs.encode(macaroon_bytes, 'hex')
pin=40   
def metadata_callback(context, callback):
    callback([('macaroon', macaroon)], None)
    
os.environ["GRPC_SSL_CIPHER_SUITES"] = 'HIGH+ECDSA'

cert = open(os.path.expanduser('~/App/lnd/tls.cert'), 'rb').read()
cert_creds = grpc.ssl_channel_credentials(cert)
auth_creds = grpc.metadata_call_credentials(metadata_callback)
combined_creds = grpc.composite_channel_credentials(cert_creds, auth_creds)

channel = grpc.secure_channel('<Your IP address>:<port>', combined_creds)

stub = lnrpc.LightningStub(channel)
generate_bill()
app.tk.attributes("-fullscreen",True)
app.display()
```

### Expected behaviour

The gui should display a qr code for payment and trigger an action on the raspberry pi.

### Actual behaviour

Instead the error` Security handshake failed` occurs. I'm not sure what I'm doing wrong because the `admin.macaroon` and `tls.cert` files in use should be the correct ones.

here's the error below.
```
D0618 16:33:12.245440478    1335 ev_posix.cc:174]            Using polling engine: epollex
D0618 16:33:12.245832821    1335 dns_resolver_ares.cc:480]   Using ares dns resolver
E0618 16:33:12.245934279    1335 trace.cc:65]                Unknown trace var: 'client_channel'
I0618 16:33:12.251783167    1335 pick_first.cc:164]          Pick First 0x27e4298 created.
I0618 16:33:12.251906448    1335 pick_first.cc:249]          Pick First 0x27e4298 received update with 1 addresses
I0618 16:33:12.252002541    1335 subchannel_list.h:494]      [pick_first 0x27e4298] Creating subchannel list 0x27e44c8 for 1 subchannels
I0618 16:33:12.253832119    1335 subchannel_list.h:545]      [pick_first 0x27e4298] subchannel list 0x27e44c8 index 0: Created subchannel 0x27e6990 for address uri ipv4:192.168.0.28:18555
I0618 16:33:12.253908942    1335 subchannel_list.h:327]      [pick_first 0x27e4298] subchannel list 0x27e44c8 index 0 of 1 (subchannel 0x27e6990): starting watch: requesting connectivity change notification (from IDLE)
I0618 16:33:12.254405659    1335 subchannel_list.h:441]      [pick_first 0x27e4298] subchannel list 0x27e44c8 index 0 of 1 (subchannel 0x27e6990): connectivity changed: state=CONNECTING, error="No Error", shutting_down=0
I0618 16:33:12.254485502    1335 subchannel_list.h:349]      [pick_first 0x27e4298] subchannel list 0x27e44c8 index 0 of 1 (subchannel 0x27e6990): renewing watch: requesting connectivity change notification (from CONNECTING)
D0618 16:33:12.259030853    1335 tcp_posix.cc:1258]          cannot set inq fd=12 errno=92
D0618 16:33:12.262443290    1335 security_handshaker.cc:176] Security handshake failed: {"created":"@1560864792.262291832","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1560864792.262272301","description":"Connection reset by peer","errno":104,"fd":12,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":495,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg","target_address":"ipv4:192.168.0.28:18555"}]}
I0618 16:33:12.262698602    1335 subchannel.cc:926]          Connect failed: {"created":"@1560864792.262291832","description":"Handshake read failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1560864792.262272301","description":"Connection reset by peer","errno":104,"fd":12,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":495,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg","target_address":"ipv4:192.168.0.28:18555"}]}
I0618 16:33:12.262808914    1335 subchannel_list.h:441]      [pick_first 0x27e4298] subchannel list 0x27e44c8 index 0 of 1 (subchannel 0x27e6990): connectivity changed: state=TRANSIENT_FAILURE, error="No Error", shutting_down=0
I0618 16:33:12.262868185    1335 subchannel_list.h:369]      [pick_first 0x27e4298] subchannel list 0x27e44c8 index 0 of 1 (subchannel 0x27e6990): stopping connectivity watch
I0618 16:33:12.262964695    1335 subchannel_list.h:327]      [pick_first 0x27e4298] subchannel list 0x27e44c8 index 0 of 1 (subchannel 0x27e6990): starting watch: requesting connectivity change notification (from TRANSIENT_FAILURE)
I0618 16:33:12.263024382    1335 subchannel.cc:863]          Subchannel 0x27e6990: Retry in 989 milliseconds
Traceback (most recent call last):
  File "/home/pi/App/lnd/hardware_control.py", line 108, in <module>
    generate_bill()
  File "/home/pi/App/lnd/hardware_control.py", line 28, in generate_bill
    response = stub.WalletBalance(ln.WalletBalanceRequest())
  File "/home/pi/App/lnd/lib/python3.5/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/pi/App/lnd/lib/python3.5/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@15612364792.263039018","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3381,"referenced_errors":[{"created":"@15612364792.263039018","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":453,"grpc_status":14}]}"
>
```

**Comment by wpaulino** [comment]
Did you move the TLS and macaroon files from their expected path within the lnd directory? If so, lnd will think the files do not exist and will generate new ones.

**Comment by elvisLutta** [comment]
The macaroon file is in a directory in the gopath, the tls file is still in the .lnd directory.

**Comment by Roasbeef** [comment]
Double check that the other side is actually listening, the main error here is: 
> Connection reset by peer","errno":104

**Comment by halseth** [comment]
Closing per https://github.com/lightningnetwork/lnd/issues/3215#issuecomment-504237885, please re-open if this is not the issue.
