### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alevchuk** [lightningnetwork/lnd#3409]
### Background

Started a new LND node and in the first 1 hour got a nil pointer dereference

### Your environment

* version of `lnd version 0.7.1-beta commit=v0.7.1-beta-91-g938516ec5ae4a19d865036a23bb2c3ba095a9d00` 938516ec5ae4a19d865036a23bb2c3ba095a9d00
* which operating system (`Linux x 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux` )
* version of `bitcoind --version Bitcoin Core Daemon version v0.18.0`
* Raspberry Pi 4 with 4 GB RAM

### Steps to reproduce

Start a new Bitoind, wait for the chain the sync, start new LND. Didn't add any funds yet.

### Expected behaviour

Should keep running.

### Actual behaviour

Crashed:
```
2019-08-15 21:08:31.449 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
2019-08-15 21:09:31.450 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory] [lseed.bitcoinstats.com ]]
2019-08-15 21:09:51.784 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2019-08-15 21:09:51.786 [ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61e9fc]

goroutine 4583 [running]:
github.com/lightningnetwork/lnd/discovery.(*GossipSyncer).ResetSyncedSignal(0x0, 0x0)
        /home/lightning/gocode/src/github.com/lightningnetwork/lnd/discovery/syncer.go:1162 +0x1c
github.com/lightningnetwork/lnd/discovery.(*SyncManager).syncerHandler(0x3892120)
        /home/lightning/gocode/src/github.com/lightningnetwork/lnd/discovery/sync_manager.go:398 +0x260
created by github.com/lightningnetwork/lnd/discovery.(*SyncManager).Start.func1
        /home/lightning/gocode/src/github.com/lightningnetwork/lnd/discovery/sync_manager.go:166 +0x4c
```

**Comment by wpaulino** [comment]
Fixed by https://github.com/lightningnetwork/lnd/pull/3400.
