### ISSUE TITLE
Unpretty error when restorechanbackup fails

### ISSUE THREAD

**Issue by Sjors** [lightningnetwork/lnd#3452]
### Background

When using `lncli restorechanbackup channel.backup` on an invalid backup (either not matching the seed, or the wrong network?) `lncli` throws an unreadable error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x17072d0]

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc00020f768)
	/Users/sjors/go/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:472 +0x287
panic(0x17f6c80, 0x2133690)
	/usr/local/Cellar/go/1.12.9/libexec/src/runtime/panic.go:522 +0x1b5
main.restoreChanBackup(0xc000288140, 0x0, 0x0)
	/Users/sjors/dev/lnd/cmd/lncli/commands.go:4008 +0x110
main.actionDecorator.func1(0xc000288140, 0x0, 0x0)
	/Users/sjors/dev/lnd/cmd/lncli/commands.go:70 +0x33
reflect.Value.call(0x17b1760, 0xc0000d36f0, 0x13, 0x18f86bc, 0x4, 0xc00020f708, 0x1, 0x1, 0xc0000e6900, 0x1013dc3, ...)
	/usr/local/Cellar/go/1.12.9/libexec/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x17b1760, 0xc0000d36f0, 0x13, 0xc00020f708, 0x1, 0x1, 0xc00053a0d0, 0xc00053a108, 0x140)
	/usr/local/Cellar/go/1.12.9/libexec/src/reflect/value.go:308 +0xa4
github.com/urfave/cli.HandleAction(0x17b1760, 0xc0000d36f0, 0xc000288140, 0x0, 0x0)
	/Users/sjors/go/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:481 +0x1ff
github.com/urfave/cli.Command.Run(0x1903e73, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1927fd2, 0x41, 0x0, ...)
	/Users/sjors/go/pkg/mod/github.com/urfave/cli@v1.18.0/command.go:186 +0x8d1
github.com/urfave/cli.(*App).Run(0xc000562300, 0xc0000f6000, 0x3, 0x3, 0x0, 0x0)
	/Users/sjors/go/pkg/mod/github.com/urfave/cli@v1.18.0/app.go:235 +0x601
main.main()
	/Users/sjors/dev/lnd/cmd/lncli/main.go:311 +0x11c6
```

### Your environment

* lnd master @ 81cb3cb739ebda96620cd15cac8f1fd1b83a4d35
* macOS 10.14
* bitcoind v0.18.1
* go 1.12.9 via homebrew 

### Expected behaviour

It should ideally say what's wrong.

**Comment by wpaulino** [comment]
@Sjors https://github.com/lightningnetwork/lnd/pull/3455 should address the issue.
