### ISSUE TITLE
ChannelArbitrator panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vwoo** [lightningnetwork/lnd#3549]
### Background

My lnd node will no longer startup. The last part of the logs say:

```
2019-09-27 16:56:25.684 [INF] CNCT: ChannelArbitrator(ae48c9acaae2fda06bee0581256af6f9f51f499e90103f5a449e390bdfab009a:0): starting state=StateDefault
2019-09-27 16:56:25.691 [INF] CNCT: ChannelArbitrator(de1b7caba631137e23c96990e9cf85f89cd67eba7a0d6b9fe40ebb284ccb8b34:1): starting state=StateDefault
2019-09-27 16:56:25.697 [INF] CNCT: ChannelArbitrator(ea119bebcec989757157287918387b510deb34d0c1446306be9a15dc537fd6ba:1): starting state=StateWaitingFullResolution
2019-09-27 16:56:25.701 [INF] CNCT: ChannelArbitrator(ea119bebcec989757157287918387b510deb34d0c1446306be9a15dc537fd6ba:1): still awaiting contract resolution
2019-09-27 16:56:25.701 [INF] RPCS: Stopping RPC Server
2019-09-27 16:56:25.701 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
2019-09-27 16:56:25.701 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2019-09-27 16:56:25.701 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
2019-09-27 16:56:25.701 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
2019-09-27 16:56:25.701 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
2019-09-27 16:56:25.701 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
2019-09-27 16:56:25.705 [INF] LTND: Shutdown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16bc19d]

goroutine 1 [running]:
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).Start(0xc001064000, 0x0, 0x0)
	/Users/vwoo/gocode/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:429 +0x66d
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).Start(0xc0000bf680, 0x0, 0x0)
	/Users/vwoo/gocode/src/github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:543 +0x12e2
github.com/lightningnetwork/lnd.(*server).Start.func1()
	/Users/vwoo/gocode/src/github.com/lightningnetwork/lnd/server.go:1238 +0x40b
sync.(*Once).doSlow(0xc000478008, 0xc0003375f0)
	/usr/local/Cellar/go/1.13/libexec/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/usr/local/Cellar/go/1.13/libexec/src/sync/once.go:57
github.com/lightningnetwork/lnd.(*server).Start(0xc000478000, 0x1e3f217, 0x2e)
	/Users/vwoo/gocode/src/github.com/lightningnetwork/lnd/server.go:1174 +0x95
github.com/lightningnetwork/lnd.Main(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/vwoo/gocode/src/github.com/lightningnetwork/lnd/lnd.go:620 +0x1b01
main.main()
	/Users/vwoo/gocode/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:14 +0x32
```

Full startup log is here: [log.txt](https://github.com/lightningnetwork/lnd/files/3664876/log.txt)

I had just recompiled lnd with the HEAD of master. I tried recompiling after checking out a commit from a couple of weeks ago to roughly where it last worked but it still won't startup.

### Your environment

* lnd @ git commit 7fcac54dffcc97964db22b0d8eaf31a9d751b76c, Sep 26, 2019
* macOS 10.14.6
* bitcoind v0.18.1
* bitcoin network: testnet

### Steps to reproduce

cd $GOPATH/src/github.com/lightningnetwork/lnd && git pull && make install tags="signrpc walletrpc chainrpc invoicesrpc routerrpc"
lnd
lncli unlock

**Comment by wpaulino** [comment]
You can use this diff for now in order to start your node:

```
diff --git a/contractcourt/channel_arbitrator.go b/contractcourt/channel_arbitrator.go
index 1789e775..dfa5097a 100644
--- a/contractcourt/channel_arbitrator.go
+++ b/contractcourt/channel_arbitrator.go
@@ -426,10 +426,12 @@ func (c *ChannelArbitrator) Start() error {
 		// receive a chain event from the chain watcher than the
 		// commitment has been confirmed on chain, and before we
 		// advance our state step, we call InsertConfirmedCommitSet.
-		confCommitSet := commitSet.HtlcSets[*commitSet.ConfCommitKey]
-		if err := c.relaunchResolvers(confCommitSet); err != nil {
-			c.cfg.BlockEpochs.Cancel()
-			return err
+		confCommitSet, ok := commitSet.HtlcSets[*commitSet.ConfCommitKey]
+		if ok {
+			if err := c.relaunchResolvers(confCommitSet); err != nil {
+				c.cfg.BlockEpochs.Cancel()
+				return err
+			}
 		}
 	}
 

```

**Comment by vwoo** [comment]
Thank you for looking into it. I applied your patch. Startup went a bit further but still crashed. 
Startup log is here: [log_after_patch.txt](https://github.com/lightningnetwork/lnd/files/3664987/log_after_patch.txt)

The last part of the startup log:

```
2019-09-27 18:53:11.957 [INF] CNCT: ChannelArbitrator(d3a8058852dd15fc904b3ac1b62054dfd04c6070e36eddf9f4a84934c49dd222:1): starting state=StateDefault
2019-09-27 18:53:11.961 [INF] CNCT: ChannelArbitrator(130d05315e02a7544dd0129d6098935e317164174c7a71e1f6cbad8b5dde0ecc:1): starting state=StateDefault
2019-09-27 18:53:11.965 [INF] CNCT: ChannelArbitrator(ea119bebcec989757157287918387b510deb34d0c1446306be9a15dc537fd6ba:1): starting state=StateWaitingFullResolution
2019-09-27 18:53:11.969 [INF] CNCT: ChannelArbitrator(ea119bebcec989757157287918387b510deb34d0c1446306be9a15dc537fd6ba:1): still awaiting contract resolution
2019-09-27 18:53:11.969 [INF] CNCT: ChannelArbitrator(ea119bebcec989757157287918387b510deb34d0c1446306be9a15dc537fd6ba:1): relaunching 1 contract resolvers
2019-09-27 18:53:11.969 [INF] NTFN: Cancelling epoch notification, epoch_id=84
2019-09-27 18:53:11.969 [INF] CNCT: Stopping ChainArbitrator
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=17
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=20
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=63
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=14
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=38
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=55
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=15
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=52
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=67
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=41
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=16
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=70
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=56
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=66
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=45
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=22
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=33
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=5
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=19
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=58
2019-09-27 18:53:11.970 [INF] NTFN: Cancelling epoch notification, epoch_id=79
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=71
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=7
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=44
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=73
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=36
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=34
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=72
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=9
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=35
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=13
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=83
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=75
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=82
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=28
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=46
2019-09-27 18:53:11.971 [INF] NTFN: Cancelling epoch notification, epoch_id=57
2019-09-27 18:53:11.972 [INF] NTFN: Cancelling epoch notification, epoch_id=21
2019-09-27 18:53:11.972 [INF] NTFN: Cancelling epoch notification, epoch_id=23
2019-09-27 18:53:11.972 [INF] NTFN: Cancelling epoch notification, epoch_id=69
2019-09-27 18:53:11.973 [INF] NTFN: Cancelling epoch notification, epoch_id=77
2019-09-27 18:53:11.973 [INF] NTFN: Cancelling epoch notification, epoch_id=54
2019-09-27 18:53:11.973 [INF] NTFN: Cancelling epoch notification, epoch_id=64
2019-09-27 18:53:11.974 [INF] NTFN: Cancelling epoch notification, epoch_id=74
2019-09-27 18:53:11.974 [ERR] LTND: Unable to start server: htlc for success resolver unavailable
2019-09-27 18:53:11.974 [INF] RPCS: Stopping RPC Server
2019-09-27 18:53:11.974 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
2019-09-27 18:53:11.974 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
2019-09-27 18:53:11.974 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
2019-09-27 18:53:11.975 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
2019-09-27 18:53:11.975 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2019-09-27 18:53:11.975 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
2019-09-27 18:53:11.978 [INF] LTND: Shutdown complete
Unable to start server: htlc for success resolver unavailable
```

**Comment by BitBargain** [comment]
Bump

(so that I get a notification when it's fixed - lnd is giving me the same error message and because of the vuln I don't want to downgrade).

I see vwoo is is already on the case, but if you need additional info or logs from me, let me know.

**Comment by Roasbeef** [comment]
@BitBargain @vwoo can y'all test #3576 to confirm it resolves the issue (allows your node to start), thanks!

**Comment by vwoo** [comment]
Compiled from #3576 and startup worked. Thank you!

**Comment by BitBargain** [comment]
It no longer crashes on startup. Thanks for your work!

**Comment by BitBargain** [comment]
Unfortunately it didn't last for long:

2019-10-04 13:02:46.394 [INF] NTFN: New spend subscription: spend_id=6, outpoint=4d77ac5c34193798075296830ed5089856ae6400814b941d0dba1c5ed9116e24:0, height_hint=596925
2019-10-04 13:02:46.394 [INF] UTXN: UTXO Nursery is now fully synced
2019-10-04 13:02:46.394 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] CNCT: Creating ChannelArbitrators for 8 closing channels
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] NTFN: New block epoch subscription
2019-10-04 13:02:46.483 [INF] CNCT: ChannelArbitrator(0df5e6a2a1617eaa4e9c2beebe8b1fb503007177889936457b9e15b0121cd301:1): starting state=StateWaitingFullResolution
2019-10-04 13:02:46.485 [INF] CNCT: ChannelArbitrator(0df5e6a2a1617eaa4e9c2beebe8b1fb503007177889936457b9e15b0121cd301:1): still awaiting contract resolution
2019-10-04 13:02:46.485 [INF] RPCS: Stopping RPC Server
2019-10-04 13:02:46.485 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
2019-10-04 13:02:46.488 [INF] LTND: Shutdown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xab5f9d]

goroutine 1 [running]:
github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).Start(0xc000288000, 0xc0001ecb40, 0xc001207108)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:429 +0x66d
github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).Start(0xc0001da900, 0x0, 0x0)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:543 +0x12e2
github.com/lightningnetwork/lnd.(*server).Start.func1()
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/server.go:1244 +0x40b
sync.(*Once).doSlow(0xc000262488, 0xc0002275f0)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/lightningnetwork/lnd.(*server).Start(0xc000262480, 0x12279e5, 0x2e)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/server.go:1180 +0x95
github.com/lightningnetwork/lnd.Main(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/lnd.go:619 +0x1b0d
main.main()
        /data/coin/ln/go/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:14 +0x32

Shall I submit a separate issue for this?

**Comment by Roasbeef** [comment]
@BitBargain the fix hasn't been merged yet, you need to check out the branch I referenced above in order to test out the fix.
