### ISSUE TITLE
LND prompt for password loop

### ISSUE THREAD

**Issue by thrasher-** [lightningnetwork/lnd#3550]
### Background

When prompted to unlock the LND wallet, it starts the channelarbitrator logic but then falls back to prompting to unlock the wallet again. This happens in a continuous loop.

### Your environment

* version of `lnd`: 0.7.1
* which operating system (`uname -a` on *Nix): Raspiblitz 1.3.0
* version of `btcd`, `bitcoind`, or other backend: bitcoind
* any other relevant environment details

### Steps to reproduce

Start LND, enter wallet PWD

### Expected behaviour

Unlocks wallet and can use LND functionality as per usual

### Actual behaviour

```

2019-09-28 04:18:28.696 [DBG] LNWL: Filtering block 596903 (000000000000000000002c805ebc4f584d7a420ab775915b8ceab5f9135fe659) with 1871 transactions
2019-09-28 04:18:29.137 [DBG] LNWL: Filtering block 596904 (00000000000000000011a02454b154f17c08c4ff8c9bf9701bad4ae3f176eb59) with 216 transactions
2019-09-28 04:18:29.407 [DBG] LNWL: Filtering block 596905 (000000000000000000076303ff0d91aff5422c62770f35a9a3119274f9bcb0bc) with 1515 transactions
2019-09-28 04:18:30.144 [DBG] LNWL: Filtering block 596906 (0000000000000000000df444c317a1d86146f7631a4b41c612c26d5d2a497754) with 2216 transactions
2019-09-28 04:18:31.052 [DBG] LNWL: Filtering block 596907 (00000000000000000004250adc3ae8700434e5cf7d45c7d5c5be967be978b315) with 1535 transactions
2019-09-28 04:18:31.810 [DBG] LNWL: Filtering block 596908 (00000000000000000008234a5f1772b043ab83daac13005926fd678970b922ed) with 2268 transactions
2019-09-28 04:18:33.069 [DBG] LNWL: Filtering block 596909 (000000000000000000096ed382c5285d50f4c99f33f2726442ce2ca1bd9f01b2) with 2976 transactions
2019-09-28 04:18:34.082 [DBG] LNWL: Filtering block 596910 (0000000000000000000b9eca9731101313d33e5bf60f2fdadcc13ced84a5de9c) with 2491 transactions
2019-09-28 04:18:34.894 [DBG] LNWL: Filtering block 596911 (000000000000000000100aca0092af7d3dcca149c4fcd5ac7d21d6669182aa76) with 2117 transactions
2019-09-28 04:18:35.417 [DBG] LNWL: Filtering block 596912 (0000000000000000000c3b793daa60166f06422103d1fa126867e54c6d7c2c55) with 278 transactions
2019-09-28 04:18:35.597 [DBG] LNWL: Filtering block 596913 (00000000000000000006ac1874da3a64c085be5bee2bf48059447728c1aa9013) with 765 transactions
2019-09-28 04:18:35.796 [DBG] LNWL: Filtering block 596914 (0000000000000000000321c16db06f19e9ae9c8473002e13cf8b10d379d9e6be) with 214 transactions
2019-09-28 04:18:35.887 [INF] LNWL: Catching up block hashes to height 596914, this might take a while
2019-09-28 04:18:35.922 [INF] LNWL: Done catching up block hashes
2019-09-28 04:18:35.922 [INF] LNWL: Finished rescan for 94 addresses (synced to block 0000000000000000000321c16db06f19e9ae9c8473002e13cf8b10d379d9e6be, height 596914)
2019-09-28 04:18:36.801 [INF] LTND: Chain backend is fully synced (end_height=596914)!
2019-09-28 04:18:36.816 [TRC] CHNF: ChannelNotifier starting
2019-09-28 04:18:36.915 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:36.915 [INF] HSWC: Starting HTLC Switch
2019-09-28 04:18:36.917 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:37.086 [TRC] SWPR: Sweeper starting
2019-09-28 04:18:37.089 [DBG] SWPR: Best height: 596914
2019-09-28 04:18:37.089 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:37.093 [TRC] UTXN: Starting UTXO nursery
2019-09-28 04:18:37.124 [TRC] CNCT: Starting ChainArbitrator
2019-09-28 04:18:37.125 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:37.181 [INF] CNCT: Creating ChannelArbitrators for 3 active channels
2019-09-28 04:18:37.181 [DBG] CNCT: New ChainEventSubscription(id=0) for ChannelPoint(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0)
2019-09-28 04:18:37.181 [TRC] CNCT: Creating ChannelArbitrator for ChannelPoint(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0)
2019-09-28 04:18:37.182 [DBG] CNCT: New ChainEventSubscription(id=0) for ChannelPoint(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1)
2019-09-28 04:18:37.182 [TRC] CNCT: Creating ChannelArbitrator for ChannelPoint(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1)
2019-09-28 04:18:37.182 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:37.182 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:37.182 [DBG] CNCT: New ChainEventSubscription(id=0) for ChannelPoint(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1)
2019-09-28 04:18:37.182 [TRC] CNCT: Creating ChannelArbitrator for ChannelPoint(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1)
2019-09-28 04:18:37.182 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:37.190 [DBG] CNCT: Starting chain watcher for ChannelPoint(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0)
2019-09-28 04:18:37.190 [DBG] CNCT: Starting chain watcher for ChannelPoint(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1)
2019-09-28 04:18:37.190 [DBG] CNCT: Starting chain watcher for ChannelPoint(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1)
2019-09-28 04:18:37.192 [DBG] NTFN: Using height hint 596816 retrieved from cache for outpoint=58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0 instead of 581014
2019-09-28 04:18:37.192 [INF] NTFN: New spend subscription: spend_id=1, outpoint=58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0, height_hint=596816
2019-09-28 04:18:37.192 [DBG] NTFN: Dispatching historical spend rescan for outpoint=58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0
2019-09-28 04:18:37.192 [DBG] NTFN: Using height hint 596816 retrieved from cache for outpoint=c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1 instead of 571633
2019-09-28 04:18:37.193 [INF] NTFN: New spend subscription: spend_id=2, outpoint=c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1, height_hint=596816
2019-09-28 04:18:37.193 [DBG] NTFN: Dispatching historical spend rescan for outpoint=c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1
2019-09-28 04:18:37.195 [DBG] NTFN: Using height hint 596816 retrieved from cache for outpoint=c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1 instead of 571633
2019-09-28 04:18:37.195 [INF] NTFN: New spend subscription: spend_id=3, outpoint=c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1, height_hint=596816
2019-09-28 04:18:37.195 [DBG] NTFN: Dispatching historical spend rescan for outpoint=c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1
2019-09-28 04:18:37.205 [TRC] NTFN: Updating spend hint to height 596914 for [outpoint=58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0]
2019-09-28 04:18:37.265 [TRC] NTFN: Updating spend hint to height 596914 for [outpoint=c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1]
2019-09-28 04:18:37.266 [INF] CNCT: Close observer for ChannelPoint(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0) active
2019-09-28 04:18:37.310 [TRC] NTFN: Updating spend hint to height 596914 for [outpoint=c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1]
2019-09-28 04:18:37.310 [INF] CNCT: Close observer for ChannelPoint(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1) active
2019-09-28 04:18:37.355 [INF] CNCT: Close observer for ChannelPoint(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1) active
2019-09-28 04:18:37.355 [DBG] CNCT: Starting ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) (len=2) {
 (contractcourt.HtlcSetKey) RemoteHtlcSet: (contractcourt.htlcSet) {
  incomingHTLCs: (map[uint64]channeldb.HTLC) {
  },
  outgoingHTLCs: (map[uint64]channeldb.HTLC) {
  }
 },
 (contractcourt.HtlcSetKey) LocalHtlcSet: (contractcourt.htlcSet) {
  incomingHTLCs: (map[uint64]channeldb.HTLC) {
  },
  outgoingHTLCs: (map[uint64]channeldb.HTLC) {
  }
 }
}

2019-09-28 04:18:37.356 [INF] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): starting state=StateDefault
2019-09-28 04:18:37.359 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): attempting state step with trigger=chainTrigger from state=StateDefault
2019-09-28 04:18:37.359 [DBG] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): new block (height=596914) examining active HTLC's
2019-09-28 04:18:37.359 [DBG] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): checking chain actions at height=596914
2019-09-28 04:18:37.359 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): no actions to take at height=596914
2019-09-28 04:18:37.359 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): no actions for chain trigger, terminating
2019-09-28 04:18:37.359 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): terminating at state=StateDefault
2019-09-28 04:18:37.359 [DBG] CNCT: Starting ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) (len=2) {
 (contractcourt.HtlcSetKey) LocalHtlcSet: (contractcourt.htlcSet) {
  incomingHTLCs: (map[uint64]channeldb.HTLC) {
  },
  outgoingHTLCs: (map[uint64]channeldb.HTLC) {
  }
 },
 (contractcourt.HtlcSetKey) RemoteHtlcSet: (contractcourt.htlcSet) {
  incomingHTLCs: (map[uint64]channeldb.HTLC) {
  },
  outgoingHTLCs: (map[uint64]channeldb.HTLC) {
  }
 }
}

2019-09-28 04:18:37.360 [INF] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): starting state=StateDefault
2019-09-28 04:18:37.360 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): attempting state step with trigger=chainTrigger from state=StateDefault
2019-09-28 04:18:37.360 [DBG] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): new block (height=596914) examining active HTLC's
2019-09-28 04:18:37.361 [DBG] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): checking chain actions at height=596914
2019-09-28 04:18:37.361 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): no actions to take at height=596914
2019-09-28 04:18:37.361 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): no actions for chain trigger, terminating
2019-09-28 04:18:37.361 [TRC] CNCT: ChannelArbitrator(c9a8fcd5f39e3acab35ea353ba8e64035ba4082a26d6e96ef711f97da74133e7:1): terminating at state=StateDefault
2019-09-28 04:18:37.363 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): attempting state step with trigger=chainTrigger from state=StateDefault
2019-09-28 04:18:37.363 [DBG] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): new block (height=596914) examining active HTLC's
2019-09-28 04:18:37.364 [DBG] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): checking chain actions at height=596914
2019-09-28 04:18:37.364 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): no actions to take at height=596914
2019-09-28 04:18:37.364 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): no actions for chain trigger, terminating
2019-09-28 04:18:37.364 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): terminating at state=StateDefault
2019-09-28 04:18:37.364 [DBG] CNCT: Starting ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) (len=2) {
 (contractcourt.HtlcSetKey) RemoteHtlcSet: (contractcourt.htlcSet) {
  incomingHTLCs: (map[uint64]channeldb.HTLC) {
  },
  outgoingHTLCs: (map[uint64]channeldb.HTLC) {
  }
 },
 (contractcourt.HtlcSetKey) LocalHtlcSet: (contractcourt.htlcSet) {
  incomingHTLCs: (map[uint64]channeldb.HTLC) {
  },
  outgoingHTLCs: (map[uint64]channeldb.HTLC) {
  }
 }
}

2019-09-28 04:18:37.364 [INF] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): starting state=StateDefault
2019-09-28 04:18:37.364 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): attempting state step with trigger=chainTrigger from state=StateDefault
2019-09-28 04:18:37.364 [DBG] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): new block (height=596914) examining active HTLC's
2019-09-28 04:18:37.364 [DBG] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): checking chain actions at height=596914
2019-09-28 04:18:37.364 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): no actions to take at height=596914
2019-09-28 04:18:37.365 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): no actions for chain trigger, terminating
2019-09-28 04:18:37.365 [TRC] CNCT: ChannelArbitrator(c56ed189ccb84e0a188bed37d2c4b73310344df8d6fbb9e8c0b43f8c4c3611c7:1): terminating at state=StateDefault
2019-09-28 04:18:37.367 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): attempting state step with trigger=chainTrigger from state=StateDefault
2019-09-28 04:18:37.368 [DBG] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): new block (height=596914) examining active HTLC's
2019-09-28 04:18:37.368 [DBG] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): checking chain actions at height=596914
2019-09-28 04:18:37.368 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): no actions to take at height=596914
2019-09-28 04:18:37.368 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): no actions for chain trigger, terminating
2019-09-28 04:18:37.368 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): terminating at state=StateDefault
2019-09-28 04:18:37.368 [TRC] BRAR: Starting breach arbiter
2019-09-28 04:18:37.368 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): attempting state step with trigger=chainTrigger from state=StateDefault
2019-09-28 04:18:37.368 [DBG] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): new block (height=596914) examining active HTLC's
2019-09-28 04:18:37.368 [DBG] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): checking chain actions at height=596914
2019-09-28 04:18:37.369 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): no actions to take at height=596914
2019-09-28 04:18:37.369 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): no actions for chain trigger, terminating
2019-09-28 04:18:37.369 [TRC] CNCT: ChannelArbitrator(58b4aa8d1869e598fd4cf0f10e8171279ac2df59ae5e0edad9030cf4cfa6e34b:0): terminating at state=StateDefault
2019-09-28 04:18:37.375 [INF] DISC: Authenticated Gossiper is starting
2019-09-28 04:18:37.375 [INF] BRAR: Starting contract observer, watching for breaches.
2019-09-28 04:18:37.375 [INF] NTFN: New block epoch subscription
2019-09-28 04:18:37.378 [TRC] CRTR: Channel Router starting
2019-09-28 04:18:37.378 [DBG] DISC: Requesting online notification for peer=02659867866aa19e7d6e72be3408b832ce28579322da603679054d753494da8d26
2019-09-28 04:18:37.435 [INF] CRTR: FilteredChainView starting
2019-09-28 04:19:37.823 [INF] LTND: Version: 0.7.1-beta commit=v0.7.1-beta, build=production, logging=default
2019-09-28 04:19:37.823 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2019-09-28 04:19:37.827 [INF] CHDB: Checking for schema update: latest_version=9, db_version=9
2019-09-28 04:19:37.914 [INF] RPCS: password RPC server listening on 0.0.0.0:10009
2019-09-28 04:19:37.914 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2019-09-28 04:19:37.914 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
```

More:

```
****************************************
* The LND service is not running.
****************************************
If you just started some config/setup, this might be OK.

2 RESTARTS DETECTED - LND might be in a error loop
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/channeldb.nodeTraversal(0x0, 0x2c88800, 0x21, 0x21, 0x30650, 0x37cca50, 0xa63938, 0x1)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:234+0x9c
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/channeldb.(*LightningNode).ForEachChannel(...)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:237
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/routing.(*ChannelRouter).ForAllOutgoingChannels(0x2de4b600x37cca48, 0x16bc080, 0x0)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/routing/router.go:23410x7c
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).retransmitStaleChannel0x2c88a00, 0xcf3f30, 0x2c81a10)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:38 +0x78
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler(0x2c88a)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:2 +0xec
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).start
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:6 +0x15c
```

**Comment by thrasher-** [comment]
[log.txt](https://github.com/lightningnetwork/lnd/files/3665062/log.txt)

**Comment by halseth** [comment]
Can you make sure it is not the run script you are using that is restarting lnd? (try starting lnd normally)

I suspect that's the case, since lnd won't prompt for the password again after being unlocked.

**Comment by wpaulino** [comment]
Your initial report includes v0.7.1, but the logs attached in a following comment show v0.8.0. Did you try upgrading to address the issue? It seems like `lnd` is crashing with:

```
Sep 28 04:43:26 thrasherlnd01 lnd[12759]: panic: freepages: failed to get all reachable pages (page -1835263452: out of bounds: 27465)
Sep 28 04:43:26 thrasherlnd01 lnd[12759]: goroutine 28 [running]:
Sep 28 04:43:26 thrasherlnd01 lnd[12759]: github.com/coreos/bbolt.(*DB).freepages.func2(0x20787c0)
Sep 28 04:43:26 thrasherlnd01 lnd[12759]:         github.com/coreos/bbolt@v1.3.3/db.go:1003 +0xcc
Sep 28 04:43:26 thrasherlnd01 lnd[12759]: created by github.com/coreos/bbolt.(*DB).freepages
Sep 28 04:43:26 thrasherlnd01 lnd[12759]:         github.com/coreos/bbolt@v1.3.3/db.go:1001 +0x108
```

This could be related to https://github.com/lightningnetwork/lnd/pull/3278, but could also just point to database corruption. If I recall correctly, you've had an issue like this in the past though.

**Comment by thrasher-** [comment]
Thanks for your responses. Tried manually starting LND and got

```
lnd
2019-10-01 02:40:04.780 [INF] LTND: Version: 0.8.0-beta commit=v0.8.0-beta-rc1, build=production, logging=default
2019-10-01 02:40:04.780 [INF] LTND: Active chain: Bitcoin (network=mainnet)
panic: freepages: failed to get all reachable pages (page -1835263452: out of bounds: 27465)

goroutine 54 [running]:
github.com/coreos/bbolt.(*DB).freepages.func2(0x216a580)
        github.com/coreos/bbolt@v1.3.3/db.go:1003 +0xcc
created by github.com/coreos/bbolt.(*DB).freepages
        github.com/coreos/bbolt@v1.3.3/db.go:1001 +0x108
```

@wpaulino spot on, tried 0.7.1 which was bundled with Raspiblitz, but had the same issue. Tried upgrading to v0.8.0 to see if it helped but now run into the above. My Raspi encountered undervoltage reports in the past (now upgraded to a Raspi 4) which reports 0. If the DB is corrupted, what's the best way of salvaging it and starting from fresh with the existing funds?

**Comment by wpaulino** [comment]
The panic during `v0.7.1` leads me to believe it is corrupted:

```
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/channeldb.nodeTraversal(0x0, 0x2c88800, 0x21, 0x21, 0x30650, 0x37cca50, 0xa63938, 0x1)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:234+0x9c
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/channeldb.(*LightningNode).ForEachChannel(...)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/channeldb/graph.go:237
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/routing.(*ChannelRouter).ForAllOutgoingChannels(0x2de4b600x37cca48, 0x16bc080, 0x0)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/routing/router.go:23410x7c
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).retransmitStaleChannel0x2c88a00, 0xcf3f30, 0x2c81a10)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:38 +0x78
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler(0x2c88a)
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:2 +0xec
Sep 28 04:18:37 thrasherlnd01 lnd[5718]: created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).start
Sep 28 04:18:37 thrasherlnd01 lnd[5718]:         /Users/roasbeef/gocode/src/gi
```

> what's the best way of salvaging it and starting from fresh with the existing funds?

You can follow our [recovery documentation](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md).

**Comment by thrasher-** [comment]
Thanks guys, have restarted from scratch
