### ISSUE TITLE
Getting a lot of crashes when syncing up a new node (Neutrino)

### ISSUE THREAD

**Issue by nolim1t** [lightningnetwork/lnd#3611]
### Background

I'm seeing a lot of errors when I'm syncing up a new node (neutrino). However when it restarts again it resumes syncing. 

No pattern when it crashes. Just happens.

### Your environment

* 0.8.0
* Two different environments: ```Linux 4.19.67-0-rpi #1-Alpine SMP PREEMPT Tue Aug 20 08:35:23 UTC 2019 aarch64 Linux``` ``` Linux 4.19.76-0-rpi #1-Alpine Tue Oct 1 08:51:58 UTC 2019 armv6l Linux```

*  Neutrino backend
* The arm6 is compiled from source, the aarch64 is run from this [docker image](https://github.com/lncm/docker-lnd/tree/master/0.8)

### Steps to reproduce

Just run a new LND with neutrino mode, wait a bit.. get a random crash

### Expected behaviour

Node should not not crash

### Actual behaviour

Node crashes with the following

```
goroutine 65 [running]:
github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders.func1(0x40000bc460, 0xfd66e0, 0x4000214450, 0xfd64a0, 0x40001e2b40, 0x4000088101)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:1051 +0xc80
github.com/lightninglabs/neutrino.queryChainServiceBatch(0x40000da280, 0x400033a260, 0x1, 0x1, 0x40001e2d20, 0x4000092840, 0x0, 0x0, 0x0)
	github.com/lightninglabs/neutrino@v0.10.0/query.go:569 +0x794
github.com/lightninglabs/neutrino.NewChainService.func3(0x400033a260, 0x1, 0x1, 0x40001e2d20, 0x4000092840, 0x0, 0x0, 0x0)
	github.com/lightninglabs/neutrino@v0.10.0/neutrino.go:674 +0x68
github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders(0x40004921a0, 0x4000a72000, 0x6f, 0x80, 0x40000b2170, 0x0)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:916 +0x730
github.com/lightninglabs/neutrino.(*blockManager).cfHandler(0x40004921a0)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:623 +0xc1c
github.com/lightninglabs/neutrino.(*blockManager).Start.func1(0x40004921a0)
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:312 +0x19c
created by github.com/lightninglabs/neutrino.(*blockManager).Start
	github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:298 +0x114
```

message before that (with random blocks, not just a specific block)

```
panic: couldn't write cfheaders msg: attempt to write cfheaders out of order! Tip=6a6221d5fbcc14f48b1b1f1e912c04e8e101b060ebc49a9dfcf6edab4fea7173 (height=123000), prev_hash=143b4bfd819c7719d2e4c824f799bb184f92da88ddd79d5b170c964d93af5917.
```

**Comment by wpaulino** [comment]
Fixed in https://github.com/lightningnetwork/lnd/pull/3704.
