### ISSUE TITLE
Panic when starting lnd

### ISSUE THREAD

**Issue by riperk** [lightningnetwork/lnd#3671]
On a pretty recent version:

```
2019-11-03 22:28:34.924 [INF] LTND: Version: 0.8.0-beta commit=v0.8.0-beta-80-g64e5d06cd19f3d9da8fc67da6287ddea1308c07e, build=production, logging=default
2019-11-03 22:28:34.924 [INF] LTND: Active chain: Bitcoin (network=testnet)
2019-11-03 22:28:44.926 [INF] CHDB: Checking for schema update: latest_version=11, db_version=11
2019-11-03 22:28:46.582 [INF] BTCN: Loaded 25 addresses from file '/home/ubuntu/.lnd/data/chain/bitcoin/testnet/peers.json'
2019-11-03 22:28:46.582 [INF] BTCN: Registering block subscription: id=1
2019-11-03 22:28:46.584 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080
2019-11-03 22:28:46.584 [INF] BTCN: Broadcaster now active
2019-11-03 22:28:46.585 [INF] RPCS: password RPC server listening on 0.0.0.0:10009
2019-11-03 22:28:46.585 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2019-11-03 22:28:46.610 [INF] BTCN: New valid peer 159.203.125.125:18333 (outbound) (/btcwire:0.5.0/btcd:0.20.0/)
2019-11-03 22:28:46.611 [INF] BTCN: Syncing to block height 1605942 from peer 159.203.125.125:18333
2019-11-03 22:28:46.611 [INF] BTCN: Fetching set of headers from tip (height=1584769) from peer 159.203.125.125:18333
2019-11-03 22:28:46.614 [INF] BTCN: Waiting for more block headers, then will start cfheaders sync from height 1583000...
2019-11-03 22:28:46.614 [INF] BTCN: Starting cfheaders sync from (block_height=1583000, block_hash=00000000001712847278a37b457e43bcae71b449bea94828b7cbc5d00bdea0cf) to (block_height=1584769, block_hash=b15b1a02e6ecc8970da17b3f2ff1e13e432b231ef774520aee1f725a0e2535a3)
2019-11-03 22:28:46.614 [INF] BTCN: Starting cfheaders sync for filter_type=0
2019-11-03 22:28:46.637 [INF] BTCN: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: No address associated with hostname
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x946a7c]

goroutine 24 [running]:
github.com/lightninglabs/neutrino.(*blockManager).handleHeadersMsg(0xc0000341a0, 0xc0004edd60)
        /home/ubuntu/go/pkg/mod/github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:2499 +0xa9c
github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0xc0000341a0)
        /home/ubuntu/go/pkg/mod/github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:1940 +0x2be
created by github.com/lightninglabs/neutrino.(*blockManager).Start
        /home/ubuntu/go/pkg/mod/github.com/lightninglabs/neutrino@v0.10.0/blockmanager.go:297 +0xd9
```

**Comment by riperk** [comment]
Updated to master (083b574fd800bc218477f29b9b7a3f8554347034) and getting the exact same panic with the same stack.

**Comment by wpaulino** [comment]
Do you have more logs before this to see if there are any hints as to how you arrived at this state?

**Comment by riperk** [comment]
Nope. I ended up just nuking the whole thing and re-syncing from scratch
