### ISSUE TITLE
panic: runtime error: slice bounds out of range [::2762892038] with length 2147483647

### ISSUE THREAD

**Issue by zagota** [lightningnetwork/lnd#3888]
### Background

After starting lnd...
```
2020-01-04 10:36:41.442 [INF] LTND: Version: 0.8.2-beta commit=v0.8.2-beta, build=production, logging=default
2020-01-04 10:36:41.443 [INF] LTND: Active chain: Bitcoin (network=testnet)
2020-01-04 10:36:41.499 [INF] LTND: Shutdown complete
panic: runtime error: slice bounds out of range [::2762892038] with length 2147483647

goroutine 1 [running]:
github.com/coreos/bbolt.(*leafPageElement).key(...)
	github.com/coreos/bbolt@v1.3.3/page.go:120
github.com/coreos/bbolt.(*Cursor).keyValue(0xc00044ad68, 0x5462b446, 0x1fa, 0x1fa, 0x7f485462b44e, 0x1fa, 0x1fa, 0xc00008e1c0)
	github.com/coreos/bbolt@v1.3.3/cursor.go:350 +0x1b7
github.com/coreos/bbolt.(*Cursor).next(0xc00044ad68, 0xc00044ad18, 0x6a2c80, 0xc00008e1c0, 0x7f485462b446, 0x8, 0x8, 0x0)
	github.com/coreos/bbolt@v1.3.3/cursor.go:242 +0xd1
github.com/coreos/bbolt.(*Cursor).Next(0xc00044ad68, 0x8, 0x8, 0x7f485462b44e, 0x1fa, 0x1fa, 0x0)
	github.com/coreos/bbolt@v1.3.3/cursor.go:75 +0x41
github.com/coreos/bbolt.(*Bucket).ForEach(0xc00008e1c0, 0xc00044adb8, 0x0, 0xc00044ade8)
	github.com/coreos/bbolt@v1.3.3/bucket.go:387 +0xb4
github.com/coreos/bbolt.(*Tx).checkBucket(0xc0001580e0, 0xc00008e1c0, 0xc00044b220, 0xc00044b1f0, 0xc0000da3c0)
	github.com/coreos/bbolt@v1.3.3/tx.go:488 +0x146
github.com/coreos/bbolt.(*Tx).checkBucket.func2(0x7f485667a50c, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/coreos/bbolt@v1.3.3/tx.go:490 +0xc0
github.com/coreos/bbolt.(*Bucket).ForEach(0xc00008f280, 0xc00044af10, 0x0, 0xc00044af40)
	github.com/coreos/bbolt@v1.3.3/bucket.go:388 +0xfe
github.com/coreos/bbolt.(*Tx).checkBucket(0xc0001580e0, 0xc00008f280, 0xc00044b220, 0xc00044b1f0, 0xc0000da3c0)
	github.com/coreos/bbolt@v1.3.3/tx.go:488 +0x146
github.com/coreos/bbolt.(*Tx).checkBucket.func2(0x7f485685b2a9, 0xa, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/coreos/bbolt@v1.3.3/tx.go:490 +0xc0
github.com/coreos/bbolt.(*Bucket).ForEach(0xc0001580f8, 0xc00044b068, 0x0, 0xc00044b098)
	github.com/coreos/bbolt@v1.3.3/bucket.go:388 +0xfe
github.com/coreos/bbolt.(*Tx).checkBucket(0xc0001580e0, 0xc0001580f8, 0xc00044b220, 0xc00044b1f0, 0xc0000da3c0)
	github.com/coreos/bbolt@v1.3.3/tx.go:488 +0x146
github.com/coreos/bbolt.(*DB).freepages(0xc000486c00, 0x0, 0x0, 0x0)
	github.com/coreos/bbolt@v1.3.3/db.go:1006 +0x211
github.com/coreos/bbolt.(*DB).loadFreelist.func1()
	github.com/coreos/bbolt@v1.3.3/db.go:313 +0x10c
sync.(*Once).doSlow(0xc000486d68, 0xc00044b3d8)
	sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	sync/once.go:57
github.com/coreos/bbolt.(*DB).loadFreelist(0xc000486c00)
	github.com/coreos/bbolt@v1.3.3/db.go:309 +0x6a
github.com/coreos/bbolt.Open(0xc000036810, 0x2d, 0x180, 0xc00044b5a8, 0x2d, 0x78, 0x40c1b6)
	github.com/coreos/bbolt@v1.3.3/db.go:286 +0x35d
github.com/lightningnetwork/lnd/channeldb.Open(0xc0000367e0, 0x22, 0xc00044bd88, 0x3, 0x3, 0x2, 0x90, 0xa0)
	github.com/lightningnetwork/lnd@/channeldb/db.go:158 +0x1d0
github.com/lightningnetwork/lnd.Main(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/lightningnetwork/lnd@/lnd.go:189 +0x4bb
main.main()
	github.com/lightningnetwork/lnd@/cmd/lnd/main.go:14 +0x32

```

### Your environment

* version of `lnd`
Version: 0.8.2-beta commit=v0.8.2-beta, build=production, logging=default

* which operating system (`uname -a` on *Nix)
Linux ubnt-ln 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v0.19.0.1

### Steps to reproduce
Starting lnd

**Comment by wpaulino** [comment]
Are you running with `sync-freelist=true` in your config? If not, does setting it and restarting help your node make progress?

**Comment by Roasbeef** [comment]
What type of hardware are you running on?
