### ISSUE TITLE
RPI zero: fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by grunch** [lightningnetwork/lnd#4240]
### Background
I've been using neutrino on a Raspberry pi zero for a while without any problem, recently I updated to master and I can't even unlock the wallet cause I get an `out of memory` error and lnd crash.

Is it a new feature added to unlock that is needing more memory? is it a way to fix it without go back to an older lnd version?

### Your environment

* lnd version 0.10.0-beta commit=v0.10.0-beta-37-g2c979fc17916fdbcddf60e095a810dce3406b030
* Linux 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux
*  Raspberry Pi Zero W Rev 1.1, 512 MB ram

### Steps to reproduce
* Run lnd
* unlock lnd wallet

### Expected behaviour
No crash

### Actual behaviour
Lnd crash

**Comment by grunch** [comment]
this is the log when lnd crash
```
2020-05-03 17:11:00.291 [INF] LNWL: Opened wallet
2020-05-03 17:11:01.634 [INF] LTND: Primary chain is set to: bitcoin
2020-05-03 17:11:01.673 [INF] LTND: Using API fee estimator!
2020-05-03 17:11:01.681 [INF] LNWL: Starting web API fee estimator
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc5676e, 0x16)
	/usr/local/go/src/runtime/panic.go:1116 +0x5c
runtime.sysMap(0x22400000, 0x10000000, 0x179cc70)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xa8
runtime.(*mheap).sysAlloc(0x178fe08, 0x10000000, 0x75b34, 0x9dffbcfc)
	/usr/local/go/src/runtime/malloc.go:715 +0x184
runtime.(*mheap).grow(0x178fe08, 0x8000, 0x0)
	/usr/local/go/src/runtime/mheap.go:1286 +0x134
runtime.(*mheap).allocSpan(0x178fe08, 0x8000, 0x2000100, 0x179cc80, 0x2000fdc)
	/usr/local/go/src/runtime/mheap.go:1124 +0x64c
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:871 +0x50
runtime.(*mheap).alloc(0x178fe08, 0x8000, 0x2000101, 0x2001c00)
	/usr/local/go/src/runtime/mheap.go:865 +0x58
runtime.largeAlloc(0x10000000, 0x101, 0x2001c00)
	/usr/local/go/src/runtime/malloc.go:1152 +0x6c
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1047 +0x38
runtime.systemstack(0x152)
	/usr/local/go/src/runtime/asm_arm.s:347 +0x84
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1041

goroutine 97 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm.s:294 +0x4 fp=0x2056890 sp=0x205688c pc=0x77e98
runtime.mallocgc(0x10000000, 0xacafb0, 0x1, 0x2c65000)
	/usr/local/go/src/runtime/malloc.go:1046 +0x8cc fp=0x20568f4 sp=0x2056890 pc=0x1da44
runtime.makeslice(0xacafb0, 0x4000000, 0x4000000, 0x2c65000)
	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0x2056908 sp=0x20568f4 pc=0x60628
golang.org/x/crypto/scrypt.Key(0x21e51a0, 0xc, 0x10, 0x22b7774, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
	/home/pi/go/pkg/mod/golang.org/x/crypto@v0.0.0-20190211182817-74369b46fc67/scrypt/scrypt.go:236 +0x134 fp=0x205695c sp=0x2056908 pc=0x35b5b4
github.com/btcsuite/btcwallet/snacl.(*SecretKey).deriveKey(0x22b7770, 0x2056cc4, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/snacl/snacl.go:114 +0x64 fp=0x20569a8 sp=0x205695c pc=0x35bc60
github.com/btcsuite/btcwallet/snacl.(*SecretKey).DeriveKey(0x22b7770, 0x2056cc4, 0x9351598, 0x9cbe7c8)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/snacl/snacl.go:201 +0x24 fp=0x20569f8 sp=0x20569a8 pc=0x35c144
github.com/btcsuite/btcwallet/waddrmgr.(*Manager).Unlock(0x20e89a0, 0xa5b631f8, 0x2c55dc0, 0x21e51a0, 0xc, 0x10, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/waddrmgr/manager.go:1124 +0x234 fp=0x2056cb4 sp=0x20569f8 pc=0x36cff8
github.com/btcsuite/btcwallet/wallet.(*Wallet).walletLocker.func1(0xf56400, 0x2c68788, 0x2c68788, 0x0)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/wallet/wallet.go:1221 +0x90 fp=0x2056ce0 sp=0x2056cb4 pc=0x4f1b80
github.com/btcsuite/btcwallet/walletdb.View(0xf5e488, 0x2401040, 0x21c4dfc, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet/walletdb@v1.3.1/interface.go:236 +0x98 fp=0x2056d18 sp=0x2056ce0 pc=0x3382cc
github.com/btcsuite/btcwallet/wallet.(*Wallet).walletLocker(0x20fe0c0)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/wallet/wallet.go:1219 +0x5a4 fp=0x2056fe4 sp=0x2056d18 pc=0x4e9690
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:857 +0x4 fp=0x2056fe4 sp=0x2056fe4 pc=0x79d34
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).Start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/wallet/wallet.go:148 +0xc0

goroutine 1 [chan receive]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).Unlock(...)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/wallet/wallet.go:1322
github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).Start(0x2c78090, 0x1, 0x1)
	/home/pi/go/src/github.com/lightningnetwork/lnd/lnwallet/btcwallet/btcwallet.go:159 +0xbc
github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).Startup(0x2450e00, 0x2450e00, 0x2b93b00)
	/home/pi/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:352 +0x4c
github.com/lightningnetwork/lnd.newChainControlFromConfig(0x204cb40, 0x20ccf20, 0x21e51a0, 0xc, 0x10, 0x21e51a0, 0xc, 0x10, 0x0, 0x0, ...)
	/home/pi/go/src/github.com/lightningnetwork/lnd/chainregistry.go:534 +0xaf8
github.com/lightningnetwork/lnd.Main(0x0, 0x0, 0x0, 0x0)
	/home/pi/go/src/github.com/lightningnetwork/lnd/lnd.go:426 +0xba8
main.main()
	/home/pi/go/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:14 +0x20

goroutine 8 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x130
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.Notify.func1
	/usr/local/go/src/os/signal/signal.go:127 +0x34

goroutine 10 [select, 1 minutes]:
github.com/lightningnetwork/lnd/signal.mainInterruptHandler()
	/home/pi/go/src/github.com/lightningnetwork/lnd/signal/signal.go:71 +0xc8
created by github.com/lightningnetwork/lnd/signal.Intercept
	/home/pi/go/src/github.com/lightningnetwork/lnd/signal/signal.go:39 +0xac

goroutine 13 [select]:
io.(*pipe).Read(0x216d540, 0x214f000, 0x1000, 0x1000, 0x216d500, 0x103c08, 0x1690100)
	/usr/local/go/src/io/pipe.go:57 +0xac
io.(*PipeReader).Read(0x215afe0, 0x214f000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:134 +0x38
bufio.(*Reader).fill(0x2046784)
	/usr/local/go/src/bufio/bufio.go:100 +0x108
bufio.(*Reader).ReadSlice(0x2046784, 0xa, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:359 +0x2c
bufio.(*Reader).ReadLine(0x2046784, 0x1690173, 0x1, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:388 +0x24
github.com/jrick/logrotate/rotator.(*Rotator).Run(0x2073950, 0xf52fe0, 0x215afe0, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/jrick/logrotate@v1.0.0/rotator/rotator.go:100 +0x90
github.com/lightningnetwork/lnd/build.(*RotatingLogWriter).InitLogRotator.func1(0x2441520, 0x215afe0)
	/home/pi/go/src/github.com/lightningnetwork/lnd/build/logrotator.go:80 +0x30
created by github.com/lightningnetwork/lnd/build.(*RotatingLogWriter).InitLogRotator
	/home/pi/go/src/github.com/lightningnetwork/lnd/build/logrotator.go:79 +0x288

goroutine 22 [select]:
github.com/btcsuite/btcd/addrmgr.(*AddrManager).addressHandler(0x20ac000)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/addrmgr/addrmanager.go:346 +0xcc
created by github.com/btcsuite/btcd/addrmgr.(*AddrManager).Start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/addrmgr/addrmanager.go:580 +0xd0

goroutine 23 [select]:
github.com/lightninglabs/neutrino.(*blockManager).blockHandler(0x2400280)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockmanager.go:2083 +0xf0
created by github.com/lightninglabs/neutrino.(*blockManager).Start
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockmanager.go:322 +0xb8

goroutine 24 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0x27b3308, 0x0)
	/usr/local/go/src/runtime/sema.go:513 +0x154
sync.(*Cond).Wait(0x27b3300)
	/usr/local/go/src/sync/cond.go:56 +0x6c
github.com/lightninglabs/neutrino.(*blockManager).cfHandler(0x2400280)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockmanager.go:688 +0xdc0
github.com/lightninglabs/neutrino.(*blockManager).Start.func1(0x2400280)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockmanager.go:337 +0x178
created by github.com/lightninglabs/neutrino.(*blockManager).Start
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockmanager.go:323 +0xd4

goroutine 25 [select]:
github.com/lightninglabs/neutrino/blockntfns.(*SubscriptionManager).subscriptionHandler(0x2068cc0)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockntfns/manager.go:160 +0x124
created by github.com/lightninglabs/neutrino/blockntfns.(*SubscriptionManager).Start
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockntfns/manager.go:124 +0xbc

goroutine 26 [select]:
github.com/lightninglabs/neutrino/query.(*WorkManager).workDispatcher(0x27b2d60)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/query/workmanager.go:255 +0x67c
created by github.com/lightninglabs/neutrino/query.(*WorkManager).Start
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/query/workmanager.go:133 +0x48

goroutine 27 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0x27b3648, 0x0)
	/usr/local/go/src/runtime/sema.go:513 +0x154
sync.(*Cond).Wait(0x27b3640)
	/usr/local/go/src/sync/cond.go:56 +0x6c
github.com/lightninglabs/neutrino.(*UtxoScanner).batchManager(0x20923c0)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/utxoscanner.go:220 +0xd8
created by github.com/lightninglabs/neutrino.(*UtxoScanner).Start
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/utxoscanner.go:137 +0x70

goroutine 28 [select]:
github.com/lightningnetwork/lnd/queue.(*ConcurrentQueue).start.func1(0x2168ec0)
	/home/pi/go/src/github.com/lightningnetwork/lnd/queue/queue.go:68 +0x48c
created by github.com/lightningnetwork/lnd/queue.(*ConcurrentQueue).start
	/home/pi/go/src/github.com/lightningnetwork/lnd/queue/queue.go:58 +0x48

goroutine 29 [select]:
github.com/lightninglabs/neutrino/blockntfns.(*SubscriptionManager).NewSubscription.func1(0x2168f40, 0x2068cc0)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockntfns/manager.go:223 +0xd4
created by github.com/lightninglabs/neutrino/blockntfns.(*SubscriptionManager).NewSubscription
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/blockntfns/manager.go:219 +0x214

goroutine 30 [select]:
github.com/lightninglabs/neutrino/pushtx.(*Broadcaster).broadcastHandler(0x2068f00, 0x2011618)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/pushtx/broadcaster.go:166 +0x228
created by github.com/lightninglabs/neutrino/pushtx.(*Broadcaster).Start.func1
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/pushtx/broadcaster.go:94 +0xcc

goroutine 32 [select]:
github.com/lightninglabs/neutrino.(*ChainService).peerHandler(0x20fc1a0)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/neutrino.go:1082 +0x1b4
created by github.com/lightninglabs/neutrino.(*ChainService).Start
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/neutrino.go:1527 +0x158

goroutine 109 [select]:
net/http.(*persistConn).writeLoop(0x2420000)
	/usr/local/go/src/net/http/transport.go:2277 +0xc4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1648 +0x9d4

goroutine 37 [select]:
github.com/btcsuite/btcd/connmgr.(*ConnManager).connHandler(0x2432c60)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/connmgr/connmanager.go:241 +0xf4
created by github.com/btcsuite/btcd/connmgr.(*ConnManager).Start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/connmgr/connmanager.go:518 +0xbc

goroutine 77 [select]:
github.com/lightninglabs/neutrino/query.(*worker).Run(0x21bcf50, 0x2066780, 0x20667c0)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/query/worker.go:95 +0x1c4
github.com/lightninglabs/neutrino/query.(*WorkManager).workDispatcher.func2(0x27b2d60, 0x22d36c0, 0xf56460, 0x21bcf50)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/query/workmanager.go:282 +0x80
created by github.com/lightninglabs/neutrino/query.(*WorkManager).workDispatcher
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/query/workmanager.go:278 +0x18f0

goroutine 96 [select]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).txCreator(0x20fe0c0)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/wallet/wallet.go:1139 +0x9c
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).Start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200403222202-ada7ca077ebb/wallet/wallet.go:147 +0xa4

goroutine 80 [select]:
github.com/btcsuite/btcd/peer.(*Peer).queueHandler(0x204d680)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:1574 +0x1b0
created by github.com/btcsuite/btcd/peer.(*Peer).start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:2154 +0x240

goroutine 79 [IO wait]:
internal/poll.runtime_pollWait(0xa5b5ab9c, 0x72, 0xffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x44
internal/poll.(*pollDesc).wait(0x2092d84, 0x72, 0x0, 0x18, 0xffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x2092d70, 0x21eb120, 0x18, 0x18, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x174
net.(*netFD).Read(0x2092d70, 0x21eb120, 0x18, 0x18, 0x18, 0x21eb120, 0x20d3340)
	/usr/local/go/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x20c47b0, 0x21eb120, 0x18, 0x18, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x64
io.ReadAtLeast(0xf530d0, 0x20c47b0, 0x21eb120, 0x18, 0x18, 0x18, 0x2, 0x0, 0x0)
	/usr/local/go/src/io/io.go:310 +0x6c
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
github.com/btcsuite/btcd/wire.readMessageHeader(0xf530d0, 0x20c47b0, 0x0, 0x55df20, 0x216d540, 0x222ee48)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/wire/message.go:204 +0x50
github.com/btcsuite/btcd/wire.ReadMessageWithEncodingN(0xf530d0, 0x20c47b0, 0x1117d, 0xd9b4bef9, 0x2, 0x22873b0, 0xcb04c, 0x2287384, 0x789e4f61, 0x13f, ...)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/wire/message.go:344 +0x28
github.com/btcsuite/btcd/peer.(*Peer).readMessage(0x204d680, 0x2, 0x45, 0x21bd200, 0x2, 0x2, 0x4ea4, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:1009 +0x78
github.com/btcsuite/btcd/peer.(*Peer).inHandler(0x204d680)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:1334 +0x98
created by github.com/btcsuite/btcd/peer.(*Peer).start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:2153 +0x224

goroutine 78 [select]:
github.com/btcsuite/btcd/peer.(*Peer).stallHandler(0x204d680)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:1198 +0x164
created by github.com/btcsuite/btcd/peer.(*Peer).start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:2152 +0x208

goroutine 82 [select]:
github.com/btcsuite/btcd/peer.(*Peer).pingHandler(0x204d680)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:1782 +0xb8
created by github.com/btcsuite/btcd/peer.(*Peer).start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:2156 +0x278

goroutine 74 [chan receive]:
github.com/btcsuite/btcd/peer.(*Peer).WaitForDisconnect(...)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:2200
github.com/lightninglabs/neutrino.(*ChainService).peerDoneHandler(0x20fc1a0, 0x21899d0)
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/neutrino.go:1463 +0x2c
created by github.com/lightninglabs/neutrino.(*ChainService).outboundPeerConnected
	/home/pi/go/pkg/mod/github.com/lightninglabs/neutrino@v0.11.1-0.20200316235139-bffc52e8f200/neutrino.go:1457 +0x2f4

goroutine 108 [IO wait]:
internal/poll.runtime_pollWait(0xa5b5a418, 0x72, 0xffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x44
internal/poll.(*pollDesc).wait(0x2092974, 0x72, 0xf00, 0xf87, 0xffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x30
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x2092960, 0x2019000, 0xf87, 0xf87, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x174
net.(*netFD).Read(0x2092960, 0x2019000, 0xf87, 0xf87, 0x179bf58, 0x1d474, 0x1dcd4)
	/usr/local/go/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x2011978, 0x2019000, 0xf87, 0xf87, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x64
crypto/tls.(*atLeastReader).Read(0x2c632b0, 0x2019000, 0xf87, 0xf87, 0x1a430, 0x29a440, 0xf530d0)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x78
bytes.(*Buffer).ReadFrom(0x201c160, 0xf51d80, 0x2c632b0, 0x1d474, 0x298f54, 0xb07be8, 0xc20038)
	/usr/local/go/src/bytes/buffer.go:204 +0xa8
crypto/tls.(*Conn).readFromUntil(0x201c000, 0xf530d0, 0x2011978, 0x5, 0x2011978, 0x14)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xc4
crypto/tls.(*Conn).readRecordOrCCS(0x201c000, 0x0, 0x0, 0x16b34)
	/usr/local/go/src/crypto/tls/conn.go:589 +0xfc
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0x201c000, 0x2c76000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x14c
net/http.(*persistConn).Read(0x2420000, 0x2c76000, 0x1000, 0x1000, 0x2b93a00, 0x428828, 0x2b93a00)
	/usr/local/go/src/net/http/transport.go:1825 +0x168
bufio.(*Reader).fill(0x2c51fb0)
	/usr/local/go/src/bufio/bufio.go:100 +0x108
bufio.(*Reader).Peek(0x2c51fb0, 0x1, 0x0, 0x0, 0x1, 0x2b93900, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x38
net/http.(*persistConn).readLoop(0x2420000)
	/usr/local/go/src/net/http/transport.go:1978 +0x15c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1647 +0x9b8

goroutine 110 [select]:
github.com/lightningnetwork/lnd/lnwallet/chainfee.(*WebAPIEstimator).feeUpdateManager(0x2092780)
	/home/pi/go/src/github.com/lightningnetwork/lnd/lnwallet/chainfee/estimator.go:720 +0xb4
created by github.com/lightningnetwork/lnd/lnwallet/chainfee.(*WebAPIEstimator).Start.func1
	/home/pi/go/src/github.com/lightningnetwork/lnd/lnwallet/chainfee/estimator.go:607 +0xd4

goroutine 81 [select]:
github.com/btcsuite/btcd/peer.(*Peer).outHandler(0x204d680)
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:1708 +0x98
created by github.com/btcsuite/btcd/peer.(*Peer).start
	/home/pi/go/pkg/mod/github.com/btcsuite/btcd@v0.20.1-beta/peer/peer.go:2155 +0x25c
```

**Comment by Roasbeef** [comment]
Nothing significant change recently, other than the migration included in this version. If you compact the database are you able to boot up normally?

**Comment by Roasbeef** [comment]
> Is it a new feature added to unlock that is needing more memory? is it a way to fix it without go back to an older lnd version?

Unlocking has always taken 2-300MB due to the scrypt paramaters we use. In the past, we had planned to create an "aezeed lite" for devices with less memory, but never saw any evidence that it was an issue, so shelved the plans.

**Comment by grunch** [comment]
> Nothing significant change recently, other than the migration included in this version. If you compact the database are you able to boot up normally?

I wanted to start fresh so I deleted `.lnd/data` `.lnd/graph` and `tls*`, just kept `lnd.conf`

Do you have any suggestion to make it work? the rpi doesn't have much processes running, I tried to let it clean

**Comment by Crypt-iQ** [comment]
Possibly related: https://github.com/lightninglabs/neutrino/issues/196

**Comment by Crypt-iQ** [comment]
You can compact the database by running `bbolt` with the compact option (see here: https://github.com/etcd-io/bbolt/blob/master/cmd/bbolt/main.go#L113)

**Comment by grunch** [comment]
> Nothing significant change recently, other than the migration included in this version. If you compact the database are you able to boot up normally?

I compacted all database files and I still getting an ´out of memory´ error and lnd crash.

**Comment by Crypt-iQ** [comment]
Could you get a CPU profile and heap profile? We need to fix the way we do migrations.

**Comment by Roasbeef** [comment]
Closing due to inactivity.

**Comment by EMRahman** [comment]
Ran out of memory; so setup swap file on a different mount e.g. an SDD

Refer to: https://stadicus.github.io/RaspiBolt/raspibolt_20_pi.html#move-swap-file

```
sudo /sbin/dphys-swapfile setup
sudo dphys-swapfile install
sudo dphys-swapfile swapon
```

Check via 
`free -h`
