### ISSUE TITLE
LND not starting after power failure

### ISSUE THREAD

**Issue by Cees2daBees** [lightningnetwork/lnd#4477]
### Background

Experienced a power failure and LND now not starting

### Your environment

lnd version 0.10.4-beta commit=v0.10.4-beta
Linux RaspiBolt 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
Bitcoin Core version v0.20.0

### Steps to reproduce

1. Improper shutdown due to power failure. 
2. LND failed after power came back on.
3. Restarted node using `sudo shutdown -r now`

### Expected behaviour

LND should start

### Actual behaviour

LND keeps cycling through a failure and restart. Logs below:
```
-- Logs begin at Thu 2016-11-03 17:16:42 UTC. --
Jul 20 02:59:16 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 02:59:17 RaspiBolt lnd[700]: Attempting automatic RPC configuration to bitcoind
Jul 20 02:59:17 RaspiBolt lnd[700]: Automatically obtained bitcoind's RPC credentials
Jul 20 02:59:17 RaspiBolt lnd[700]: 2020-07-20 02:59:17.974 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 02:59:17 RaspiBolt lnd[700]: 2020-07-20 02:59:17.974 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 02:59:18 RaspiBolt lnd[700]: 2020-07-20 02:59:18.022 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:27:00 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:27:00 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:27:00 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:28:00 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:28:00 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:28:00 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:28:01 RaspiBolt lnd[1159]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:28:01 RaspiBolt lnd[1159]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:28:01 RaspiBolt lnd[1159]: 2020-07-20 03:28:01.939 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:28:01 RaspiBolt lnd[1159]: 2020-07-20 03:28:01.942 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:28:02 RaspiBolt lnd[1159]: 2020-07-20 03:28:02.020 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:42:38 RaspiBolt lnd[1159]: panic: freepages: failed to get all reachable pages (page 2205: multiple references)
Jul 20 03:42:38 RaspiBolt lnd[1159]: goroutine 7 [running]:
Jul 20 03:42:38 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:42:38 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:42:38 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:43:38 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:43:38 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:43:39 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:43:39 RaspiBolt lnd[1184]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:43:39 RaspiBolt lnd[1184]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:43:39 RaspiBolt lnd[1184]: 2020-07-20 03:43:39.683 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:43:39 RaspiBolt lnd[1184]: 2020-07-20 03:43:39.685 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:43:39 RaspiBolt lnd[1184]: 2020-07-20 03:43:39.737 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:43:57 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:43:57 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:43:57 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:44:57 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:44:57 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:44:57 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:44:57 RaspiBolt lnd[1197]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:44:57 RaspiBolt lnd[1197]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:44:57 RaspiBolt lnd[1197]: 2020-07-20 03:44:57.709 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:44:57 RaspiBolt lnd[1197]: 2020-07-20 03:44:57.709 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:44:57 RaspiBolt lnd[1197]: 2020-07-20 03:44:57.709 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:44:58 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:44:58 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:44:58 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:45:58 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:45:58 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:45:58 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:45:59 RaspiBolt lnd[1210]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:45:59 RaspiBolt lnd[1210]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:45:59 RaspiBolt lnd[1210]: 2020-07-20 03:45:59.226 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:45:59 RaspiBolt lnd[1210]: 2020-07-20 03:45:59.226 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:45:59 RaspiBolt lnd[1210]: 2020-07-20 03:45:59.226 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:46:00 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:46:00 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:46:00 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:47:00 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:47:00 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:47:00 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:47:00 RaspiBolt lnd[1222]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:47:00 RaspiBolt lnd[1222]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:47:00 RaspiBolt lnd[1222]: 2020-07-20 03:47:00.702 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:47:00 RaspiBolt lnd[1222]: 2020-07-20 03:47:00.702 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:47:00 RaspiBolt lnd[1222]: 2020-07-20 03:47:00.702 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:47:01 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:47:01 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:47:01 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:48:01 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:48:01 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:48:01 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:48:02 RaspiBolt lnd[1235]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:48:02 RaspiBolt lnd[1235]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:48:02 RaspiBolt lnd[1235]: 2020-07-20 03:48:02.211 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:48:02 RaspiBolt lnd[1235]: 2020-07-20 03:48:02.212 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:48:02 RaspiBolt lnd[1235]: 2020-07-20 03:48:02.212 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:48:03 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:48:03 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:48:03 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:49:03 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:49:03 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:49:03 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:49:03 RaspiBolt lnd[1251]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:49:03 RaspiBolt lnd[1251]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:49:03 RaspiBolt lnd[1251]: 2020-07-20 03:49:03.714 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:49:03 RaspiBolt lnd[1251]: 2020-07-20 03:49:03.714 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:49:03 RaspiBolt lnd[1251]: 2020-07-20 03:49:03.714 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:49:04 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:49:04 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:49:04 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:50:04 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:50:04 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:50:04 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:50:05 RaspiBolt lnd[1265]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:50:05 RaspiBolt lnd[1265]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:50:05 RaspiBolt lnd[1265]: 2020-07-20 03:50:05.197 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:50:05 RaspiBolt lnd[1265]: 2020-07-20 03:50:05.198 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:50:05 RaspiBolt lnd[1265]: 2020-07-20 03:50:05.198 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:50:06 RaspiBolt lnd[1265]: panic: freepages: failed to get all reachable pages (page 2205: multiple references)
Jul 20 03:50:06 RaspiBolt lnd[1265]: goroutine 58 [running]:
Jul 20 03:50:06 RaspiBolt lnd[1265]: go.etcd.io/bbolt.(*DB).freepages.func2(0x3088a40)
Jul 20 03:50:06 RaspiBolt lnd[1265]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1003 +0xcc
Jul 20 03:50:06 RaspiBolt lnd[1265]: created by go.etcd.io/bbolt.(*DB).freepages
Jul 20 03:50:06 RaspiBolt lnd[1265]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1001 +0x108
Jul 20 03:50:06 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:50:06 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:50:06 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:51:06 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:51:06 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:51:06 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:51:06 RaspiBolt lnd[1277]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:51:06 RaspiBolt lnd[1277]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:51:06 RaspiBolt lnd[1277]: 2020-07-20 03:51:06.709 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:51:06 RaspiBolt lnd[1277]: 2020-07-20 03:51:06.709 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:51:06 RaspiBolt lnd[1277]: 2020-07-20 03:51:06.710 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:51:07 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:51:07 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:51:07 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:52:07 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:52:07 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:52:07 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:52:08 RaspiBolt lnd[1289]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:52:08 RaspiBolt lnd[1289]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:52:08 RaspiBolt lnd[1289]: 2020-07-20 03:52:08.218 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:52:08 RaspiBolt lnd[1289]: 2020-07-20 03:52:08.219 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:52:08 RaspiBolt lnd[1289]: 2020-07-20 03:52:08.219 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:52:09 RaspiBolt lnd[1289]: panic: freepages: failed to get all reachable pages (page 2205: multiple references)
Jul 20 03:52:09 RaspiBolt lnd[1289]: goroutine 7 [running]:
Jul 20 03:52:09 RaspiBolt lnd[1289]: go.etcd.io/bbolt.(*DB).freepages.func2(0x34ab480)
Jul 20 03:52:09 RaspiBolt lnd[1289]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1003 +0xcc
Jul 20 03:52:09 RaspiBolt lnd[1289]: created by go.etcd.io/bbolt.(*DB).freepages
Jul 20 03:52:09 RaspiBolt lnd[1289]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1001 +0x108
Jul 20 03:52:09 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:52:09 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:52:09 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:53:09 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:53:09 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:53:09 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:53:09 RaspiBolt lnd[1301]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:53:09 RaspiBolt lnd[1301]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:53:09 RaspiBolt lnd[1301]: 2020-07-20 03:53:09.636 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:53:09 RaspiBolt lnd[1301]: 2020-07-20 03:53:09.637 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:53:09 RaspiBolt lnd[1301]: 2020-07-20 03:53:09.637 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:53:10 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:53:10 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:53:10 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:54:10 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:54:10 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:54:10 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:54:11 RaspiBolt lnd[1313]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:54:11 RaspiBolt lnd[1313]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:54:11 RaspiBolt lnd[1313]: 2020-07-20 03:54:11.189 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:54:11 RaspiBolt lnd[1313]: 2020-07-20 03:54:11.191 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:54:11 RaspiBolt lnd[1313]: 2020-07-20 03:54:11.192 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:54:12 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:54:12 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:54:12 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:55:12 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:55:12 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:55:12 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:55:12 RaspiBolt lnd[1327]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:55:12 RaspiBolt lnd[1327]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:55:12 RaspiBolt lnd[1327]: 2020-07-20 03:55:12.732 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:55:12 RaspiBolt lnd[1327]: 2020-07-20 03:55:12.733 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:55:12 RaspiBolt lnd[1327]: 2020-07-20 03:55:12.733 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:55:13 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:55:13 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:55:13 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 20 03:56:13 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 20 03:56:13 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Jul 20 03:56:13 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Jul 20 03:56:14 RaspiBolt lnd[1340]: Attempting automatic RPC configuration to bitcoind
Jul 20 03:56:14 RaspiBolt lnd[1340]: Automatically obtained bitcoind's RPC credentials
Jul 20 03:56:14 RaspiBolt lnd[1340]: 2020-07-20 03:56:14.226 [INF] LTND: Version: 0.10.4-beta commit=v0.10.4-beta, build=production, logging=default
Jul 20 03:56:14 RaspiBolt lnd[1340]: 2020-07-20 03:56:14.226 [INF] LTND: Active chain: Bitcoin (network=mainnet)
Jul 20 03:56:14 RaspiBolt lnd[1340]: 2020-07-20 03:56:14.226 [INF] LTND: Opening the main database, this might take a few minutes...
Jul 20 03:56:15 RaspiBolt lnd[1340]: panic: freepages: failed to get all reachable pages (page 2205: multiple references)
Jul 20 03:56:15 RaspiBolt lnd[1340]: goroutine 23 [running]:
Jul 20 03:56:15 RaspiBolt lnd[1340]: go.etcd.io/bbolt.(*DB).freepages.func2(0x3474f40)
Jul 20 03:56:15 RaspiBolt lnd[1340]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1003 +0xcc
Jul 20 03:56:15 RaspiBolt lnd[1340]: created by go.etcd.io/bbolt.(*DB).freepages
Jul 20 03:56:15 RaspiBolt lnd[1340]:         go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/db.go:1001 +0x108
Jul 20 03:56:15 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 20 03:56:15 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Jul 20 03:56:15 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
```

**Comment by guggero** [comment]
Your `channel.db` file was not written correctly because of the power outage.
The error `panic: freepages: failed to get all reachable pages (page 2205: multiple references)` is well known. We are working on migrating over to `etcd` instead of `bbolt` to mitigate some of these problems.
But powering down any device without giving the processes time to write their memory to disk is always a risk.

In the meantime, try the `compactdb` command of `chantools`: https://github.com/guggero/chantools#compactdb
This will open the corrupted DB in safe mode and try to create a 1:1 copy. If successful you can just replace the old `channel.db` with the copy created by the tool and the node should start again.

**Comment by Cees2daBees** [comment]
Thanks @guggero , I'm always a bit fearful of doing anything with the `channel.db` file and inadvertently broadcasting old state and losing all my funds. Is there any chance of that if I mess something up with your suggestion? I'm not an advanced user, so I'm very reluctant to do things out of the ordinary.

**Comment by Cees2daBees** [comment]
Thanks @guggero, I went to try the chantools but needed to install golang on my machine and seemed like it would be a bit of legwork so I ended up just restoring my node from scratch and recovering the funds with my static channel backup. Thank goodness it worked! Thanks for your time.
