### ISSUE TITLE
lnd segfaults when trying to send payment to htlc.me

### ISSUE THREAD

**Issue by minecraft2048** [lightningnetwork/lnd#464]
I have updated my lnd installation by running this:

```                                                                                                                                                                    feanor@silmaril ~> cd $GOPATH/src/github.com/lightningnetwork/lnd
feanor@silmaril ~/g/s/g/l/lnd> git pull;and glide install
remote: Counting objects: 3, done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/lightningnetwork/lnd
   7a3116f..ce6dee6  master     -> origin/master
Updating 7a3116f..ce6dee6
Fast-forward
 peer.go | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Found desired version locally github.com/aead/chacha20 d31a916ded42d1640b9d89a26f8abd53cc96790c!
some glide output here
[INFO]	Replacing existing vendor dependencies
feanor@silmaril ~/g/s/g/l/lnd> go install . ./cmd/...
```
and I opened up a channel to htlc.me using this address:
`02995ec02804a3ae30e2e0a9bca58bd77af664eeff688d36c8f1ee677fe05b5394@45.63.87.131`
and using this command:
```
feanor@silmaril ~> lncli connect 02995ec02804a3ae30e2e0a9bca58bd77af664eeff688d36c8f1ee677fe05b5394@45.63.87.131
{
    "peer_id": 0
}
feanor@silmaril ~> lncli listpeers
{
    "peers": [
        {
            "pub_key": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134",
            "peer_id": 1,
            "address": "34.250.234.192:9735",
            "bytes_sent": "5728",
            "bytes_recv": "206831",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": true,
            "ping_time": "421914"
        },
        {
            "pub_key": "02995ec02804a3ae30e2e0a9bca58bd77af664eeff688d36c8f1ee677fe05b5394",
            "peer_id": 2,
            "address": "45.63.87.131:9735",
            "bytes_sent": "2167",
            "bytes_recv": "437503",
            "sat_sent": "0",
            "sat_recv": "0",
            "inbound": true,
            "ping_time": "0"
        }
    ]
}
feanor@silmaril ~> lncli openchannel --node_key=02995ec02804a3ae30e2e0a9bca58bd77af664eeff688d36c8f1ee677fe05b5394 --local_amt=100000
{
	"funding_txid": "315fa154eb2d8e22803ad038ed36dd1de26e2119857f120467681fc4c70a8cc8"
}

```
then I verified that the channel is actually open:

```
feanor@silmaril ~> lncli listchannels
{
    "channels": [
        {
            "active": false,
            "remote_pubkey": "02995ec02804a3ae30e2e0a9bca58bd77af664eeff688d36c8f1ee677fe05b5394",
            "channel_point": "315fa154eb2d8e22803ad038ed36dd1de26e2119857f120467681fc4c70a8cc8:0",
            "chan_id": "1378943711890440192",
            "capacity": "100000",
            "local_balance": "91312",
            "remote_balance": "0",
            "commit_fee": "8688",
            "commit_weight": "600",
            "fee_per_kw": "12000",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "0",
            "pending_htlcs": [
            ],
            "csv_delay": 4
        }
    ]
}
```
then when I try to send 100 satoshi to htlc.me this happened:

```
feanor@silmaril ~> lncli sendpayment --pay_req=lntb1u1pdznhuxpp5gtcvwna0rf0w9jllefpjdyngk94cx6gltptp89pz5ka58l53fu4sdz40v3xwetwv4exjc6ld9jzyw3zxq6rsd3cxcmkztfsxsexztf58yurgttpvgcrstfkxa3kgvryxyenjd3nvv386cqzys9a7gazuqvqf86wd652389zerwnq8gcn6zpmlmgjhge2l3t9am7dx0ertmp65ylxqy6h7654uja3997a7k5c2r2f4a28lgsannht09ugpvlk8fc
[lncli] rpc error: code = Unavailable desc = transport is closing
```
```
2017-12-08 11:49:20.681 [DBG] BTCN: Received cfilter from 159.203.125.125:18333 (outbound)
2017-12-08 11:49:20.949 [DBG] BTCN: Sending getcfilter to 159.203.125.125:18333 (outbound)
2017-12-08 11:49:21.213 [DBG] BTCN: Received cfilter from 159.203.125.125:18333 (outbound)
2017-12-08 11:49:21.489 [DBG] BTCN: Sending getcfilter to 159.203.125.125:18333 (outbound)
2017-12-08 11:49:21.818 [DBG] BTCN: Received cfilter from 159.203.125.125:18333 (outbound)
2017-12-08 11:49:22.116 [DBG] BTCN: Sending getcfilter to 159.203.125.125:18333 (outbound)
2017-12-08 11:49:22.432 [DBG] BTCN: Received cfilter from 159.203.125.125:18333 (outbound)
2017-12-08 11:49:22.751 [DBG] BTCN: Sending getcfilter to 159.203.125.125:18333 (outbound)
2017-12-08 11:49:23.015 [DBG] BTCN: Received cfilter from 159.203.125.125:18333 (outbound)
2017-12-08 11:49:23.325 [DBG] BTCN: Sending getcfilter to 159.203.125.125:18333 (outbound)
2017-12-08 11:49:23.632 [DBG] BTCN: Received cfilter from 159.203.125.125:18333 (outbound)
2017-12-08 11:49:23.707 [DBG] CRTR: Mission Control returning prune view of 0 edges, 0 vertexes
2017-12-08 11:49:23.713 [DBG] PEER: Sending UpdateAddHTLC(chan_id=c88c0ac7c41f686704127f8519216ee21ddd36ed38d03a80228e2deb54a15f31, id=0, amt=100000 mSAT, expiry=1254287, hash=42f0c74faf1a5ee2cbffca43269268b16b83691f5856139422a5bb43fe914f2b) to 45.63.87.131:9735
2017-12-08 11:49:23.760 [INF] HSWC: ChannelLink(315fa154eb2d8e22803ad038ed36dd1de26e2119857f120467681fc4c70a8cc8:0) has exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x612869]

goroutine 171 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec.(*PublicKey).SerializeCompressed(0x0, 0xc421142700, 0x0, 0x1)
	/home/feanor/go/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec/pubkey.go:146 +0x69
github.com/lightningnetwork/lnd/lnwallet.SingleTweakBytes(0x0, 0xc420743aa0, 0x1, 0x30, 0x140000000028)
	/home/feanor/go/src/github.com/lightningnetwork/lnd/lnwallet/script_utils.go:1045 +0x47
github.com/lightningnetwork/lnd/lnwallet.deriveCommitmentKeys(0x0, 0x0, 0xc420099480, 0xc4200994d8, 0x0)
	/home/feanor/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:825 +0x51
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc4200b0420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/feanor/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2958 +0x1c9
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc42010e1e0, 0x4, 0x0)
	/home/feanor/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:985 +0x44
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc42010e1e0)
	/home/feanor/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:555 +0x55e
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
	/home/feanor/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:267 +0x126
feanor@silmaril ~> 
```

**Comment by Roasbeef** [comment]
Thanks for the bug report! There was a slight logic error in a prior commit which I've spotted. The fix should be pushed out shortly. Additionally, I tracked down another `neutrino` related bug and fixed it as well in the process.
