### ISSUE TITLE
crash sending fee update for channel without `RemoteNextRevocation`

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lnd#470]
`lnd` can crash trying to send a fee update for a channel where the `RemoteNextRevocation` is not yet set:

```
2017-12-09 13:45:33.064 [INF] NTFN: New block: height=1254296, sha=00000000000003407d334f361e42fefc6cbd7e748fd863fbf41943b160b9c58d
2017-12-09 13:45:33.065 [INF] HSWC: ChannelPoint(6c6ae627c59f4e2467cf68e843418428934238df70b9be5b8e11a91cd5b49cc2:0): updating commit fee to 0.00019 BTC sat/kw
2017-12-09 13:45:33.075 [INF] HSWC: ChannelLink(6c6ae627c59f4e2467cf68e843418428934238df70b9be5b8e11a91cd5b49cc2:0) has exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x61aad0]

goroutine 17916 [running]:
2017-12-09 13:45:33.078 [INF] CRTR: Block 00000000000003407d334f361e42fefc6cbd7e748fd863fbf41943b160b9c58d (height=1254296) closed 0 channels
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec.(*PublicKey).SerializeCompressed(0x0, 0xc04205a680, 0xc042401c20, 0x6900000074)
        D:/dev/go/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec/pubkey.go:146 +0x70
github.com/lightningnetwork/lnd/lnwallet.SingleTweakBytes(0x0, 0xc042b1eee0, 0x0, 0xffffffffffffffff, 0x0)
        D:/dev/go/src/github.com/lightningnetwork/lnd/lnwallet/script_utils.go:1045 +0x4e
github.com/lightningnetwork/lnd/lnwallet.deriveCommitmentKeys(0x0, 0x0, 0xc042e7c080, 0xc042e7c0d8, 0x0)
        D:/dev/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:826 +0x58
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).SignNextCommitment(0xc0420dc6e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/dev/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2959 +0x1dc
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateCommitTx(0xc04267e000, 0x14b7940, 0xc042401b90)
        D:/dev/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:985 +0x4b
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).updateChannelFee(0xc04267e000, 0x4a38, 0x0, 0x0)
        D:/dev/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:1149 +0x23f
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc04267e000)
        D:/dev/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:491 +0x4fe
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start
        D:/dev/go/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:267 +0x132
```

We must make sure fee updates are sent only if the link is `EligibleToForward`, as introduced here: https://github.com/lightningnetwork/lnd/pull/457/commits/36956d390fa77906cffb91eea50ac39403aad35e

**Comment by Roasbeef** [comment]
Was closed due to #471.
