### ISSUE TITLE
gomobile (android) crash: runtime: out of memory

### ISSUE THREAD

**Issue by Overtorment** [lightningnetwork/lnd#5091]
### Background

Sometimes compiled AAR starts crashing randomly on my android emulator. I usually fix it via going to "avd manager" on android studio and clicking "wipe data".  not sure if the problem is in ram or in disk storage.
Log file attached.
[lnd-crash-log.txt](https://github.com/lightningnetwork/lnd/files/6118087/lnd-crash-log.txt)
see around

```
03-10 18:24:34.408  5331  5560 I GoLog   : 2021-03-10 18:24:34.408 [INF] LNWL: Opened wallet
03-10 18:24:34.646  5331  5570 V ReactNativeLND: lnd inited ===========================================================================
03-10 18:24:34.648  5331  5573 I GoLog   : 2021-03-10 18:24:34.648 [INF] CHRE: Primary chain is set to: bitcoin
03-10 18:24:34.660  5331  5573 I GoLog   : 2021-03-10 18:24:34.660 [INF] CHRE: Using external fee estimator https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json: cached=true
03-10 18:24:34.660  5331  5573 I GoLog   : 2021-03-10 18:24:34.660 [INF] LNWL: Starting web API fee estimator
03-10 18:24:34.761  5331  5570 V ReactNativeLND: resp: admin_macaroon: "\002\001\003lnd\002\370\001\003\n\020\0328m:\224Y\222T\263\250\364r\206\333\244\305\022\0010\032\026\n\aaddress\022\004read\022\005write\032\023\n\004info\022\004read\022\005write\032\027\n\binvoices\022\004read\022\005write\032!\n\bmacaroon\022\bgenerate\022\004read\022\005write\032\026\n\amessage\022\004read\022\005write\032\027\n\boffchain\022\004read\022\005write\032\026\n\aonchain\022\004read\022\005write\032\024\n\005peers\022\004read\022\005write\032\030\n\006signer\022\bgenerate\022\004read\000\000\006 \376I\005\210\025\343\0065\377\304i\345\336\305t\220\235\230\032\357$\377&-\236\272\347{Y\305\273\326"
03-10 18:24:34.811  1795  2251 E GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
03-10 18:24:34.811  1795  2251 E GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
03-10 18:24:34.878  1777  5581 E ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
03-10 18:24:35.361  5331     0 E Go      : runtime: out of memory: cannot allocate 268435456-byte block (657489920 in use)
03-10 18:24:35.361  5331     0 E Go      : fatal error: out of memory
03-10 18:24:35.361  5331  5565 E GoLog   : runtime: out of memory: cannot allocate 268435456-byte block (657489920 in use)
03-10 18:24:35.363  5331     0 E Go      : 
03-10 18:24:35.363  5331     0 E Go      : runtime stack:
03-10 18:24:35.363  5331     0 E Go      : runtime.throw(0xa68db177, 0xd)
03-10 18:24:35.363  5331     0 E Go      : 	/usr/local/go/src/runtime/panic.go:1116 +0x70
03-10 18:24:35.363  5331     0 E Go      : runtime.largeAlloc(0x10000000, 0x101, 0x1000004)
03-10 18:24:35.363  5331     0 E Go      : 	/usr/local/go/src/runtime/malloc.go:1179 +0x17b
03-10 18:24:35.363  5331     0 E Go      : runtime.mallocgc.func1()
03-10 18:24:35.363  5331     0 E Go      : 	/usr/local/go/src/runtime/malloc.go:1071 +0x3a
03-10 18:24:35.363  5331     0 E Go      : runtime.systemstack(0xf3f8a37b)
03-10 18:24:35.363  5331     0 E Go      : 	/usr/local/go/src/runtime/asm_386.s:391 +0x62
03-10 18:24:35.363  5331     0 E Go      : runtime.mstart()
03-10 18:24:35.363  5331     0 E Go      : 	/usr/local/go/src/runtime/proc.go:1116
03-10 18:24:35.363  5331     0 E Go      : 
03-10 18:24:35.363  5331     0 E Go      : goroutine 461 [running]:
03-10 18:24:35.363  5331     0 E Go      : runtime.systemstack_switch()
```

### Your environment

* `0.12.0-beta.rc6-dirty`
* android emu (x86)
* neutrino
* any other relevant environment details:

launch arguments I use:

```
    const defaultArguments =
      '--sync-freelist --tlsdisableautofill  --maxpendingchannels=1000 ' + // --debuglevel=debug
      '--minchansize=1000000 --ignore-historical-gossip-filters ' + // --rejecthtlc
      '--bitcoin.active --bitcoin.mainnet --bitcoin.defaultchanconfs=1 --routing.assumechanvalid ' +
      '--protocol.wumbo-channels --rpclisten=127.0.0.1 --norest --nolisten ' +
      '--maxbackoff=5s --connectiontimeout=20s' + // --enable-upfront-shutdown
      '--bitcoin.node=neutrino --neutrino.addpeer=btcd-mainnet.lightning.computer --neutrino.maxpeers=10 ' +
      '--neutrino.assertfilterheader=660000:08312375fabc082b17fa8ee88443feb350c19a34bb7483f94f7478fa4ad33032 ' +
      '--neutrino.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json  --numgraphsyncpeers=3 ' +
      '--bitcoin.basefee=100000 --bitcoin.feerate=10000 ';
```

### Steps to reproduce

Occurs randomly, but in general, after some wear'n'tear of the emulator, when there's a bunch of other test apks installed

**Comment by halseth** [comment]
How much RAM do you allocate to the emulator?

**Comment by halseth** [comment]
you can set up profiling when launching lnd, which lets you do memory dumps while it's running to see what's going on.

**Comment by Roasbeef** [comment]
Closing due to inactivity.
