### ISSUE TITLE
Segmentation Violations on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#510]
I've been experimenting on Windows Subsystem for Linux on my Windows 10 laptop. Here's what I have installed along with the latest code from btcd/roasbeef and lnd:

`go version go1.8.3 linux/amd64`
`Ubuntu 16.04.3 LTS`

On running `lnd` in neutrino mode, it crashes almost immediately with a segfault. The stack traces are long so I've put them into gists, here's an example using neutrino https://gist.github.com/sangaman/6612ee3f7bd75d92030ae8b4c2708555.

If I run against a fully synced btcd testnet instance, it seems to run fine as long as I don't have any peers. Within seconds of adding a peer amidst a flood of channel update and announcement messages, I get another segfault. Here's an example coming shortly after I manually added a peer https://gist.github.com/sangaman/0e70bca85dc92c5f2ea2f3409f353a73 failing on a ChannelUpdate. Here's another example shortly after starting lnd with `--autopilot.active` and a balance in my wallet failing on ChannelAnnouncement https://gist.github.com/sangaman/8d1bb3dd01923ad24d641591c764e93b.

**Comment by halseth** [comment]
Looks like database errors. Don't know much about "Linux on Windows", but maybe there are some special file system access privileges you don't have?

**Comment by sangaman** [comment]
I'm no WSL expert either... btcd synced the testnet blockchain without issue which I'd expect to be much heavier on I/O and database activity. I found some similar errors people searching online but nothing in the way of a clear solution or what causes it. I'm guessing it may be related to incoming connections, I synced btcd without being reachable but maybe I'll try forwarding port 18333 and see if that causes an error.

**Comment by sangaman** [comment]
Interestingly, I've been trying this some more this evening and it seems to be working fine now. The only thing I did differently was set `--externalip` and forward the 9735 port to my laptop (which doesn't seem to be working because it's still not accepting incoming connections but that's a separate issue). I've had lnd running for several hours with multiple peers and an open channel, no problems. I'll keep this issue updated.

**Comment by Roasbeef** [comment]
Hmm, all those traces point to issues with `bolt` running on WSL. `btcd` would be unaffected as it uses `leveldb` which doesn't seem to run into this particular edge case. 

Tracing down the point of panic, it looks like it's failing the following check: 
https://github.com/golang/go/blob/master/src/runtime/signal_unix.go#L297

**Comment by Roasbeef** [comment]
Looks like this was also filed as an issue on the OG bolt repo: https://github.com/boltdb/bolt/issues/702

**Comment by Roasbeef** [comment]
Which then lead to a fix: https://github.com/Microsoft/WSL/issues/2304

Perhaps try to update your version of WSL?

**Comment by sangaman** [comment]
Interesting. I believe I am on the latest version, I keep Windows updated and I've done the Fall Creators update - I actually came across that same bolt#702 issue as you but discounted it because I figured I'm up to date. I only installed WSL and the Ubuntu app within the past couple of days and one of the first things I did was updating/upgrading all the packages.

On the bright side, LND has been running stable on WSL since last night and I'm currently connected to a bunch of channels. If it comes back it might be worth taking it up wth the WSL project directly if the problem comes back and nothing is apparently wrong with the relevant LND code.

**Comment by Roasbeef** [comment]
Yeh seems like they don't yet emmulate the behavior of `mmap` with full fidelity yet.

**Comment by sangaman** [comment]
This has been running stably for me for days, even throwing lots of payments and channels at it. Anyone reading this who wants to run lnd on windows can give it a shot, it'd be interesting to see if these segfaults appear at all. I'll probably try on another windows machine myself at some point.

**Comment by Roasbeef** [comment]
Closing this for now as the issue seems to have resolved itself.

**Comment by sangaman** [comment]
I'm seeing segmentation violations everytime I run `go test` from the main directory on WSL, looks like the same error each time. I've updated to the latest before trying these tests, and I've confirmed I don't get them on regular Debian machines.

```bash
$ go test
unexpected fault address 0x7f9f646c8008
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f9f646c8008 pc=0x5545e9]

goroutine 118 [running]:
runtime.throw(0xd93cd3, 0x5)
        /usr/lib/go-1.8/src/runtime/panic.go:596 +0x95 fp=0xc4201a07b8 sp=0xc4201a0798
runtime.sigpanic()
        /usr/lib/go-1.8/src/runtime/signal_unix.go:297 +0x28c fp=0xc4201a0808 sp=0xc4201a07b8
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc4201a09b8, 0x1312fa0, 0x10, 0x10, 0x8)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/cursor.go:255 +0x69 fp=0xc4201a08d0 sp=0xc4201a0808
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc4201a09b8, 0x1312fa0, 0x10, 0x10, 0x0, 0x0, 0x8, 0x18, 0xc420200900, 0x0, ...)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/cursor.go:159 +0xb1 fp=0xc4201a0920 sp=0xc4201a08d0
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc42022d198, 0x1312fa0, 0x10, 0x10, 0x0, 0x0, 0xc420452400)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/bucket.go:172 +0x124 fp=0xc4201a0a20 sp=0xc4201a0920
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc42022d198, 0x1312fa0, 0x10, 0x10, 0xc92c60, 0xc420463501, 0xc420200920)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/bucket.go:206 +0x4d fp=0xc4201a0a80 sp=0xc4201a0a20
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(0xc42022d180, 0x1312fa0, 0x10, 0x10, 0xc4201a0b30, 0x42babf, 0xef0da0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/tx.go:115 +0x4f fp=0xc4201a0ac8 sp=0xc4201a0a80
github.com/lightningnetwork/lnd/channeldb.updateChanBucket(0xc42022d180, 0xc4204ecb70, 0xc4200891a4, 0x719526f8d77f4943, 0xaec3ced90fa3f408, 0xad0ee984209779ba, 0x933ea01, 0xc400000008, 0xc420268340, 0x556a88)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:410 +0x88 fp=0xc4201a0b30 sp=0xc4201a0ac8
github.com/lightningnetwork/lnd/channeldb.(*OpenChannel).MarkAsOpen.func1(0xc42022d180, 0xeef028, 0xc42022d180)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:513 +0x80 fp=0xc4201a0bb0 sp=0xc4201a0b30
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4204b6780, 0xc4201a0c28, 0x0, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/db.go:598 +0x9f fp=0xc4201a0c00 sp=0xc4201a0bb0
github.com/lightningnetwork/lnd/channeldb.(*OpenChannel).MarkAsOpen(0xc420089180, 0x0, 0x0, 0x0, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:527 +0xd2 fp=0xc4201a0c58 sp=0xc4201a0c00
github.com/lightningnetwork/lnd.(*fundingManager).waitForFundingConfirmation(0xc4202c2300, 0xc420089180, 0xc42018fd40, 0xc42018fce0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1581 +0x703 fp=0xc4201a0f90 sp=0xc4201a0c58
github.com/lightningnetwork/lnd.(*fundingManager).handleFundingSigned.func1.1(0xc4202c2300, 0xc420089180, 0xc42018fd40, 0xc42018fce0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1361 +0x7c fp=0xc4201a0fc0 sp=0xc4201a0f90
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4201a0fc8 sp=0xc4201a0fc0
created by github.com/lightningnetwork/lnd.(*fundingManager).handleFundingSigned.func1
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1362 +0x122

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4204f8410, 0xdaeb7d, 0x21, 0xeeed68, 0xc42040fd01)
        /usr/lib/go-1.8/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc4204f8410)
        /usr/lib/go-1.8/src/testing/testing.go:882 +0x67
testing.tRunner(0xc4204f8410, 0xc42040fde0)
        /usr/lib/go-1.8/src/testing/testing.go:657 +0x96
testing.runTests(0xc4204eed00, 0x135f840, 0x19, 0x19, 0xaec3ced90fa3f408)
        /usr/lib/go-1.8/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc420177f20, 0xc42040ff20)
        /usr/lib/go-1.8/src/testing/testing.go:822 +0xfc
main.main()
        github.com/lightningnetwork/lnd/_test/_testmain.go:90 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 73 [select]:
github.com/lightningnetwork/lnd.(*fundingManager).reservationCoordinator(0xc4202c2300)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:691 +0x5aa
created by github.com/lightningnetwork/lnd.(*fundingManager).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:544 +0xe2e

goroutine 18 [syscall]:
os/signal.signal_recv(0x1e42925011c1191)
        /usr/lib/go-1.8/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/lib/go-1.8/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/lib/go-1.8/src/os/signal/signal_unix.go:28 +0x41

goroutine 71 [sleep]:
time.Sleep(0x1dcd6500)
        /usr/lib/go-1.8/src/runtime/time.go:59 +0xf9
github.com/lightningnetwork/lnd.assertDatabaseState(0xc420206820, 0xc4201d1980, 0xc4226407b0, 0xc420506100)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager_test.go:576 +0x3a4
github.com/lightningnetwork/lnd.assertMarkedOpen(0xc420206820, 0xc4201d1980, 0xc4202ec1e0, 0xc4226407b0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager_test.go:602 +0x44
github.com/lightningnetwork/lnd.TestFundingManagerRestartBehavior(0xc420206820)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager_test.go:897 +0x232
testing.tRunner(0xc420206820, 0xeeed68)
        /usr/lib/go-1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
        /usr/lib/go-1.8/src/testing/testing.go:697 +0x2ca

goroutine 13 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d25a0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 35 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228410)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 36 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228410)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 37 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228410)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 38 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228410)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 40 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228be0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 41 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228be0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 42 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228be0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 43 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420228be0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 12 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d25a0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 14 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d25a0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 15 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d25a0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 50 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2d70)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 51 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2d70)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 52 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2d70)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 53 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2d70)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 76 [select]:
github.com/lightningnetwork/lnd.(*fundingManager).handleFundingCreated.func2(0xc4202c2500, 0xc420089400, 0xc4205060a0, 0xc4204ecb10, 0xc4206a1990)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1232 +0x3c1
created by github.com/lightningnetwork/lnd.(*fundingManager).handleFundingCreated
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1261 +0x1218

goroutine 75 [select]:
github.com/lightningnetwork/lnd.(*fundingManager).reservationCoordinator(0xc4202c2500)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:691 +0x5aa
created by github.com/lightningnetwork/lnd.(*fundingManager).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:544 +0xe2e

goroutine 74 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).requestHandler(0xc420088f00)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:410 +0x401
created by github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).Startup
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:339 +0x167

goroutine 83 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).requestHandler(0xc4200ac500)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:410 +0x401
created by github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).Startup
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:339 +0x167

goroutine 85 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).requestHandler(0xc4200aca00)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:410 +0x401
created by github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).Startup
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:339 +0x167

goroutine 72 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).requestHandler(0xc420088c80)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:410 +0x401
created by github.com/lightningnetwork/lnd/lnwallet.(*LightningWallet).Startup
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/wallet.go:339 +0x167

goroutine 117 [select]:
github.com/lightningnetwork/lnd.(*fundingManager).handleFundingSigned.func1(0xc4202c2300, 0xc420089180, 0xc4201e0f90, 0xc4200891a4, 0xc4204ecb70, 0xc4201b0b00)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1366 +0xbee
created by github.com/lightningnetwork/lnd.(*fundingManager).handleFundingSigned
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1434 +0xc64

goroutine 49 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2690)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 114 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2690)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 115 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2690)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 116 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc4201d2690)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 101 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420275bd0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 102 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420275bd0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 103 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420275bd0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 104 [select]:
github.com/lightningnetwork/lnd/lnwallet.(*sigPool).poolWorker(0xc420275bd0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:176 +0xb9a
created by github.com/lightningnetwork/lnd/lnwallet.(*sigPool).Start
        /home/dm/go/src/github.com/lightningnetwork/lnd/lnwallet/sigpool.go:149 +0x80

goroutine 77 [select]:
github.com/lightningnetwork/lnd.(*fundingManager).waitForFundingWithTimeout(0xc4202c2500, 0xc420089400, 0xc42263c5a0, 0xc42263c600)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1470 +0x54b
created by github.com/lightningnetwork/lnd.(*fundingManager).handleFundingCreated.func2
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1228 +0xef

goroutine 78 [runnable]:
math/big.nat.montgomery(0xc4201aec80, 0x4, 0x10, 0xc42264d960, 0x4, 0xe, 0xc42264d960, 0x4, 0xe, 0xc42001d3e0, ...)
        /usr/lib/go-1.8/src/math/big/nat.go:211 +0x3cd
math/big.nat.expNNMontgomery(0xc4201aec80, 0x4, 0x10, 0xc4201aec00, 0x4, 0x11, 0xc420015b40, 0x4, 0x8, 0xc42001d3e0, ...)
        /usr/lib/go-1.8/src/math/big/nat.go:1153 +0x9a0
math/big.nat.expNN(0x0, 0x0, 0x0, 0xc4201aec00, 0xc, 0x10, 0xc420015b40, 0x4, 0x8, 0xc42001d3e0, ...)
        /usr/lib/go-1.8/src/math/big/nat.go:965 +0x9fc
math/big.(*Int).Exp(0xc422668520, 0xc4202cd5d0, 0xc42000d7e0, 0xc42000d6a0, 0x0)
        /usr/lib/go-1.8/src/math/big/int.go:423 +0xf6
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec.decompressPoint(0x136b4c0, 0xc422668500, 0x0, 0x20, 0xc422668500, 0x21)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec/pubkey.go:40 +0xeb
github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec.ParsePubKey(0xc42021b950, 0x21, 0x21, 0x136b4c0, 0x21, 0x21, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/btcec/pubkey.go:103 +0x1ac
github.com/lightningnetwork/lnd/channeldb.readElement(0x1314ac0, 0xc42021b260, 0xbede60, 0xc4202d3520, 0x0, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/codec.go:233 +0x1fc
github.com/lightningnetwork/lnd/channeldb.readElements(0x1314ac0, 0xc42021b260, 0xc4202cd8a8, 0xb, 0xb, 0x0, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/codec.go:311 +0x65
github.com/lightningnetwork/lnd/channeldb.fetchChanInfo.func1(0x1314ac0, 0xc42021b260, 0xc4202d34d8, 0x0, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:1603 +0x16b
github.com/lightningnetwork/lnd/channeldb.fetchChanInfo(0xc4201aba00, 0xc4202d3400, 0x68dd90, 0xc4201ab9c0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:1608 +0x323
github.com/lightningnetwork/lnd/channeldb.fetchOpenChannel(0xc4201aba00, 0xc420089424, 0xc420089424, 0x719526f8d77f4943, 0xaec3ced90fa3f408)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:596 +0x7b
github.com/lightningnetwork/lnd/channeldb.(*OpenChannel).MarkAsOpen.func1(0xc42018cfc0, 0xeef028, 0xc42018cfc0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:518 +0xb0
github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4204b6f00, 0xc42019fc28, 0x0, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/vendor/github.com/boltdb/bolt/db.go:598 +0x9f
github.com/lightningnetwork/lnd/channeldb.(*OpenChannel).MarkAsOpen(0xc420089400, 0x0, 0x0, 0x0, 0x0)
        /home/dm/go/src/github.com/lightningnetwork/lnd/channeldb/channel.go:527 +0xd2
github.com/lightningnetwork/lnd.(*fundingManager).waitForFundingConfirmation(0xc4202c2500, 0xc420089400, 0xc42263c6c0, 0xc42263c660)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1581 +0x703
github.com/lightningnetwork/lnd.(*fundingManager).waitForFundingWithTimeout.func1(0xc4202c2500, 0xc420089400, 0xc42263c6c0, 0xc42263c660)
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1464 +0x7c
created by github.com/lightningnetwork/lnd.(*fundingManager).waitForFundingWithTimeout
        /home/dm/go/src/github.com/lightningnetwork/lnd/fundingmanager.go:1465 +0x13c
exit status 2
FAIL    github.com/lightningnetwork/lnd 3.800s
```

**Comment by sangaman** [comment]
@Roasbeef I'm getting more segfaults on initial sync after updating to the latest from master and cleaning out the lnd directory on a WSL node. If you think it's worth reopening this I can try to help debug these.
