### ISSUE TITLE
// comment in proto file breaks node-grpc's TypeScript definition generator

### ISSUE THREAD

**Issue by AaronDewes** [lightningnetwork/lnd#5546]
This comment

https://github.com/lightningnetwork/lnd/blob/306da010d89a35d29b5a6acc42cfed6dae8685c3/lnrpc/rpc.proto#L152

breaks `proto-loader-gen-types` when generating types. It seems like // comments aren't valid in proto files. Can this TODO either be done (@Roasbeef) or moved to a different place to avoid this issue? Or should I try submitting a bug report to grpc?

Here's the error:

```
Error: illegal token 'PendingChannels' (resources/rpc.proto, line 153)
    at illegal (/home/pi/middleware/node_modules/protobufjs/src/parse.js:96:16)
    at parseService_block (/home/pi/middleware/node_modules/protobufjs/src/parse.js:660:23)
    at ifBlock (/home/pi/middleware/node_modules/protobufjs/src/parse.js:290:17)
    at parseService (/home/pi/middleware/node_modules/protobufjs/src/parse.js:652:9)
    at parseCommon (/home/pi/middleware/node_modules/protobufjs/src/parse.js:269:17)
    at parse (/home/pi/middleware/node_modules/protobufjs/src/parse.js:790:21)
    at process (/home/pi/middleware/node_modules/protobufjs/src/root.js:127:30)
    at /home/pi/middleware/node_modules/protobufjs/src/root.js:194:17
    at fetchReadFileCallback (/home/pi/middleware/node_modules/@protobufjs/fetch/index.js:51:19)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by guggero** [comment]
There are many `//` comments in the proto files. And they are perfectly legal too: https://developers.google.com/protocol-buffers/docs/proto#adding_comments

Maybe this particular library stumbles over the TODO somehow? Is there a specific reason why you use the `protobufjs` library and not the recommended [`@grpc/proto-loader`](https://github.com/lightningnetwork/lnd/blob/master/docs/grpc/javascript.md) one?

**Comment by AaronDewes** [comment]
I'm using the recommended one and generating types like this: `proto-loader-gen-types --longs String --defaults -O lnd --grpcLib=@grpc/grpc-js resources/rpc.proto resources/walletunlocker.proto resources/stateservice.proto` which is the recommended way, but it seems to use protbufjs internally.

**Comment by Roasbeef** [comment]
Unable to repro this on our end, we use typscript for Lightning Terminal, here's how we generate the protos: https://github.com/lightninglabs/lightning-terminal/blob/b5d4e17b567378c5149465577f8b4224ec89fe45/proto/gen_protos_docker.sh

**Comment by heanzyzabala** [comment]
This issue happens to me to. Anyone with the same issue should just delete the TODO comment.
