### ISSUE TITLE
itest-parallel panics 

### ISSUE THREAD

**Issue by naveensrinivasan** [lightningnetwork/lnd#5806]
### Background
Running tests on `go` `1.16` consistently fails `GOOS=linux make itest-parallel backend=bitcoind tranches=2 parallel=4`
```
lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('
CPU(s):                          8
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
```
```
GOOS=linux make itest-parallel backend=bitcoind tranches=2 parallel=4
 Building itest btcd and lnd.
CGO_ENABLED=0 GO111MODULE=on go build -v -tags="rpctest" -o lntest/itest/btcd-itest -ldflags " -X github.com/lightningnetwork/lnd/build.Commit=kvdb/v1.1.0-33-g3385d384 -X github.com/lightningnetwork/lnd/build.CommitHash=3385d3841436a840c2695ba064c10af9e275c032 -X github.com/lightningnetwork/lnd/build.GoVersion=go1.16.4 -X github.com/lightningnetwork/lnd/build.RawTags=dev,autopilotrpc,chainrpc,invoicesrpc,routerrpc,signrpc,verrpc,walletrpc,watchtowerrpc,wtclientrpc,rpctest,bitcoind" github.com/btcsuite/btcd
CGO_ENABLED=0 GO111MODULE=on go build -v -tags="dev autopilotrpc chainrpc invoicesrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc rpctest bitcoind" -o lntest/itest/lnd-itest -ldflags " -X github.com/lightningnetwork/lnd/build.Commit=kvdb/v1.1.0-33-g3385d384 -X github.com/lightningnetwork/lnd/build.CommitHash=3385d3841436a840c2695ba064c10af9e275c032 -X github.com/lightningnetwork/lnd/build.GoVersion=go1.16.4 -X github.com/lightningnetwork/lnd/build.RawTags=dev,autopilotrpc,chainrpc,invoicesrpc,routerrpc,signrpc,verrpc,walletrpc,watchtowerrpc,wtclientrpc,rpctest,bitcoind" github.com/lightningnetwork/lnd/cmd/lnd
 Building itest binary for bitcoind backend.
CGO_ENABLED=0 GO111MODULE=on go test  -v ./lntest/itest -tags="dev autopilotrpc chainrpc invoicesrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc rpctest bitcoind" -c -o lntest/itest/itest.test
 Running tests
rm -rf lntest/itest/*.log lntest/itest/.logs-*; date
Wed Sep 29 14:37:11 UTC 2021
EXEC_SUFFIX= echo "$(seq 0 $(expr 4 - 1))" | xargs -P 4 -n 1 -I {} scripts/itest_part.sh {} 2  -test.timeout=60m
/root/lnd/lntest/itest/itest.test -test.v -test.timeout=60m -logoutput -goroutinedump -logdir=.logs-tranche0 -lndexec=/root/lnd/lntest/itest/lnd-itest -btcdexec=/root/lnd/lntest/itest/btcd-itest -splittranches=2 -runtranche=0
/root/lnd/lntest/itest/itest.test -test.v -test.timeout=60m -logoutput -goroutinedump -logdir=.logs-tranche1 -lndexec=/root/lnd/lntest/itest/lnd-itest -btcdexec=/root/lnd/lntest/itest/btcd-itest -splittranches=2 -runtranche=1
/root/lnd/lntest/itest/itest.test -test.v -test.timeout=60m -logoutput -goroutinedump -logdir=.logs-tranche2 -lndexec=/root/lnd/lntest/itest/lnd-itest -btcdexec=/root/lnd/lntest/itest/btcd-itest -splittranches=2 -runtranche=2
/root/lnd/lntest/itest/itest.test -test.v -test.timeout=60m -logoutput -goroutinedump -logdir=.logs-tranche3 -lndexec=/root/lnd/lntest/itest/lnd-itest -btcdexec=/root/lnd/lntest/itest/btcd-itest -splittranches=2 -runtranche=3
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon
--- FAIL: TestLightningNetworkDaemon (0.00s)
panic: runtime error: slice bounds out of range [126:85] [recovered]
	panic: runtime error: slice bounds out of range [126:85]

goroutine 10 [running]:
testing.tRunner.func1.2(0x13d3e60, 0xc0001e0b58)
	/usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc00008ac00)
	/usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0x13d3e60, 0xc0001e0b58)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/lightningnetwork/lnd/lntest/itest.getTestCaseSplitTranche(0x17520e8, 0xc00008ac00, 0x0, 0x0, 0x0)
	/root/lnd/lntest/itest/lnd_test.go:81 +0xf7
github.com/lightningnetwork/lnd/lntest/itest.TestLightningNetworkDaemon(0xc00008ac00)
	/root/lnd/lntest/itest/lnd_test.go:95 +0xf6
testing.tRunner(0xc00008ac00, 0x160d050)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
xargs: scripts/itest_part.sh: exited with status 255; aborting
make: *** [Makefile:215: itest-parallel] Error 124
```
```
uname -a
Linux lnd-tear-down 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

``` master
git rev-parse HEAD
3385d3841436a840c2695ba064c10af9e275c032
```

**Comment by guggero** [comment]
That's kind of expected (even if perhaps not documented). The `tranches` variable either needs to be set to `1` (useful when used in combination with `icase=` to run the same test case multiple times in parallel) or to the same value as `parallel` (default=4).
Any other case will lead to this error.

**Comment by naveensrinivasan** [comment]
Sounds good. Thanks
