### ISSUE TITLE
lnd crashes with "concurrent map writes"

### ISSUE THREAD

**Issue by ogunden** [lightningnetwork/lnd#5864]
### Background

lnd crashes with "concurrent map writes", every few times I run it. Other observations:
* it seems to happen shortly after startup. If I get past a minute or so of runtime, then it's stable and never crashes.
* It seems correlated to when I start thunderhub and connect to the web interface
* Each time it has happened, I have noticed the top stack trace has been related to btcsuite/btcwallet/waddrmgr
* The first time it happened was right after upgrading to 0.13.3. I was previously running 0.13.1 in this same environment with no issues.

### Your environment

*     "version": "0.13.3-beta commit=v0.13.3-beta", "commit_hash": "4f567577db9d85b6f392f960b3aabddcad3cd02c",
* `Linux 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Bitcoin Core version v0.21.1
* lnd compiled at tag v0.13.3-beta with `make tags="autopilotrpc signrpc walletrpc chainrpc invoicesrpc routerrpc" install`

### Steps to reproduce (it's a heisenbug -- this only reproduces the crash some of the time):
1. start lnd
2. lncli unlock
3. start thunderhub
4. navigate to thunderhub web interface
5. observe that lnd has crashed

### Stack trace

[crash.txt](https://github.com/lightningnetwork/lnd/files/7353070/crash.txt)

**Comment by ogunden** [comment]
> Can you link to a pastebin or something? I personally don't download random files from the internet

It's 2 megs, not sure if pastebin is going to be any more helpful. FWIW, I used github's supported mechanism for uploading files. Plus, it's text/plain so it's hard to imagine it hurting your box as long as you don't chmod +x it. 

Here's a bit of a larger excerpt. (Are we fairly confident that none of these frame pointers etc can be used to somehow compromise my keys?)

```
fatal error: concurrent map writes

goroutine 13935 [running]:
runtime.throw({0x12ea2b3, 0xc031c61380})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc008d4cfa8 sp=0xc008d4cf78 pc=0x436f31
runtime.mapassign_fast32(0xc00126e300, 0xc031df3560, 0x0)
        /usr/local/go/src/runtime/map_fast32.go:101 +0x2c5 fp=0xc008d4cfe0 sp=0xc008d4cfa8 pc=0x412345
github.com/btcsuite/btcwallet/waddrmgr.(*ScopedKeyManager).loadAccountInfo(0xc00126e300, {0x7f264d73fa10, 0xc031da3e00}, 0x0)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/waddrmgr/scoped_manager.go:512 +0x739 fp=0xc008d4d120 sp=0xc008d4cfe0 pc=0x75d819
github.com/btcsuite/btcwallet/waddrmgr.(*ScopedKeyManager).AccountProperties(0xc00126e300, {0x7f264d73fa10, 0xc031da3e00}, 0x0)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/waddrmgr/scoped_manager.go:541 +0x106 fp=0xc008d4d1c0 sp=0xc008d4d120 pc=0x75dbe6
github.com/btcsuite/btcwallet/wallet.(*Wallet).Accounts.func1.1(0x3199fa50)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/wallet/wallet.go:2405 +0x45 fp=0xc008d4d268 sp=0xc008d4d1c0 pc=0x916245
github.com/btcsuite/btcwallet/waddrmgr.forEachAccount.func1({0xc03199fa80, 0x1b7, 0x1000000000001b7}, {0xc03199fa84, 0x10, 0x10})
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/waddrmgr/db.go:987 +0x34 fp=0xc008d4d288 sp=0xc008d4d268 pc=0x747bb4
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0325c6880, 0xc031daffb0)
        /home/bitcoin/code/gocode/pkg/mod/go.etcd.io/bbolt@v1.3.5-0.20200615073812-232d8fc87f50/bucket.go:390 +0xa4 fp=0xc008d4d2e8 sp=0xc008d4d288 pc=0x92d504
github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).ForEach(0x7f264d73fa10, 0x1e0d3b8)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:190 +0x1d fp=0xc008d4d320 sp=0xc008d4d2e8 pc=0x94169d
github.com/btcsuite/btcwallet/waddrmgr.forEachAccount({0x7f264d73fa10, 0xc031da3e00}, 0xc031da3e40, 0xc0325c86f0)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/waddrmgr/db.go:982 +0xab fp=0xc008d4d360 sp=0xc008d4d320 pc=0x747b2b
github.com/btcsuite/btcwallet/waddrmgr.(*ScopedKeyManager).ForEachAccount(...)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/waddrmgr/scoped_manager.go:2187
github.com/btcsuite/btcwallet/wallet.(*Wallet).Accounts.func1({0x15dcca8, 0xc015a6ce70})
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/wallet/wallet.go:2404 +0x295 fp=0xc008d4d5d0 sp=0xc008d4d360 pc=0x915f75
github.com/btcsuite/btcwallet/walletdb/bdb.(*db).View(0xc031da3dc0, 0xc032587ce0, 0x4107bd)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:392 +0xad fp=0xc008d4d648 sp=0xc008d4d5d0 pc=0x94326d
github.com/btcsuite/btcwallet/walletdb.View(...)
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/interface.go:260
github.com/btcsuite/btcwallet/wallet.(*Wallet).Accounts(0xc00035c5a0, {0x8d4d738, 0xc0})
        /home/bitcoin/code/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.12.1-0.20210826004415-4ef582f76b02/wallet/wallet.go:2393 +0x13f fp=0xc008d4d6b0 sp=0xc008d4d648 pc=0x915c1f
github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).ListAccounts(0xc00063ae10, {0x0, 0xc009c22aa0}, 0x1)
        /home/bitcoin/code/lnd/lnwallet/btcwallet/btcwallet.go:538 +0x396 fp=0xc008d4d868 sp=0xc008d4d6b0 pc=0xafe096
github.com/lightningnetwork/lnd.(*rpcServer).WalletBalance(0xc0006d60d0, {0xc0325879b0, 0xc009c22aa0}, 0x1)
        /home/bitcoin/code/lnd/rpcserver.go:2812 +0x62 fp=0xc008d4d910 sp=0xc008d4d868 pc=0xf7b6e2
github.com/lightningnetwork/lnd/lnrpc._Lightning_WalletBalance_Handler.func1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0})
        /home/bitcoin/code/lnd/lnrpc/rpc.pb.go:21552 +0x7b fp=0xc008d4d950 sp=0xc008d4d910 pc=0xd87ffb
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0})
        /home/bitcoin/code/gocode/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:31 +0x89 fp=0xc008d4d998 sp=0xc008d4d950 pc=0xe704c9
github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).MacaroonUnaryServerInterceptor.func1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0}, 0xc0325879e0, 0xc02c6c9590)
        /home/bitcoin/code/lnd/rpcperms/interceptor.go:485 +0x8b fp=0xc008d4d9d0 sp=0xc008d4d998 pc=0xe72e6b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0})
        /home/bitcoin/code/gocode/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x6f fp=0xc008d4da18 sp=0xc008d4d9d0 pc=0xe704af
github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).rpcStateUnaryServerInterceptor.func1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0}, 0x50, 0xc02c6c9590)
        /home/bitcoin/code/lnd/rpcperms/interceptor.go:576 +0x82 fp=0xc008d4da48 sp=0xc008d4da18 pc=0xe733a2
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0})
        /home/bitcoin/code/gocode/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:34 +0x6f fp=0xc008d4da90 sp=0xc008d4da48 pc=0xe704af
github.com/lightningnetwork/lnd/rpcperms.errorLogUnaryServerInterceptor.func1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0}, 0xc031db9980, 0x0)
        /home/bitcoin/code/lnd/rpcperms/interceptor.go:401 +0x58 fp=0xc008d4db08 sp=0xc008d4da90 pc=0xe72678
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x15ecd80, 0xc0325879b0}, {0x119e2e0, 0xc0325879e0}, 0xc031db9980, 0xc031deea80)
        /home/bitcoin/code/gocode/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4/chain.go:39 +0x1a3 fp=0xc008d4db78 sp=0xc008d4db08 pc=0xe703e3
github.com/lightningnetwork/lnd/lnrpc._Lightning_WalletBalance_Handler({0x12cc760, 0xc0006d60d0}, {0x15ecd80, 0xc0325879b0}, 0xc032588780, 0xc0006b4db0)
        /home/bitcoin/code/lnd/lnrpc/rpc.pb.go:21554 +0x138 fp=0xc008d4dbd0 sp=0xc008d4db78 pc=0xd87eb8
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00050c9c0, {0x1601b80, 0xc02d656480}, 0xc0327be900, 0xc0006b5080, 0x1f2e8c0, 0x0)
        /home/bitcoin/code/gocode/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0xc8f fp=0xc008d4de50 sp=0xc008d4dbd0 pc=0xcf632f
google.golang.org/grpc.(*Server).handleStream(0xc00050c9c0, {0x1601b80, 0xc02d656480}, 0xc0327be900, 0x0)
        /home/bitcoin/code/gocode/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0x9f3 fp=0xc008d4df68 sp=0xc008d4de50 pc=0xcf9eb3
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/bitcoin/code/gocode/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0x98 fp=0xc008d4dfe0 sp=0xc008d4df68 pc=0xcf4078
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc008d4dfe8 sp=0xc008d4dfe0 pc=0x46a321
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/bitcoin/code/gocode/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xef

goroutine 1 [chan receive, 1 minutes]:
github.com/lightningnetwork/lnd.Main(0xc0003aa000, {0x0, 0x0, {0x0, 0x0}}, {0xc0001306c0, 0xc00010e3c0, 0xc00010e420, 0xc00010e480})
        /home/bitcoin/code/lnd/lnd.go:1022 +0x569f
main.main()
        /home/bitcoin/code/lnd/cmd/lnd/main.go:36 +0x145

goroutine 66 [syscall, 1 minutes]:
os/signal.signal_recv()
        /usr/local/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x2c

goroutine 23 [select, 1 minutes]:
github.com/lightningnetwork/lnd/signal.(*Interceptor).mainInterruptHandler(0xc00003c740)
        /home/bitcoin/code/lnd/signal/signal.go:95 +0x148
created by github.com/lightningnetwork/lnd/signal.Intercept
        /home/bitcoin/code/lnd/signal/signal.go:60 +0x1e7

```

**Comment by Roasbeef** [comment]
Ran through all the instances where the map is used: 
```
waddrmgr/scoped_manager.go
269:	for _, acctInfo := range s.acctInfo {
376:	if acctInfo, ok := s.acctInfo[account]; ok {
512:	s.acctInfo[account] = acctInfo
635:	acctInfo, ok := s.acctInfo[kp.InternalAccount]
1791:		if acctInfo, ok := s.acctInfo[account]; ok {
2364:	delete(s.acctInfo, account)
```

and AFAICT, all them are holding the mutex...
