### ISSUE TITLE
v0.14.1 - unexpected fault address / fatal error: fault / signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by miketwenty1** [lightningnetwork/lnd#6061]
### Background

running v0.14.1-beta / ec2 / 2 cpu / 8gb ram / ubuntu 20.04 

### Steps to reproduce

has happened twice on the same node. Once after running for 40 hours. Another after running for 35 hours. Unsure what action is causing it, as this node gets a lot of use in production.

### Expected behaviour

node doesn't crash

### Actual behaviour

node crashes.

_________________________

I would feel more comfortable sharing logs privately. currently Ryan Gentry has been given logs.. if you want to ask him for them.

A small snippet from logs:
```
unexpected fault address 0x7f6d7a97b548
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6d7a97b548 pc=0x40231f]

goroutine 1759 [running]:
runtime.throw({0x1ab5c44, 0xc0182adad8})
	runtime/panic.go:1198 +0x71 fp=0xc0182ada50 sp=0xc0182ada20 pc=0x435a71
```

**Comment by guggero** [comment]
Got the full log, here's the relevant part of the stack trace:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6d7a97b548 pc=0x40231f]

goroutine 1759 [running]:
runtime.throw({0x1ab5c44, 0xc0182adad8})
	runtime/panic.go:1198 +0x71 fp=0xc0182ada50 sp=0xc0182ada20 pc=0x435a71
runtime.sigpanic()
	runtime/signal_unix.go:742 +0x2f6 fp=0xc0182adaa0 sp=0xc0182ada50 pc=0x44bfb6
cmpbody()
	internal/bytealg/compare_amd64.s:74 +0x3f fp=0xc0182adaa8 sp=0xc0182adaa0 pc=0x40231f
bytes.Compare(...)
	bytes/bytes.go:27
go.etcd.io/bbolt.(*Cursor).searchNode.func1(0x18)
	go.etcd.io/bbolt@v1.3.6/cursor.go:273 +0x55 fp=0xc0182adaf0 sp=0xc0182adaa8 pc=0x9325d5
sort.Search(0x44d6b4, 0xc0182adb50)
	sort/search.go:66 +0x48 fp=0xc0182adb20 sp=0xc0182adaf0 pc=0x4a2b28
go.etcd.io/bbolt.(*Cursor).searchNode(0xc0182adcb0, {0x7f6d7a97b548, 0x31, 0x31}, 0xc0046a2a80)
	go.etcd.io/bbolt@v1.3.6/cursor.go:270 +0x93 fp=0xc0182adb90 sp=0xc0182adb20 pc=0x9324b3
go.etcd.io/bbolt.(*Cursor).search(0xc0182adcb0, {0x7f6d7a97b548, 0x31, 0x31}, 0xc0182adc70)
	go.etcd.io/bbolt@v1.3.6/cursor.go:262 +0x197 fp=0xc0182adc28 sp=0xc0182adb90 pc=0x9322d7
go.etcd.io/bbolt.(*Cursor).seek(0xc0182adcb0, {0x7f6d7a97b548, 0x7f6d69f928f0, 0x0})
	go.etcd.io/bbolt@v1.3.6/cursor.go:159 +0x48 fp=0xc0182adc80 sp=0xc0182adc28 pc=0x931be8
go.etcd.io/bbolt.(*Bucket).Delete(0xc003693180, {0x7f6d7a97b548, 0x0, 0x31})
	go.etcd.io/bbolt@v1.3.6/bucket.go:321 +0x99 fp=0xc0182adce0 sp=0xc0182adc80 pc=0x92f819
github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).Delete(0x17eae20, {0x7f6d7a97b548, 0xc00403dbc0, 0x31})
	github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:220 +0x25 fp=0xc0182add20 sp=0xc0182adce0 pc=0x944745
github.com/lightningnetwork/lnd/routing.(*missionControlStore).storeResults.func1({0x1ed7450, 0xc010d201e8})
	github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:350 +0x44a fp=0xc0182ade20 sp=0xc0182add20 pc=0x132520a
github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0x20, 0xc0145c6300, 0xc003724f01)
	github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:429 +0xb0 fp=0xc0182ade98 sp=0xc0182ade20 pc=0x945ef0
github.com/lightningnetwork/lnd/channeldb.(*DB).Update(0xc00007e820, 0xc004af6f28, 0xc004af6fe8)
	<autogenerated>:1 +0x2f fp=0xc0182adec0 sp=0xc0182ade98 pc=0x1214f6f
github.com/lightningnetwork/lnd/kvdb.Update(...)
	github.com/lightningnetwork/lnd/kvdb@v1.2.1/interface.go:16
github.com/lightningnetwork/lnd/routing.(*missionControlStore).storeResults(0xc00097e900)
	github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:314 +0x20b fp=0xc0182adf20 sp=0xc0182adec0 pc=0x1324bcb
github.com/lightningnetwork/lnd/routing.(*missionControlStore).run.func1()
	github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:290 +0x125 fp=0xc0182adfe0 sp=0xc0182adf20 pc=0x1324805
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0182adfe8 sp=0xc0182adfe0 pc=0x469061
created by github.com/lightningnetwork/lnd/routing.(*missionControlStore).run
	github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:282 +0x6f
```

Looks like a disk or file system issue at first glance. Trying to narrow it down further in chat.

**Comment by guggero** [comment]
Got a report from another user with exactly the same stack trace... Probably can rule out disk or file system issues at this point...

```
Dec 06 14:31:50 lnd[5818]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xfffdba7f97f1 pc=0x12264]
Dec 06 14:31:50 lnd[5818]: goroutine 10790 [running]:
Dec 06 14:31:50 lnd[5818]: runtime.throw({0x165bc53, 0x5})
Dec 06 14:31:50 lnd[5818]:         runtime/panic.go:1198 +0x54 fp=0x4018f1d980 sp=0x4018f1d950 pc=0x47e04
Dec 06 14:31:50 lnd[5818]: runtime.sigpanic()
Dec 06 14:31:50 lnd[5818]:         runtime/signal_unix.go:742 +0x1e4 fp=0x4018f1d9c0 sp=0x4018f1d980 pc=0x60d74
Dec 06 14:31:50 lnd[5818]: cmpbody()
Dec 06 14:31:50 lnd[5818]:         internal/bytealg/compare_arm64.s:46 +0x24 fp=0x4018f1d9d0 sp=0x4018f1d9d0 pc=0x12264
Dec 06 14:31:50 lnd[5818]: bytes.Compare(...)
Dec 06 14:31:50 lnd[5818]:         bytes/bytes.go:27
Dec 06 14:31:50 lnd[5818]: go.etcd.io/bbolt.(*Cursor).searchNode.func1(0x1)
Dec 06 14:31:50 lnd[5818]:         go.etcd.io/bbolt@v1.3.6/cursor.go:273 +0x74 fp=0x4018f1da20 sp=0x4018f1d9d0 pc=0x524034
Dec 06 14:31:50 lnd[5818]: sort.Search(0x2, 0x4018f1da98)
Dec 06 14:31:50 lnd[5818]:         sort/search.go:66 +0x4c fp=0x4018f1da60 sp=0x4018f1da20 pc=0xb713c
Dec 06 14:31:50 lnd[5818]: go.etcd.io/bbolt.(*Cursor).searchNode(0x4018f1dc48, {0xfffdba7f97f1, 0x31, 0x31}, 0x400023fb20)
Dec 06 14:31:50 lnd[5818]:         go.etcd.io/bbolt@v1.3.6/cursor.go:270 +0x74 fp=0x4018f1dad0 sp=0x4018f1da60 pc=0x523f14
Dec 06 14:31:50 lnd[5818]: go.etcd.io/bbolt.(*Cursor).search(0x4018f1dc48, {0xfffdba7f97f1, 0x31, 0x31}, 0xb5b)
Dec 06 14:31:50 lnd[5818]:         go.etcd.io/bbolt@v1.3.6/cursor.go:262 +0x190 fp=0x4018f1db70 sp=0x4018f1dad0 pc=0x523d80
Dec 06 14:31:50 lnd[5818]: go.etcd.io/bbolt.(*Cursor).seek(0x4018f1dc48, {0xfffdba7f97f1, 0x31, 0x31})
Dec 06 14:31:50 lnd[5818]:         go.etcd.io/bbolt@v1.3.6/cursor.go:159 +0x68 fp=0x4018f1dbe0 sp=0x4018f1db70 pc=0x5235d8
Dec 06 14:31:50 lnd[5818]: go.etcd.io/bbolt.(*Bucket).Delete(0x40077af680, {0xfffdba7f97f1, 0x31, 0x31})
Dec 06 14:31:50 lnd[5818]:         go.etcd.io/bbolt@v1.3.6/bucket.go:321 +0x98 fp=0x4018f1dc70 sp=0x4018f1dbe0 pc=0x520d48
Dec 06 14:31:50 lnd[5818]: github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).Delete(0x40077af680, {0xfffdba7f97f1, 0x31, 0x31})
Dec 06 14:31:50 lnd[5818]:         github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:220 +0x40 fp=0x4018f1dcd0 sp=0x4018f1dc70 pc=0x537c50
Dec 06 14:31:50 lnd[5818]: github.com/lightningnetwork/lnd/routing.(*missionControlStore).storeResults.func1({0x1a6b450, 0x40129fc528})
Dec 06 14:31:50 lnd[5818]:         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:350 +0x4b0 fp=0x4018f1dde0 sp=0x4018f1dcd0 pc=0xee6120
Dec 06 14:31:50 lnd[5818]: github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0x400014efc0, 0x4005a9ba10, 0x400ba28320)
Dec 06 14:31:50 lnd[5818]:         github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:429 +0xa4 fp=0x4018f1de50 sp=0x4018f1dde0 pc=0x539f04
Dec 06 14:31:50 lnd[5818]: github.com/lightningnetwork/lnd/channeldb.(*DB).Update(0x40001101e0, 0x4005a9ba10, 0x400ba28320)
Dec 06 14:31:50 lnd[5818]:         <autogenerated>:1 +0x4c fp=0x4018f1de90 sp=0x4018f1de50 pc=0xde59ac
Dec 06 14:31:50 lnd[5818]: github.com/lightningnetwork/lnd/kvdb.Update(...)
Dec 06 14:31:50 lnd[5818]:         github.com/lightningnetwork/lnd/kvdb@v1.2.1/interface.go:16
Dec 06 14:31:50 lnd[5818]: github.com/lightningnetwork/lnd/routing.(*missionControlStore).storeResults(0x4003dc4300)
Dec 06 14:31:50 lnd[5818]:         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:314 +0x2c0 fp=0x4018f1df10 sp=0x4018f1de90 pc=0xee5a50
Dec 06 14:31:50 lnd[5818]: github.com/lightningnetwork/lnd/routing.(*missionControlStore).run.func1(0x4003dc4300)
Dec 06 14:31:50 lnd[5818]:         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:290 +0xf4 fp=0x4018f1dfd0 sp=0x4018f1df10 pc=0xee5684
Dec 06 14:31:50 lnd[5818]: runtime.goexit()
Dec 06 14:31:50 lnd[5818]:         runtime/asm_arm64.s:1133 +0x4 fp=0x4018f1dfd0 sp=0x4018f1dfd0 pc=0x7e1f4
Dec 06 14:31:50 lnd[5818]: created by github.com/lightningnetwork/lnd/routing.(*missionControlStore).run
Dec 06 14:31:50 lnd[5818]:         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:282 +0x58
```

**Comment by guggero** [comment]
We're investigating what is causing this. For now, any user experiencing this crash is advised to add the following section to their config file:

```
[routerrpc]
routerrpc.maxmchistory=0
```

This will cause the Mission Control history to grow above its default size of 1k records. For nodes that do a lot of payments this might mean an increase in the size of the `channel.db`, so the option should be removed again once a fix for this problem is out.

**Comment by dlaptev** [comment]
Just experienced the same issue. Are we advised to rebuild with #6068 patched or is `routerrpc.maxmchistory=0` good enough for now? Thanks!

**Comment by Roasbeef** [comment]
Closing as this was fixed with #6068

**Comment by guggero** [comment]
We'll include #6068 in the next bugfix release (`v0.14.2-beta`) which will hopefully be out soon. Until then it should be enough to add the `routerrpc.maxmchistory` config option to avoid the segfault.

**Comment by miketwenty1** [comment]
just fyi this happened to us again.
Looking forward to 0.14.2-beta @guggero 
```
unexpected fault address 0x7fac554ce215
 fatal error: fault
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x7fac554ce215 pc=0x40231f]
 
 goroutine 3154 [running]:
 runtime.throw({0x1ab5c44, 0xc01695aad8})
         runtime/panic.go:1198 +0x71 fp=0xc01695aa50 sp=0xc01695aa20 pc=0x435a71
 runtime.sigpanic()
         runtime/signal_unix.go:742 +0x2f6 fp=0xc01695aaa0 sp=0xc01695aa50 pc=0x44bfb6
 cmpbody()
         internal/bytealg/compare_amd64.s:74 +0x3f fp=0xc01695aaa8 sp=0xc01695aaa0 pc=0x40231f
 bytes.Compare(...)
         bytes/bytes.go:27
 go.etcd.io/bbolt.(*Cursor).searchNode.func1(0x18)
         go.etcd.io/bbolt@v1.3.6/cursor.go:273 +0x55 fp=0xc01695aaf0 sp=0xc01695aaa8 pc=0x9325d5
 sort.Search(0x44d6b4, 0xc01695ab50)
         sort/search.go:66 +0x48 fp=0xc01695ab20 sp=0xc01695aaf0 pc=0x4a2b28
 go.etcd.io/bbolt.(*Cursor).searchNode(0xc01695acb0, {0x7fac554ce215, 0x31, 0x31}, 0xc0052b5500)
         go.etcd.io/bbolt@v1.3.6/cursor.go:270 +0x93 fp=0xc01695ab90 sp=0xc01695ab20 pc=0x9324b3
 go.etcd.io/bbolt.(*Cursor).search(0xc01695acb0, {0x7fac554ce215, 0x31, 0x31}, 0xc01695ac70)
         go.etcd.io/bbolt@v1.3.6/cursor.go:262 +0x197 fp=0xc01695ac28 sp=0xc01695ab90 pc=0x9322d7
 go.etcd.io/bbolt.(*Cursor).seek(0xc01695acb0, {0x7fac554ce215, 0x7fac38aaf5b0, 0x0})
         go.etcd.io/bbolt@v1.3.6/cursor.go:159 +0x48 fp=0xc01695ac80 sp=0xc01695ac28 pc=0x931be8
 go.etcd.io/bbolt.(*Bucket).Delete(0xc0063a9a80, {0x7fac554ce215, 0x0, 0x31})
         go.etcd.io/bbolt@v1.3.6/bucket.go:321 +0x99 fp=0xc01695ace0 sp=0xc01695ac80 pc=0x92f819
 github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).Delete(0x17eae20, {0x7fac554ce215, 0xc014ef8840, 0x31})
         github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:220 +0x25 fp=0xc01695ad20 sp=0xc01695ace0 pc=0x944745
 github.com/lightningnetwork/lnd/routing.(*missionControlStore).storeResults.func1({0x1ed7450, 0xc00f546640})
         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:350 +0x44a fp=0xc01695ae20 sp=0xc01695ad20 pc=0x132520a
 github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0x20, 0xc01d2519b0, 0xc00031af01)
         github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:429 +0xb0 fp=0xc01695ae98 sp=0xc01695ae20 pc=0x945ef0
 github.com/lightningnetwork/lnd/channeldb.(*DB).Update(0xc00054a500, 0xc00479af28, 0xc00479afe8)
         <autogenerated>:1 +0x2f fp=0xc01695aec0 sp=0xc01695ae98 pc=0x1214f6f
 github.com/lightningnetwork/lnd/kvdb.Update(...)
         github.com/lightningnetwork/lnd/kvdb@v1.2.1/interface.go:16
 github.com/lightningnetwork/lnd/routing.(*missionControlStore).storeResults(0xc001cf5860)
         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:314 +0x20b fp=0xc01695af20 sp=0xc01695aec0 pc=0x1324bcb
 github.com/lightningnetwork/lnd/routing.(*missionControlStore).run.func1()
         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:290 +0x125 fp=0xc01695afe0 sp=0xc01695af20 pc=0x1324805
 runtime.goexit()
         runtime/asm_amd64.s:1581 +0x1 fp=0xc01695afe8 sp=0xc01695afe0 pc=0x469061
 created by github.com/lightningnetwork/lnd/routing.(*missionControlStore).run
         github.com/lightningnetwork/lnd/routing/missioncontrol_store.go:282 +0x6f
 
 ```

**Comment by guggero** [comment]
But this happened on a node where you didn't set `routerrpc.maxmchistory=0`, right?
