### ISSUE TITLE
lnd crashes on startup after transfering to new node

### ISSUE THREAD

**Issue by penguin4111** [lightningnetwork/lnd#6275]
### Background

Was running an lnd node on an older system and am changing over to a new one. Upon installing lnd on my new node and copying the data folder over, lnd crashes with the following messages:

```
Attempting automatic RPC configuration to bitcoind
Automatically obtained bitcoind's RPC credentials
2022-02-18 13:05:05.223 [INF] LTND: Version: 0.14.2-beta commit=v0.14.2-beta, build=production, logging=default, debuglevel=info
2022-02-18 13:05:05.224 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2022-02-18 13:05:05.226 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2022-02-18 13:05:05.235 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080
2022-02-18 13:05:05.235 [INF] LTND: Opening the main database, this might take a few minutes...
2022-02-18 13:05:05.235 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
2022-02-18 13:05:05.235 [INF] CHDB: Compacting database file at /home/lnd/.lnd/data/graph/mainnet/channel.db
2022-02-18 13:05:05.262 [INF] LTND: Shutdown complete

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd18324]

goroutine 1 [running]:
go.etcd.io/bbolt.(*Bucket).Sequence(...)
        go.etcd.io/bbolt@v1.3.6/bucket.go:340
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1.1({0x7f90e7d760, 0x10, 0x10}, 0x0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:227 +0x104
go.etcd.io/bbolt.(*Tx).ForEach.func1({0x7f90e7d760, 0x10, 0x10}, {0x7f90e7d010, 0x0, 0x0})
        go.etcd.io/bbolt@v1.3.6/tx.go:129 +0x7c
go.etcd.io/bbolt.(*Bucket).ForEach(0x40005462b8, 0x4000838930)
        go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0x10c
go.etcd.io/bbolt.(*Tx).ForEach(0x40005462a0, 0x4000838980)
        go.etcd.io/bbolt@v1.3.6/tx.go:128 +0x58
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk.func1(0x40005462a0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:220 +0x54
go.etcd.io/bbolt.(*DB).View(0x400096e000, 0x4000838a40)
        go.etcd.io/bbolt@v1.3.6/db.go:772 +0x84
github.com/lightningnetwork/lnd/kvdb.(*compacter).walk(0x4000838eb0, 0x400096e000, 0x4000838ab8)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:219 +0x54
github.com/lightningnetwork/lnd/kvdb.(*compacter).compact(0x4000838eb0, 0x400096e240, 0x400096e000)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:147 +0xd4
github.com/lightningnetwork/lnd/kvdb.(*compacter).execute(0x4000838eb0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/bolt_compact.go:117 +0x500
github.com/lightningnetwork/lnd/kvdb.compactAndSwap(0x40008392d0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/backend.go:179 +0x71c
github.com/lightningnetwork/lnd/kvdb.GetBoltBackend(0x40008392d0)
        github.com/lightningnetwork/lnd/kvdb@v1.3.0/backend.go:101 +0x98
github.com/lightningnetwork/lnd/lncfg.(*DB).GetBackends(0x400048c000, {0x1a54510, 0x400048d5c0}, {0x4000522330, 0x21}, {0x40006590b0, 0x29}, {0x4000522360, 0x2e}, 0x1, ...)
        github.com/lightningnetwork/lnd/lncfg/db.go:392 +0x20b8
github.com/lightningnetwork/lnd.(*DefaultDatabaseBuilder).BuildDatabase(0x4000434e28, {0x1a54510, 0x400048d5c0})
        github.com/lightningnetwork/lnd/config_builder.go:810 +0x324
github.com/lightningnetwork/lnd.Main(0x4000478500, {{0x0, 0x0, 0x0}}, 0x4000542840, {0x400022c4e0, 0x40000443c0, 0x4000044540, 0x40000445a0, {0x0}})
        github.com/lightningnetwork/lnd/lnd.go:353 +0x15d0
main.main()
        github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x258
```

It is not at all clear to me what this error means and so I have no idea how I should proceed. Any thoughts from someone a little more knowledgeable would be greatly appreciated!

### Your environment

0.14.2-beta commit=v0.14.2-beta
Raspberry pi 4, pi OS 64bit
bitcoind version v22.0.0

### Steps to reproduce

Happens when I simply run lnd.

**Comment by HannahMR** [comment]
A few questions...

What is the channel.db file size?
You moved the node to Raspberry pi 4, pi OS 64bit, but can you tell us a bit about the system you migrated from?
Did you follow these steps when migrating? https://docs.lightning.engineering/lightning-network-tools/lnd/migrating-lnd

**Comment by penguin4111** [comment]
> A few questions...
> 
> What is the channel.db file size? You moved the node to Raspberry pi 4, pi OS 64bit, but can you tell us a bit about the system you migrated from? Did you follow these steps when migrating? https://docs.lightning.engineering/lightning-network-tools/lnd/migrating-lnd

The channel.db file has a size of 251MB.

Sorry I should have mentioned more about the system change. Previous system was also a Raspberry pi 4, running pi OS 32bit. Thus the changeover, to go from 32bit to 64bit OS on my pi. Previous system ran lnd v0.13.4 and bitcoind v0.21.0. 

I believe I did follow all of the steps in that guide. The only thing I did not do was delete the macaroons. I went ahead and tried that just now, but no luck same crash and error sadly.

**Comment by lucasdcf** [comment]
Hey @penguin4111, can you please try compacting with Guggero's chantools, on the new node with the old db? 
https://github.com/guggero/chantools

**Comment by lucasdcf** [comment]
@penguin4111 any news?

**Comment by Roasbeef** [comment]
Closing due to inactivity.
