### ISSUE TITLE
segmentation fault after force closing channel with 100 HTLCs

### ISSUE THREAD

**Issue by antonilol** [lightningnetwork/lnd#6436]
### Background

Describe your issue here.

i have 2 nodes on testnet and made a channel of 100k sats between them
both have accept-amp and accept-keysend enabled in the conf

i was experimenting with amp payment sharding and made a payment of 54100 sat with a max shard size of 541. i made 100 shards and it succeeded. then i tried the same thing again but now i force closed the channel to get the HTLCs on the chain. after that the rpc didnt work anymore so checked the logs and found out it crashed. if i try to restart it i can enter the wallet password and it crashed again with a segfault. my other node didnt crash

### Your environment

* version of `lnd`
  `lnd version 0.14.2-beta commit=v0.14.2-beta`
* which operating system (`uname -a` on *Nix)
  `Linux 5600g 5.17.2-arch3-1 #1 SMP PREEMPT Sun, 10 Apr 2022 11:18:32 +0000 x86_64 GNU/Linux`
* version of `btcd`, `bitcoind`, or other backend
  `Bitcoin Core version v22.0.0`
* any other relevant environment details
  

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

i dont know, it came unexpected.
i did it 5 times and the 5th time it crashed

### Expected behaviour

Tell us what should happen

no segfault of course

### Actual behaviour

Tell us what happens instead

a segfault

logs
i appended the last lines with the segfault from journalctl
[lnd_crash.log](https://github.com/lightningnetwork/lnd/files/8523237/lnd_crash.log)

```
Apr 20 17:50:02 5600g lnd[175503]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 20 17:50:02 5600g lnd[175503]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc06ea4]
Apr 20 17:50:02 5600g lnd[175503]: goroutine 1096 [running]:
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/invoices.updateInvoice(0xc002b7f180, 0xc003aa1420)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/invoices/update.go:103 +0xc4
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/invoices.(*InvoiceRegistry).notifyExitHopHtlcLocked.func1(0xc003aa1260?)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/invoices/invoiceregistry.go:1028 +0x39
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/channeldb.(*DB).updateInvoice(0xc000622280, 0xc002efe5c0?, 0x7fcaa585f2c0?, {0x17e5a58, 0xc002efe580}, {0x17e5a58, 0xc002efe600}, {0x17e5a58, 0xc002efe680}, {0xc000c4b720, ...}, ...)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/channeldb/invoices.go:2634 +0x202
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/channeldb.(*DB).UpdateInvoice.func1({0x17e1f20, 0xc0009ddab8})
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/channeldb/invoices.go:1413 +0x2fc
Apr 20 17:50:02 5600g lnd[175503]: github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0xc000600800?, 0xc000e00af0, 0x0?)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/go/pkg/mod/github.com/btcsuite/btcwallet/walletdb@v1.3.6-0.20210803004036-eebed51155ec/bdb/db.go:429 +0xb0
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/kvdb.Update(...)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/kvdb/interface.go:16
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/channeldb.(*DB).UpdateInvoice(0xc000622280?, {0x0?, 0xc0008ba7a0?, 0x0?, 0xff?}, 0xc0008ba7c0?, 0xc0025811e0?)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/channeldb/invoices.go:1383 +0x19a
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/invoices.(*InvoiceRegistry).notifyExitHopHtlcLocked(0xc0002e6640, 0xc002b7f180, 0x676066de819a6e2f?)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/invoices/invoiceregistry.go:1022 +0x2fb
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/invoices.(*InvoiceRegistry).NotifyExitHopHtlc(0xc0002e6640, {0xb3, 0xe, 0xa7, 0xe6, 0x9, 0x59, 0x1b, 0x83, 0xcc, ...}, ...)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/invoices/invoiceregistry.go:975 +0x485
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/contractcourt.(*htlcIncomingContestResolver).Resolve(0xc00039f630)
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/contractcourt/htlc_incoming_contest_resolver.go:237 +0x633
Apr 20 17:50:02 5600g lnd[175503]: github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).resolveContract(0xc0000b9180, {0x17df728?, 0xc00039f630})
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/contractcourt/channel_arbitrator.go:2282 +0x2a9
Apr 20 17:50:02 5600g lnd[175503]: created by github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).launchResolvers
Apr 20 17:50:02 5600g lnd[175503]:         /home/antoni/github/lnd/contractcourt/channel_arbitrator.go:1342 +0x195
```

**Comment by Crypt-iQ** [comment]
can you post the relevant stack trace here as well so people don't have to download it

**Comment by antonilol** [comment]
sure

**Comment by antonilol** [comment]
i restarted lnd with debuglevel=debug and it crashed as expected, here are the logs:

[lnd_crash_debug.log](https://github.com/lightningnetwork/lnd/files/8524208/lnd_crash_debug.log)

i grepped for `nil` and `0x0`, maybe this helps:
```
$ cat lnd_crash_debug.log | grep -ETn 'nil|0x0[^0-9a-f]'
                1943:	2022-04-20 20:11:02.862 [DBG] CNCT: Starting ChannelArbitrator(bc5069269301b93e2627580533814fb7ceb8555bddf8bd2feed0a350440ea9e4:0), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>
                1950:	2022-04-20 20:11:02.864 [DBG] CNCT: Starting ChannelArbitrator(70a7b4108ccc0dfc916f1e0ed29126eea6d40be05fefbb36dad2fe1c51a0d9ec:1), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>
                1958:	2022-04-20 20:11:02.864 [INF] SWPR: Sweep request received: out_point=4f411a665a8016b3baf55ce194796a01684b7db5df904ab55483bf5a66198049:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=253 sat/kw, force=false, exclusive_group=<nil>)
                1974:	2022-04-20 20:11:02.871 [DBG] CNCT: Starting ChannelArbitrator(0736d20cf96ff2ef31854b9ce3645f8f20edcaa415e9b4a190643fc3ebc2d8ff:1), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>
                2216:	2022-04-20 20:11:02.873 [DBG] CNCT: Starting ChannelArbitrator(fe068212f70886de05952e13f5e90be4bace958385496263a0a721f9c24e1b1d:1), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>
                2222:	2022-04-20 20:11:02.873 [INF] SWPR: Sweep request received: out_point=bf680a225ef135f971863588877b169d1f6f8b88ebfb2c9d67a2417010f7f755:0, witness_type=CommitmentAnchor, relative_time_lock=0, absolute_time_lock=0, amount=0.0000033 BTC, params=(fee=253 sat/kw, force=false, exclusive_group=<nil>)
                2233:	2022-04-20 20:11:02.877 [DBG] CNCT: Starting ChannelArbitrator(e328c444cdeea93ed5a7875ff9bd81b5bf51f79228886a663297708723fde170:0), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>
                2398:	2022-04-20 20:11:02.884 [DBG] CNCT: Starting ChannelArbitrator(d1ad120b1805af53782c14b00584f14fd197cdc68b502bf15bb27e8b07daa490:0), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>
                2559:	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc07184]
                2570:	github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0xc0004e6c00?, 0xc0026fe1e0, 0x0?)
                2574:	github.com/lightningnetwork/lnd/channeldb.(*DB).UpdateInvoice(0xc0000a4960?, {0x0?, 0xc0005ae660?, 0x0?, 0x93?}, 0xc0005ae680?, 0xc0000caa40?)
```

**Comment by antonilol** [comment]
one channel's HTLCs expired and my lnd runs normal again
