### ISSUE TITLE
Unexpected termination when calling `GetNetworkInfo`

### ISSUE THREAD

**Issue by alexbosworth** [lightningnetwork/lnd#6506]
### Background

LND unexpectedly terminates when `GetNetworkInfo` is called, when there are no channels or nodes

### Your environment

- LND docker daily-testing-20220506

### Steps to reproduce

1. spin up a node on regtest
2. call `GetNetworkInfo`

### Expected behavior

It should return zero values

### Actual behavior

Termination due to index out of range exception

```
?2022-05-06 16:03:49.392 [INF] LNWL: Done catching up block hashes
2022-05-06 16:03:49.392 [INF] LNWL: Finished rescan for 0 addresses (synced to block 2e325ed57befc3bb70f17dbee5df37c6c963d39ac626f2039d201c4533090cdf, height 1)
Y2022-05-06 16:03:49.553 [DBG] ATPL: Initialized simple graph with 0 nodes and 0 channels
?panic: runtime error: index out of range [0] with length 0

goroutine 482 [running]:
github.com/lightningnetwork/lnd/autopilot.(*SimpleGraph).shortestPathLengths(0x40013bda70, 0x0)
	github.com/lightningnetwork/lnd/autopilot/simple_graph.go:146 +0x2b4
github.com/lightningnetwork/lnd/autopilot.(*SimpleGraph).DiameterRadialCutoff(0x40013bda70)
	github.com/lightningnetwork/lnd/autopilot/simple_graph.go:208 +0x6c
github.com/lightningnetwork/lnd.(*rpcServer).GetNetworkInfo(0x400010d6f8?, {0xa8463c?, 0x400010d6f8?}, 0x40013bd8c0?)
	github.com/lightningnetwork/lnd/rpcserver.go:5956 +0x22c
github.com/lightningnetwork/lnd/lnrpc._Lightning_GetNetworkInfo_Handler.func1({0x19beb80, 0x40013bd320}, {0x141d140?, 0x40013bd350})
	github.com/lightningnetwork/lnd/lnrpc/lightning_grpc.pb.go:2781 +0x78
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x19beb80, 0x40013bd320}, {0x141d140, 0x40013bd350}, 0x4000262e40?, 0x4000509c50)
	github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x78
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19beb80?, 0x40013bd320?}, {0x141d140?, 0x40013bd350?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).middlewareUnaryServerInterceptor.func1({0x19beb80, 0x40013bd320}, {0x141d140, 0x40013bd350}, 0x4000909100, 0x4000909120)
	github.com/lightningnetwork/lnd/rpcperms/interceptor.go:789 +0x1a0
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19beb80?, 0x40013bd320?}, {0x141d140?, 0x40013bd350?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).MacaroonUnaryServerInterceptor.func1({0x19beb80, 0x40013bd320}, {0x141d140, 0x40013bd350}, 0x0?, 0x4000909140)
	github.com/lightningnetwork/lnd/rpcperms/interceptor.go:663 +0x94
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19beb80?, 0x40013bd320?}, {0x141d140?, 0x40013bd350?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
github.com/lightningnetwork/lnd/rpcperms.(*InterceptorChain).rpcStateUnaryServerInterceptor.func1({0x19beb80, 0x40013bd320}, {0x141d140, 0x40013bd350}, 0x400010d998?, 0x4000909160)
	github.com/lightningnetwork/lnd/rpcperms/interceptor.go:753 +0x88
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19beb80?, 0x40013bd320?}, {0x141d140?, 0x40013bd350?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
github.com/lightningnetwork/lnd/rpcperms.errorLogUnaryServerInterceptor.func1({0x19beb80?, 0x40013bd320?}, {0x141d140?, 0x40013bd350?}, 0x4000909100, 0x4000909100?)
	github.com/lightningnetwork/lnd/rpcperms/interceptor.go:579 +0x4c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19beb80?, 0x40013bd320?}, {0x141d140?, 0x40013bd350?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x40
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x19beb80, 0x40013bd320}, {0x141d140, 0x40013bd350}, 0x4001446ab8?, 0x785900?)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbc
github.com/lightningnetwork/lnd/lnrpc._Lightning_GetNetworkInfo_Handler({0x15fe2c0?, 0x4000160e10}, {0x19beb80, 0x40013bd320}, 0x400087e9c0, 0x400070c330)
	github.com/lightningnetwork/lnd/lnrpc/lightning_grpc.pb.go:2783 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0x400070a380, {0x19cbef8, 0x40013e8000}, 0x40013ca120, 0x400070c540, 0x26ea5e0, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1286 +0xad4
google.golang.org/grpc.(*Server).handleStream(0x400070a380, {0x19cbef8, 0x40013e8000}, 0x40013ca120, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1609 +0x854
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.38.0/server.go:934 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.38.0/server.go:932 +0x29c
```

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/issues/6647.
