### ISSUE TITLE
`detected stalled state=StateDefault for closed channel` followed by lnd shutting down

### ISSUE THREAD

**Issue by Fittiboy** [lightningnetwork/lnd#6585]
### Background

I have upgraded to v0.15.0-beta.rc3 to reduce my extremely large channel db, and now lnd shuts down after reporting a `stalled` state.

### Your environment

* `lnd` version: 0.15.0-beta.rc3
* OS: `Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux` (running raspiblitz 1.7.2)
* `bitcoind` version: v23.0.0

### Expected behaviour

lnd should start up and run.

### Actual behaviour

lnd shuts down:

```
2022-05-27 14:35:13.621 [DBG] CNCT: Starting ChannelArbitrator(...), htlc_set=(map[contractcourt.HtlcSetKey]contractcourt.htlcSet) <nil>, state=StateDefault
2022-05-27 14:35:13.624 [WRN] CNCT: ChannelArbitrator(...): detected stalled state=StateDefault for closed channel
2022-05-27 14:35:13.624 [INF] CNCT: ChannelArbitrator(...): starting state=StateDefault, trigger=coopCloseTrigger, triggerHeight=738086
2022-05-27 14:35:13.625 [DBG] CNCT: ChannelArbitrator(...): attempting state step with trigger=coopCloseTrigger from state=StateDefault
2022-05-27 14:35:13.626 [DBG] CNCT: ChannelArbitrator(...): new block (height=738086) examining active HTLC's
2022-05-27 14:35:13.628 [INF] RPCS: Stopping RPC Server
2022-05-27 14:35:13.629 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2022-05-27 14:35:13.630 [INF] RPCS: Stopping RouterRPC Sub-RPC Server
2022-05-27 14:35:13.631 [INF] RPCS: Stopping AutopilotRPC Sub-RPC Server
2022-05-27 14:35:13.632 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
2022-05-27 14:35:13.634 [INF] RPCS: Stopping WatchtowerClientRPC Sub-RPC Server
2022-05-27 14:35:13.635 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
2022-05-27 14:35:13.636 [INF] RPCS: Stopping PeersRPC Sub-RPC Server
2022-05-27 14:35:13.638 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
2022-05-27 14:35:13.639 [INF] RPCS: Stopping NeutrinoKitRPC Sub-RPC Server
2022-05-27 14:35:13.640 [INF] RPCS: Stopping VersionRPC Sub-RPC Server
2022-05-27 14:35:13.641 [INF] RPCS: Stopping WatchtowerRPC Sub-RPC Server
2022-05-27 14:35:13.641 [INF] TORC: Stopping tor controller
2022-05-27 14:35:13.641 [DBG] TORC: removing serviceID: from tor controller
2022-05-27 14:35:13.642 [DBG] TORC: sendCommand:DEL_ONION  got err:unexpected code, reply:Bad arguments to DEL_ONION: Need at least 1 argument(s)
2022-05-27 14:35:13.642 [ERR] TORC: DEL_ONION got error: invalid arguments: unexpected code
2022-05-27 14:35:13.643 [ERR] LTND: error stopping tor controller: invalid arguments: unexpected code
2022-05-27 14:35:13.665 [INF] LTND: Shutdown complete
```  

I manually removed the channel point from the logs. If it's required for debugging, I can send it privately.
(Also note the DEL_ONION error when LND is shutting down)

Edit: More info from the journal:
```
May 27 15:16:50 raspberrypi systemd[1]: Starting Lightning Network Daemon...
May 27 15:16:56 raspberrypi systemd[1]: Started Lightning Network Daemon.
May 27 15:17:18 raspberrypi lnd[367395]: panic: assignment to entry in nil map
May 27 15:17:18 raspberrypi lnd[367395]: goroutine 1 [running]:
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).updateActiveHTLCs(0x40044c3900)
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:2440 +0xf0
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).stateStep(0x40044c3900, 0x16a76d8?, 0x4, 0x0)
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:834 +0x1a4
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).advanceState(0x40044c3900, 0x16a4a33?, 0x4, 0x4003d4c708?)
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:1393 +0x190
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd/contractcourt.(*ChannelArbitrator).Start(0x40044c3900, 0x4004b1cd90)
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/contractcourt/channel_arbitrator.go:519 +0x574
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd/contractcourt.(*ChainArbitrator).Start(0x40086074a0)
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/contractcourt/chain_arbitrator.go:695 +0xf88
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd.(*server).Start.func1()
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/server.go:1799 +0x1804
May 27 15:17:18 raspberrypi lnd[367395]: sync.(*Once).doSlow(0x4?, 0x167f5d2?)
May 27 15:17:18 raspberrypi lnd[367395]:         sync/once.go:68 +0x10c
May 27 15:17:18 raspberrypi lnd[367395]: sync.(*Once).Do(...)
May 27 15:17:18 raspberrypi lnd[367395]:         sync/once.go:59
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd.(*server).Start(0x40000b4358?)
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/server.go:1674 +0x70
May 27 15:17:18 raspberrypi lnd[367395]: github.com/lightningnetwork/lnd.Main(0x40000b4b00, {{0x0?, 0x40001805a0?, 0x4000180600?}}, 0x4000645440, {0x400011a120, 0x40001805a0, 0x4000180600, 0x4000180660, {0x0}})
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/lnd.go:594 +0x2bc8
May 27 15:17:18 raspberrypi lnd[367395]: main.main()
May 27 15:17:18 raspberrypi lnd[367395]:         github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x1ac
May 27 15:17:19 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 27 15:17:19 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.
May 27 15:17:19 raspberrypi systemd[1]: lnd.service: Consumed 19.254s CPU time.
```

**Comment by Fittiboy** [comment]
My node has had a lot of channels, and currently has 30 "active" channels – though they're obviously not active right now while my node is in a restart loop. Therefore my startup logs are extremely long. If more information is required, I'm happy to provide it.  
Also, my channel db shrunk from 35GB to I think 1.6GB, which is why I wanted to update in the first place.

**Comment by Fittiboy** [comment]
I also just checked the closing transaction for that channel. It has 49 confirmations at the moment, and I think happened around the time I upgraded my lnd.

**Comment by Crypt-iQ** [comment]
Did you experience any power loss or panics besides this one, with a different stacktrace? I think the code here should be "roughly" atomic such that it's not possible to be in StateDefault with a closed channel - the state machine should progress through to a later state. Since this is happening, some assumption is being violated

**Comment by Roasbeef** [comment]
Related Tor error seemingly due to power failure: https://github.com/lightningnetwork/lnd/issues/6503

**Comment by Roasbeef** [comment]
@Fittiboy can you give this PR a shot? https://github.com/lightningnetwork/lnd/pull/6586

**Comment by Fittiboy** [comment]
> @Fittiboy can you give this PR a shot? #6586

Thanks @Roasbeef, that did it! I don't really know where the issue came from. I _did_ disconnect my pi from power once, but that was after a controlled shutdown, and upgrading my raspiblitz version to 1.7.2. When I disconnected it from power, that was before anything was running, on the initial update startup screen.
I'm having some other issues now, but they are probably not related. It's `cannot determine data format of binary-encoded macaroon` in my logs. Will update once I'm positive the node is actually fully functional again!

**Comment by Fittiboy** [comment]
Okay my node has caught up with the network and is now fully back up and running!
