### ISSUE TITLE
'Slice bounds out of range' on canceling epoch notification

### ISSUE THREAD

**Issue by sangaman** [lightningnetwork/lnd#659]
This error appeared out of the blue on a node that I've had running for weeks (it's also been several weeks since I updated it with the latest from master, latest commit is `2f926f1`). It's the first time I've seen it. This is on debian stretch running in neutrino mode. The logs show a bunch of `NTFN: Cancelling epoch notification` in the milliseconds before the crash, I can paste more of the log activity leading up the crash if it would be helpful.

```
2018-01-23 07:09:56.025 [INF] NTFN: Cancelling epoch notification, epoch_id=8
panic: runtime error: slice bounds out of range

goroutine 141 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightningnetwork/lightning-onion.(*OnionErrorDecrypter).DecryptEr
ror(0xc420f7d098, 0xc42779700a, 0x2, 0x2, 0xc420017900, 0xc420f37598, 0xc420f375e8, 0xa6b382, 0xc4202a8780, 0xc4306
77a10)
        /home/mcnallydp/go/src/github.com/lightningnetwork/lnd/vendor/github.com/lightningnetwork/lightning-onion/o
bfuscation.go:197 +0x4b7
github.com/lightningnetwork/lnd/htlcswitch.(*SphinxErrorDecrypter).DecryptError(0xc420f7d0b8, 0xc42779700a, 0x2, 0x
2, 0x0, 0xc4200f5860, 0xfaff58)
        /home/mcnallydp/go/src/github.com/lightningnetwork/lnd/htlcswitch/failure.go:117 +0x6a
github.com/lightningnetwork/lnd/htlcswitch.(*Switch).handleLocalDispatch(0xc4202a8750, 0xc422656900, 0x3c, 0xc42829
35e0)
        /home/mcnallydp/go/src/github.com/lightningnetwork/lnd/htlcswitch/switch.go:458 +0x674
github.com/lightningnetwork/lnd/htlcswitch.(*Switch).handlePacketForward(0xc4202a8750, 0xc422656900, 0x0, 0x1)
        /home/mcnallydp/go/src/github.com/lightningnetwork/lnd/htlcswitch/switch.go:636 +0x2d9
github.com/lightningnetwork/lnd/htlcswitch.(*Switch).htlcForwarder(0xc4202a8750)
        /home/mcnallydp/go/src/github.com/lightningnetwork/lnd/htlcswitch/switch.go:743 +0x7de
created by github.com/lightningnetwork/lnd/htlcswitch.(*Switch).Start
        /home/mcnallydp/go/src/github.com/lightningnetwork/lnd/htlcswitch/switch.go:843 +0x1e3
mcnallydp@instance-1:~/.lnd$
```

**Comment by Roasbeef** [comment]
The interfaces around the switch, and handling reconnections has been re-worked significantly. As a result, the traceback found is no longer useful. Closing for now, we can re-open if it's possible to reproduce this with the current master branch.
