### ISSUE TITLE
Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by rstoffel** [lightningnetwork/lnd#6617]
### Background

Unexpected start problem after 6 months of problem free runnig of the node. Initial errormessage:
lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

node alias: wyssblitz 
lnd version: v0.14.3-beta
bitcoind: Bitcoin Core version v0.21.1
os: Linux 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
self buit system (following raspi bolt)
lnd running as service (systemd)
management tools: RTL, LNDg

### Steps to reproduce

starting the service: sudo systemctl start lnd.service
monitoring with journalctl -u lnd -f 
result:

2022-06-04 20:30:01.971 [DBG] RPCS: Starting sub RPC server: WalletKitRPC
2022-06-04 20:30:01.971 [DBG] RPCS: Starting sub RPC server: AutopilotRPC
2022-06-04 20:30:01.971 [DBG] RPCS: Starting sub RPC server: ChainRPC
2022-06-04 20:30:01.972 [DBG] RPCS: Starting sub RPC server: WatchtowerRPC
2022-06-04 20:30:01.972 [DBG] RPCS: Starting sub RPC server: SignRPC
2022-06-04 20:30:01.972 [DBG] RPCS: Starting sub RPC server: RouterRPC
2022-06-04 20:30:01.972 [DBG] RPCS: Starting sub RPC server: InvoicesRPC
2022-06-04 20:30:01.972 [DBG] RPCS: Starting sub RPC server: VersionRPC
2022-06-04 20:30:01.972 [DBG] RPCS: Starting sub RPC server: WatchtowerClientRPC
2022-06-04 20:30:01.972 [INF] LTND: We're not running within systemd
2022-06-04 20:30:01.976 [INF] LTND: Waiting for chain backend to finish sync, start_height=739264
2022-06-04 20:30:01.982 [INF] LTND: Chain backend is fully synced (end_height=739264)!
2022-06-04 20:30:01.982 [WRN] HLCK: check: disk space configured with 0 attempts, skipping it
2022-06-04 20:30:01.982 [WRN] HLCK: check: tls configured with 0 attempts, skipping it
2022-06-04 20:30:01.982 [WRN] HLCK: check: tor connection configured with 0 attempts, skipping it
2022-06-04 20:30:01.993 [INF] PRNF: PeerNotifier starting
2022-06-04 20:30:01.998 [INF] NTFN: New block epoch subscription
2022-06-04 20:30:02.060 [INF] NTFN: New block epoch subscription
2022-06-04 20:30:02.120 [INF] BRAR: Starting contract observer, watching for breaches.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xb8f0a2]

goroutine 508 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).localLogUpdateToPayDesc(0xc004f158c0, 0xc0047d34a8, 0x1, 0xc54)
        /home/anonymous/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1568 +0x342
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restorePeerLocalUpdates(0xc0062308f0, {0xc006233e78, 0x1, 0x3000000000008}, 0x39)
        /home/anonymous/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2088 +0x132
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc0062308f0, 0xc00062d680, 0xc00062d740, 0xc00062d800, 0x1716b4f8408bdbd7, 0x16274b50abb32ba1, {0x22ace48, 0x0, 0x0}, {0xc006233e78, ...})
        /home/anonymous/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1992 +0x6ab
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc0062308f0, 0x11, 0xc00621ed58)
        /home/anonymous/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1827 +0x527
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel({0x0, 0x0}, 0xc004bc8380, 0x0)
        /home/anonymous/go/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:1345 +0x6c5
github.com/lightningnetwork/lnd/funding.(*Manager).advanceFundingState(0xc004860000, 0xc004bc8380, {0xc2, 0xcd, 0xa4, 0xbc, 0x9b, 0x8, 0x4a, 0xf6, ...}, ...)
        /home/anonymous/go/src/github.com/lightningnetwork/lnd/funding/manager.go:880 +0xdf
created by github.com/lightningnetwork/lnd/funding.(*Manager).start
        /home/anonymous/go/src/github.com/lightningnetwork/lnd/funding/manager.go:679 +0xb6

**lnd aborts**

MY research did not turn up neither a reason nor a solution for the problem. Can you help?

**Comment by rstoffel** [comment]
Tried with version 0.15.0-beta.rc3. 

Same results, same error messages.

**Comment by Crypt-iQ** [comment]
How old is your node? Have you had any power loss / OOMs / other unclean shutdowns?

**Comment by rstoffel** [comment]
- The node war started in October 2021. The oldest channel is 227 days old.
- No powerlosses or unexpected failures of the server.
- No unclean shutdowns I know of.

I don't undertsnad what an OOM is. :-)

A little more detail maybe:

- The node is running on a **proxmox ve** hypervisor.
- HD 1TB
- RAM 32G
- 8 Cores

LND has been running as a service. Looking at the logs lnd stopped without reason. The errormessages are documented above.

As @GordianLN noted above, systemctl restarted the server, lnd repeated the error, which led to the effect @GordianLN mentions.

**Comment by Crypt-iQ** [comment]
An OOM is a process getting killed by the OS for being out-of-memory. If that didn't happen, then the underlying channel logs are somehow not consistent

**Comment by yyforyongyu** [comment]
Trying to dig out what went wrong here, was looking at these lines,

https://github.com/lightningnetwork/lnd/blob/12eddae47a3c5a87d3e1de24f9f62b270713a1f1/channeldb/channel.go#L1617-L1624

Still reading the code, but should the comparison be `>` instead of `>=`?

**Comment by Crypt-iQ** [comment]
iirc, `LocalLogIndex` is last-included-update-index-num + 1. so this logic seems correct

**Comment by Crypt-iQ** [comment]
Do you have logs from when you were on 0.14.3?

**Comment by rstoffel** [comment]
I do not have a clear idea when Ind first went down, because systemctl kept restarting lnd. Lightning watch sent me a down message at 2022-06-03 20:35 UTC. The server runs on Asion time (UTC + 7).

I send you all the logs I have in the logs directory as a zip (debug.zip) file.

[debug.zip](https://github.com/lightningnetwork/lnd/files/8855210/debug.zip)

**Comment by rstoffel** [comment]
Answering your question about channels c2cda4bc9b084af6... or f64a089bbca4cdc2...

To my knowlegde I did not have channels like this..

**Comment by alexbosworth** [comment]
Did you rule out db corruption?

**Comment by alexbosworth** [comment]
To rule out corruption more definitively, could try a compact db with guggero chantools

**Comment by legalizemath** [comment]
same error, same messages

```
2022-10-03 14:55:12.324 [INF] LTND: Version: 0.14.2-beta commit=v0.14.2-beta, build=production, logging=default, debuglevel=info
2022-10-03 14:55:12.324 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2022-10-03 14:55:12.325 [INF] RPCS: RPC server listening on 0.0.0.0:10009
2022-10-03 14:55:12.331 [INF] RPCS: gRPC proxy started at 0.0.0.0:8080
2022-10-03 14:55:12.332 [INF] LTND: Opening the main database, this might take a few minutes...
2022-10-03 14:55:12.334 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
2022-10-03 15:10:48.679 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
2022-10-03 15:10:53.888 [INF] LTND: Creating local graph and channel state DB instances
2022-10-03 15:10:57.304 [INF] CHDB: Checking for schema update: latest_version=24, db_version=24
2022-10-03 15:10:57.304 [INF] LTND: Database(s) now open (time_to_open=15m44.969794129s)!
2022-10-03 15:10:57.308 [INF] LTND: We're not running within systemd
2022-10-03 15:10:57.309 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2022-10-03 15:10:58.692 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
2022-10-03 15:10:58.719 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
2022-10-03 15:11:00.073 [INF] LNWL: Opened wallet
2022-10-03 15:11:00.179 [INF] CHRE: Primary chain is set to: bitcoin
2022-10-03 15:11:00.227 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
2022-10-03 15:11:00.227 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 10.21.21.8:28333
2022-10-03 15:11:00.227 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 10.21.21.8:28332
2022-10-03 15:11:01.151 [INF] LNWL: The wallet has been unlocked without a time limit
2022-10-03 15:11:01.159 [INF] CHRE: LightningWallet opened
2022-10-03 15:11:01.176 [INF] SRVR: Proxying all network traffic via Tor (stream_isolation=false)! NOTE: Ensure the backend node is proxying over Tor as well
2022-10-03 15:11:01.176 [INF] TORC: Starting tor controller
2022-10-03 15:11:01.193 [INF] HSWC: Cleaning circuits from disk for closed channels
2022-10-03 15:11:01.369 [INF] HSWC: Finished cleaning: num_closed_channel=272, num_circuits=0, num_keystone=0
2022-10-03 15:11:01.369 [INF] HSWC: Restoring in-memory circuit state from disk
2022-10-03 15:11:01.476 [INF] HSWC: Payment circuits loaded: num_pending=315, num_open=7
2022-10-03 15:11:01.667 [INF] HSWC: Trimming open circuits for chan_id=725753:3116:2, start_htlc_id=3229
2022-10-03 15:11:01.667 [INF] HSWC: Trimming open circuits for chan_id=742027:415:1, start_htlc_id=2714
// --- repeats similar many times ---
2022-10-03 15:11:01.677 [INF] HSWC: Trimming open circuits for chan_id=701496:1162:0, start_htlc_id=3057
2022-10-03 15:11:01.677 [INF] HSWC: Trimming open circuits for chan_id=699600:2284:1, start_htlc_id=22843
2022-10-03 15:11:02.872 [INF] LNWL: Started rescan from block 00000000000000000008018807e31e5dedf4e9bab35e40f231083ccb9c3bc78b (height 756875) for 2051 addresses
2022-10-03 15:11:03.805 [INF] LNWL: Catching up block hashes to height 756879, this might take a while
2022-10-03 15:11:03.810 [INF] LNWL: Done catching up block hashes
2022-10-03 15:11:03.810 [INF] LNWL: Finished rescan for 2051 addresses (synced to block 00000000000000000005f037881326a85afbb30bd11cdf34c50fddcde7d96e62, height 756879)
2022-10-03 15:11:05.530 [WRN] CRTR: Routing failure for local channel 779751656204664833 occurred
2022-10-03 15:11:05.530 [WRN] CRTR: Routing failure for local channel 779751656204664833 occurred
2022-10-03 15:11:05.530 [WRN] CRTR: Routing failure for local channel 779751656204664833 occurred
2022-10-03 15:11:06.015 [WRN] CRTR: Routing failure for local channel 763717478203523072 occurred
2022-10-03 15:11:06.015 [WRN] CRTR: Routing failure for local channel 763717478203523072 occurred
2022-10-03 15:11:06.130 [INF] LTND: Channel backup proxy channel notifier starting
2022-10-03 15:11:06.130 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=16777215, private=false, min_confs=1, conf_target=3
2022-10-03 15:11:06.134 [INF] LTND: We're not running within systemd
2022-10-03 15:11:06.137 [INF] LTND: Waiting for chain backend to finish sync, start_height=756879
2022-10-03 15:11:06.143 [INF] LTND: Chain backend is fully synced (end_height=756879)!
2022-10-03 15:11:06.143 [WRN] HLCK: check: disk space configured with 0 attempts, skipping it
2022-10-03 15:11:06.143 [WRN] HLCK: check: tls configured with 0 attempts, skipping it
2022-10-03 15:11:06.143 [WRN] HLCK: check: tor connection configured with 0 attempts, skipping it
2022-10-03 15:11:06.151 [INF] PRNF: PeerNotifier starting
2022-10-03 15:11:06.152 [INF] LNWL: Inserting unconfirmed transaction 7ebac4ec1da34855861d37d2d8e2e2af2110bd3430a09bb4d3429f87ee1ce455
2022-10-03 15:11:06.169 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0xc01844e540)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=3 cap=3) {
  (*wire.TxIn)(0xc01845c240)({
   PreviousOutPoint: (wire.OutPoint) fae1ea806ee1ff22fc6db701a50bdac994ab6b92547974899bd3c28b7c3180dc:1,
   SignatureScript: ([]uint8) {
// --- redacted tx info ---
 TxOut: ([]*wire.TxOut) (len=1 cap=1) {
  (*wire.TxOut)(0xc01842e3e0)({
   Value: (int64) 736,
   PkScript: ([]uint8) (len=22 cap=22) {
    00000000  00 14 69 dc 3e e4 46 75  6f ab 24 35 74 e3 f6 c6  |..i.>.Fuo.$5t...|
    00000010  c3 97 1f 84 60 ff                                 |....`.|
   }
  })
 },
 LockTime: (uint32) 756175
})

2022-10-03 15:11:06.169 [INF] NTFN: New block epoch subscription
2022-10-03 15:11:06.233 [INF] NTFN: New block epoch subscription
2022-10-03 15:11:06.287 [INF] BRAR: Starting contract observer, watching for breaches.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x124f142]

goroutine 1580 [running]:
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).localLogUpdateToPayDesc(0xc0129f2ea0, 0xc0131594a8, 0x1, 0x5161)
        github.com/lightningnetwork/lnd/lnwallet/channel.go:1568 +0x342
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restorePeerLocalUpdates(0xc013e72bb0, {0xc013e72c60, 0x7, 0x3000000000008}, 0x39)
        github.com/lightningnetwork/lnd/lnwallet/channel.go:2088 +0x132
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreStateLogs(0xc013e72bb0, 0xc012295b00, 0xc012295bc0, 0xc012295c80, 0x209e467d930f2837, 0x625f85485ee03e67, {0x2d34360, 0x0, 0x0}, {0xc013e72c60, ...})
        github.com/lightningnetwork/lnd/lnwallet/channel.go:1992 +0x6ab
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).restoreCommitState(0xc013e72bb0, 0x11, 0xc01186bd58)
        github.com/lightningnetwork/lnd/lnwallet/channel.go:1827 +0x527
github.com/lightningnetwork/lnd/lnwallet.NewLightningChannel({0x0, 0x0}, 0xc012074700, 0x0)
        github.com/lightningnetwork/lnd/lnwallet/channel.go:1345 +0x6c5
github.com/lightningnetwork/lnd/funding.(*Manager).advanceFundingState(0xc000360700, 0xc012074700, {0xb9, 0xe4, 0xc0, 0x4d, 0x2f, 0x4b, 0xf4, 0x3d, ...}, ...)
        github.com/lightningnetwork/lnd/funding/manager.go:880 +0xdf
created by github.com/lightningnetwork/lnd/funding.(*Manager).start
        github.com/lightningnetwork/lnd/funding/manager.go:679 +0xb6
```

running passively for couple of months without changes, restarting processes every ~72h to recompact

after latest lnd restart / recompact process, which finished, this started happening (29 gb db after recompact)

m2 drive still half empty so plenty of space, memory never ran out with massive pagefile available, no shutdowns, no unexpected closes until this, no config changes done by me for long time

changes I tried that lead to same result:

wtclient.active=0
sync-freelist=0
forcing another recompact

is it safe to update lnd version to latest 0.15.1 to try again? set rejecthtlc=1 in config so no unintended channel updates

**Comment by guggero** [comment]
Looks like this was resolved either with an update of `lnd` or a recovery from backup. Feel free to re-open if still unresolved.
