### ISSUE TITLE
Cannot create channel - panic runtime error

### ISSUE THREAD

**Issue by quantumlicht** [lightningnetwork/lnd#770]
I am currently unable to create channels on the tesnet. Here's the logs. Can you point me in the right direction? I am running `v0.1.4`

```lnd: 2018-02-18 08:13:12.300 [WRN] LTND: open ../lnd.conf: The system cannot find the file specified. 2018-02-18 08:13:12.301 [INF] LTND: Version 0.3.0-alpha 2018-02-18 08:13:12.302 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2018-02-18 08:13:12.307 [INF] LTND: Primary chain is set to: bitcoin 2018-02-18 08:13:12.327 [INF] BTCN: Loaded 1026 addresses from file 'C:\Users\Quantik\AppData\Local\Lnd\data\testnet3\bitcoin\peers.json' 2018-02-18 08:13:12.329 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host 2018-02-18 08:13:12.330 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host
lnd: 2018-02-18 08:13:12.422 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bluematt.me
lnd: 2018-02-18 08:13:12.506 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2018-02-18 08:13:12.507 [INF] BTCN: Syncing to block height 1283459 from peer 165.227.7.29:18333
lnd: 2018-02-18 08:13:13.353 [INF] LNWL: Opened wallet
lnd: 2018-02-18 08:13:12.300 [WRN] LTND: open ../lnd.conf: The system cannot find the file specified. 2018-02-18 08:13:12.301 [INF] LTND: Version 0.3.0-alpha 2018-02-18 08:13:12.302 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2018-02-18 08:13:12.307 [INF] LTND: Primary chain is set to: bitcoin 2018-02-18 08:13:12.327 [INF] BTCN: Loaded 1026 addresses from file 'C:\Users\Quantik\AppData\Local\Lnd\data\testnet3\bitcoin\peers.json' 2018-02-18 08:13:12.329 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host 2018-02-18 08:13:12.330 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host
lnd: 2018-02-18 08:13:12.422 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bluematt.me
lnd: 2018-02-18 08:13:12.506 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2018-02-18 08:13:12.507 [INF] BTCN: Syncing to block height 1283459 from peer 165.227.7.29:18333
lnd: 2018-02-18 08:13:13.353 [INF] LNWL: Opened wallet
lnd: 2018-02-18 08:13:13.552 [INF] CMGR: 25 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de
lnd: 2018-02-18 08:13:14.395 [INF] LNWL: The wallet has been unlocked without a time limit
lnd: 2018-02-18 08:13:14.402 [INF] LTND: LightningWallet opened
```lnd: 2018-02-18 08:13:14.405 [INF] LNWL: Started rescan from block 00000000000004eb62a474fa37fd25454fbdda019ae9fc08626c72d157af5f1d (height 1283459) for 32 addresses
lnd: 2018-02-18 08:13:14.405 [INF] LNWL: Catching up block hashes to height 1283459, this might take a while
lnd: 2018-02-18 08:13:14.406 [INF] LNWL: Done catching up block hashes 2018-02-18 08:13:14.406 [INF] LNWL: Finished rescan for 32 addresses (synced to block 00000000000004eb62a474fa37fd25454fbdda019ae9fc08626c72d157af5f1d, height 1283459)
lnd: 2018-02-18 08:13:14.407 [INF] RPCS: RPC server listening on 127.0.0.1:10009
lnd: 2018-02-18 08:13:14.407 [INF] LTND: Waiting for chain backend to finish sync, start_height=1283459
lnd: 2018-02-18 08:13:14.407 [INF] RPCS: gRPC proxy started at localhost:8080
lnd: 2018-02-18 08:13:14.407 [INF] LTND: Chain backend is fully synced (end_height=1283459)!
lnd: 2018-02-18 08:13:14.407 [INF] HSWC: Starting HTLC Switch
lnd: 2018-02-18 08:13:14.407 [INF] NTFN: New block epoch subscription
lnd: 2018-02-18 08:13:14.408 [INF] BRAR: Watching for the closure of ChannelPoint(3a371c86ccf88edf6c0661214e2c63a1894bb67e625b401f415d636356227a89:0)
lnd: 2018-02-18 08:13:14.408 [INF] DISC: Authenticated Gossiper is starting
lnd: 2018-02-18 08:13:14.408 [INF] NTFN: New confirmations subscription: txid=efd02ba9a8f16d4e8f76b5261f446182b3ff9b2738710130b7664dabc56f8f85, numconfs=1, height_hint=1283459
lnd: 2018-02-18 08:13:14.408 [INF] NTFN: New block epoch subscription
lnd: 2018-02-18 08:13:14.408 [INF] CRTR: FilteredChainView starting
lnd: 2018-02-18 08:13:14.412 [INF] CRTR: Filtering chain using 7555 channels active
lnd: 2018-02-18 08:13:14.414 [INF] CRTR: Prune tip for Channel Graph: height=1280644, hash=000000003246005703f608a38cc5b79c267a5eca995e50900fe3a15db5549016
lnd: 2018-02-18 08:13:14.414 [INF] CRTR: Syncing channel graph from height=1280644 (hash=000000003246005703f608a38cc5b79c267a5eca995e50900fe3a15db5549016) to height=1283459 (hash=00000000000004eb62a474fa37fd25454fbdda019ae9fc08626c72d157af5f1d)
lnd Error: panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x20 pc=0x84d0af] goroutine 1 [running]: github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcutil/gcs.(*Filter).MatchAny(0x0, 0xff8c90d716aea564, 0x515e8a02bb5be8da, 0xc0427fc000, 0x1d83, 0x1d83, 0x0, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcutil/gcs/gcs.go:313 +0x4f github.com/lightningnetwork/lnd/routing/chainview.(*CfFilteredChainView).FilterBlock(0xc04205fc30, 0xc04247c380, 0xc04247c380, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/chainview/neutrino.go:258 +0x638 github.com/lightningnetwork/lnd/routing.(*ChannelRouter).syncGraphWithChain(0xc04226a000, 0xc04267a000, 0x1d83) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:450 +0x6c9 github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start(0xc04226a000, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:324 +0x40e main.(*server).Start(0xc042034300, 0xe9092b, 0x2e) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/server.go:415 +0x124 main.lndMain(0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnd.go:401 +0x1712 main.main() /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnd.go:450 +0x3d``

**Comment by Roasbeef** [comment]
There is no `v0.1.4`. If you were running a very old version of `lnd`, and then updated to master recently. You might run into issue with the `neutrino` backend more as the protocol has changed over time, but is now stable (BIPs assigned).

**Comment by Roasbeef** [comment]
Any update on this?

**Comment by quantumlicht** [comment]
I mistake it for the lightning app repo. Sorry
