### ISSUE TITLE
[bug]: v0.17.1-beta: panic: runtime error: slice bounds out of range [18:0]

### ISSUE THREAD

**Issue by LNBIG-COM** [lightningnetwork/lnd#8184]
### Background

After upgrading from version v0.17.0 to v0.17.1 (from sources), I received an error at the first start and the process crashed with

```
panic: runtime error: slice bounds out of range [18:0]
```

The details are below

### Your environment

* LND v0.17.1-beta
* Ubuntu 20.04
* bitcoind v23.1

### Steps to reproduce

First launch of v0.17.1-beta. Shutting down the v0.17.0 server before the upgrade was successful.

### Actual behaviour

```
023-11-16 15:28:15.022 [INF] NTFN: Cancelling epoch notification, epoch_id=374
2023-11-16 15:28:15.024 [INF] WTCL: (anchor) Queued backup(dbd6b72cbb98d984a490cca8bfb723927b65629e442847a99fb2d94ba907ba7d, 711) successfully for session 029261effb0e6635e2b88f263c1d908947c02d7d1bf206365a33dde82298258a77
2023-11-16 15:28:15.035 [INF] WTCL: (anchor) Queued backup(6bf428f86a7240647d5be0a6f60ed8a327427b7993c0507c2dc3b6d698212643, 67179) successfully for session 029261effb0e6635e2b88f263c1d908947c02d7d1bf206365a33dde82298258a77
2023-11-16 15:28:15.050 [INF] WTCL: (anchor) Queued backup(dbd6b72cbb98d984a490cca8bfb723927b65629e442847a99fb2d94ba907ba7d, 712) successfully for session 029261effb0e6635e2b88f263c1d908947c02d7d1bf206365a33dde82298258a77
2023-11-16 15:28:15.050 [INF] WTCL: not processing task for unregistered channel: 6bf428f86a7240647d5be0a6f60ed8a327427b7993c0507c2dc3b6d698212642
2023-11-16 15:28:15.060 [INF] CHCL: ChannelPoint(de7d36692380594fb65db41a3d505ebdeec75d967436290d17e8263df7f88f4e:0): initiating shutdown
2023-11-16 15:28:15.062 [INF] CHCL: ChannelPoint(de7d36692380594fb65db41a3d505ebdeec75d967436290d17e8263df7f88f4e:0): sending shutdown message
2023-11-16 15:28:15.062 [INF] PEER: Peer(03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d): Sending 2 channel sync messages to peer after loading active channels
2023-11-16 15:28:15.062 [INF] PEER: Peer(03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d): Negotiated chan series queries
2023-11-16 15:28:15.062 [INF] DISC: Creating new GossipSyncer for peer=03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d
2023-11-16 15:28:15.062 [INF] NTFN: New block epoch subscription
panic: runtime error: slice bounds out of range [18:0]

goroutine 43571 [running]:
github.com/lightningnetwork/lnd/brontide.(*Machine).Flush(0xc01eaff400, {0x1a60980, 0xc01566f418})
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/brontide/noise.go:772 +0x1e5
github.com/lightningnetwork/lnd/brontide.(*Conn).Flush(0xc14da7a103b70faf?)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/brontide/conn.go:229 +0x47
github.com/lightningnetwork/lnd/peer.(*Brontide).writeMessage.func1()
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2048 +0x77
github.com/lightningnetwork/lnd/peer.(*Brontide).writeMessage(0xc0208c5c00, {0x1a68d30, 0xc0098e2500})
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2085 +0x131
github.com/lightningnetwork/lnd/peer.(*Brontide).writeHandler(0xc0208c5c00)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2129 +0x35f
created by github.com/lightningnetwork/lnd/peer.(*Brontide).Start
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:645 +0x91f
```

**Comment by Crypt-iQ** [comment]
Seems like this was introduced in https://github.com/lightningnetwork/lnd/pull/8158

**Comment by Crypt-iQ** [comment]
There's no locking in either `WriteMessage` or `Flush` and we call `writeMessage` in a for loop in `Start` after the `writeHandler` is up. I think that a write from the for loop can race with a write from the `writeHandler` (say a gossip query message is being written) and cause `b.nextHeaderSend` to be overwritten while we're using it. I think the solution here would be to put the for loop _before_ the `writeHandler` is initiated.

cc @morehouse @Roasbeef @yyforyongyu

**Comment by morehouse** [comment]
> There's no locking in either `WriteMessage` or `Flush` and we call `writeMessage` in a for loop in `Start` after the `writeHandler` is up. I think that a write from the for loop can race with a write from the `writeHandler` (say a gossip query message is being written) and cause `b.nextHeaderSend` to be overwritten while we're using it. I think the solution here would be to put the for loop _before_ the `writeHandler` goroutine is launched.

Makes sense -- once `writeHandler` starts, it should be the only goroutine that calls `writeMessage`.

**Comment by Crypt-iQ** [comment]
I was able to reproduce the panic (it didn't show up in my prior test runs with #8158 because of how I was testing it) and https://github.com/lightningnetwork/lnd/pull/8186 does fix it

**Comment by LNBIG-COM** [comment]
Other LND server, v0.17.1-beta, not first start (may be 2nd one):

```
2023-11-16 17:51:57.648 [INF] HSWC: Trimming open circuits for chan_id=810333:2677:8, start_htlc_id=1265
2023-11-16 17:51:57.648 [INF] HSWC: Adding live link chan_id=509a31b43d267d98fc9b65e6a04d9be4775682f6f0d6e66ea924d828f2e8f910, short_chan_id=810333:2677:8
2023-11-16 17:51:57.648 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(18f9e8f228d824a96ee6d6f0f6825677e49b4da0e6659bfc987d263db4319a50:8)
2023-11-16 17:51:57.648 [INF] HSWC: ChannelLink(18f9e8f228d824a96ee6d6f0f6825677e49b4da0e6659bfc987d263db4319a50:8): HTLC manager started, bandwidth=87991263384 mSAT
2023-11-16 17:51:57.648 [INF] HSWC: ChannelLink(18f9e8f228d824a96ee6d6f0f6825677e49b4da0e6659bfc987d263db4319a50:8): attempting to re-synchronize
2023-11-16 17:51:57.652 [INF] PEER: Peer(030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f): Loading ChannelPoint(bdfa589a589d6930a693b7f2c6abba631425e8ca0224cc1f54ed5e4dea38979f:1), isPending=false
2023-11-16 17:51:57.653 [INF] HSWC: ChannelLink(bdfa589a589d6930a693b7f2c6abba631425e8ca0224cc1f54ed5e4dea38979f:1): starting
2023-11-16 17:51:57.653 [INF] HSWC: Trimming open circuits for chan_id=701970:2120:1, start_htlc_id=9815
2023-11-16 17:51:57.653 [INF] HSWC: Adding live link chan_id=9f9738ea4d5eed541fcc2402cae8251463baabc6f2b793a630699d589a58fabc, short_chan_id=701970:2120:1
2023-11-16 17:51:57.653 [INF] HSWC: ChannelLink(bdfa589a589d6930a693b7f2c6abba631425e8ca0224cc1f54ed5e4dea38979f:1): HTLC manager started, bandwidth=391933957036 mSAT
2023-11-16 17:51:57.653 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(bdfa589a589d6930a693b7f2c6abba631425e8ca0224cc1f54ed5e4dea38979f:1)
2023-11-16 17:51:57.653 [INF] HSWC: ChannelLink(bdfa589a589d6930a693b7f2c6abba631425e8ca0224cc1f54ed5e4dea38979f:1): attempting to re-synchronize
2023-11-16 17:51:57.659 [INF] PEER: Peer(030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f): Loading ChannelPoint(bc007b26cb747669f5e7bf06ba2da154571619f4a2d7fe33ccc988afd68f55b7:1), isPending=true
2023-11-16 17:51:57.659 [WRN] PEER: Peer(030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f): ChannelPoint(bc007b26cb747669f5e7bf06ba2da154571619f4a2d7fe33ccc988afd68f55b7:1) has status ChanStatusBorked|ChanStatusCommitBroadcasted|ChanStatusLocalCloseInitiator, won't start.
2023-11-16 17:51:57.659 [INF] PEER: Peer(030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f): Sending 1 channel sync messages to peer after loading active channels
2023-11-16 17:51:57.659 [INF] PEER: Peer(030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f): Negotiated chan series queries
2023-11-16 17:51:57.659 [INF] NTFN: New block epoch subscription
2023-11-16 17:51:57.659 [INF] DISC: Creating new GossipSyncer for peer=030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f
panic: runtime error: slice bounds out of range [18:0]

goroutine 47481 [running]:
github.com/lightningnetwork/lnd/brontide.(*Machine).Flush(0xc0321c9000, {0x7f06aae7f240, 0xc000040640})
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/brontide/noise.go:772 +0x1e5
github.com/lightningnetwork/lnd/brontide.(*Conn).Flush(0xc14db00ca753913f?)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/brontide/conn.go:229 +0x47
github.com/lightningnetwork/lnd/peer.(*Brontide).writeMessage.func1()
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2048 +0x77
github.com/lightningnetwork/lnd/peer.(*Brontide).writeMessage(0xc034cf1c00, {0x1a68d30, 0xc02bed9200})
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2085 +0x131
github.com/lightningnetwork/lnd/peer.(*Brontide).writeHandler(0xc034cf1c00)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2129 +0x35f
created by github.com/lightningnetwork/lnd/peer.(*Brontide).Start
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:645 +0x91f
```

**Comment by LNBIG-COM** [comment]
Other crash (3rd):

```
2023-11-16 17:37:18.673 [INF] HSWC: ChannelLink(82ca7017842205e96b4f870dc82daab17072d952309db1ceecae67ea67444407:1): attempting to re-synchronize
2023-11-16 17:37:18.676 [INF] PEER: Peer(03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d): Loading ChannelPoint(de7d36692380594fb65db41a3d505ebdeec75d967436290d17e8263df7f88f4e:0), isPending=false
2023-11-16 17:37:18.676 [WRN] PEER: Peer(03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d): ChannelPoint(de7d36692380594fb65db41a3d505ebdeec75d967436290d17e8263df7f88f4e:0) has status ChanStatusCoopBroadcasted|ChanStatusRemoteCloseInitiator, won't start.
2023-11-16 17:37:18.703 [INF] WTCL: (anchor) SessionQueue(0352239d2dc7e1f98c6f09bdabcbbdbb9d8efc78f491aa2db77c04eeb2728f9ff7) uploaded backup(dccafb1e0a62b000e62041ba0761e65ea361d3ec2454d256ba30c9bdea6236a5, 63745) seqnum=137
2023-11-16 17:37:18.704 [INF] WTCL: (anchor) SessionQueue(03d116f93a8e6d5eb1789a0bc8aca145fd662759256631b05f7992720b50158c2b) uploaded backup(6ef8a00537b026a6dff1c597b57ecb734004e9d907beeaabac8148bc91b9655f, 11887) seqnum=322
2023-11-16 17:37:18.838 [INF] WTCL: (anchor) SessionQueue(039e8470f63c9374dc96cf2b8c444b008639288f55bd6acb89b926749b33ad110d) uploaded backup(6bf428f86a7240647d5be0a6f60ed8a327427b7993c0507c2dc3b6d698212643, 79233) seqnum=648
2023-11-16 17:37:18.839 [INF] WTCL: (anchor) SessionQueue(02261dd4396400d6c40bdc2034b263e2e9b044bb522524d26604d7cd2e6ca038e2) uploaded backup(179e6d5239bd9028093cbf067286b6e45ef6299aca0b05ecaf08700de79b0f1e, 11112) seqnum=875
2023-11-16 17:37:18.839 [INF] WTCL: (anchor) SessionQueue(033107881b0c1cacce6e7edc4a9025cfdac4e616cb1c9eff940a1818d717249369) uploaded backup(77772a0cbdfae39879f4fbd7e7632f9da3d4d344ca1d768c3c2f20415e4ad96d, 41383) seqnum=89
2023-11-16 17:37:18.840 [INF] WTCL: (anchor) SessionQueue(027b32da286e889fa4c52520ff33cd4cd321c3dce8a060850bfb2f1a5efc3835f1) uploaded backup(ee58fc432790cd4809475cea78af5adf7a0364cd37054bb4ffbc90247e0ad786, 19531) seqnum=1009
2023-11-16 17:37:18.841 [INF] WTCL: (anchor) SessionQueue(02ee19d9dea742d6086eba3f5bb2170410c570d3416d6ee9baf664283854a3fc7f) uploaded backup(981578e3d638e29bcb39b44cdfad6762e01949d9d4bcad9ddfe5f8a8da7af3bb, 131060) seqnum=458
2023-11-16 17:37:19.108 [INF] WTCL: (anchor) SessionQueue(024724cef8ef86dcd25ffe3606812edc8416b2dbf6d83f260044694ac15eaa951c) uploaded backup(981578e3d638e29bcb39b44cdfad6762e01949d9d4bcad9ddfe5f8a8da7af3bb, 129986) seqnum=556
2023-11-16 17:37:19.108 [INF] WTCL: (anchor) SessionQueue(03d8fd1bc929e8949c87b4e9af7e063596e460f2ee52e72ce6f772c5512abd281a) uploaded backup(91b57c273b01dcd2fb0713ecbaeefee3e521bb01cad7fae84636d594a4b10bb0, 16069) seqnum=508
2023-11-16 17:37:19.109 [INF] WTCL: (anchor) SessionQueue(029cc5829301490a8bb35b7fc0a0be412c597db9f52511aebe4b150182e9e92969) uploaded backup(981578e3d638e29bcb39b44cdfad6762e01949d9d4bcad9ddfe5f8a8da7af3b5, 7973) seqnum=690
2023-11-16 17:37:19.111 [INF] WTCL: (anchor) SessionQueue(03449fd1eede05648af032ac152ebca1f8a968fa03f782455190898fa84fc7f8aa) uploaded backup(179e6d5239bd9028093cbf067286b6e45ef6299aca0b05ecaf08700de79b0f1e, 12068) seqnum=68
2023-11-16 17:37:19.290 [INF] CHCL: ChannelPoint(de7d36692380594fb65db41a3d505ebdeec75d967436290d17e8263df7f88f4e:0): initiating shutdown
2023-11-16 17:37:19.292 [INF] CHCL: ChannelPoint(de7d36692380594fb65db41a3d505ebdeec75d967436290d17e8263df7f88f4e:0): sending shutdown message
2023-11-16 17:37:19.292 [INF] PEER: Peer(03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d): Sending 2 channel sync messages to peer after loading active channels
2023-11-16 17:37:19.292 [INF] PEER: Peer(03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d): Negotiated chan series queries
2023-11-16 17:37:19.292 [INF] DISC: Creating new GossipSyncer for peer=03b279522ced2ccd9d2c7d1fc500d24f567129fc12b9495a076e30a2e861fffb1d
2023-11-16 17:37:19.292 [INF] NTFN: New block epoch subscription
panic: runtime error: slice bounds out of range [18:0]

goroutine 152163 [running]:
github.com/lightningnetwork/lnd/brontide.(*Machine).Flush(0xc00b884400, {0x1a60980, 0xc01d408670})
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/brontide/noise.go:772 +0x1e5
github.com/lightningnetwork/lnd/brontide.(*Conn).Flush(0xc14daf31116a9e27?)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/brontide/conn.go:229 +0x47
github.com/lightningnetwork/lnd/peer.(*Brontide).writeMessage.func1()
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2048 +0x77
github.com/lightningnetwork/lnd/peer.(*Brontide).writeMessage(0xc012a3a000, {0x1a68d30, 0xc008db8a00})
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2085 +0x131
github.com/lightningnetwork/lnd/peer.(*Brontide).writeHandler(0xc012a3a000)
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:2129 +0x35f
created by github.com/lightningnetwork/lnd/peer.(*Brontide).Start
        /home/bitcoin/go/src/github.com/lightningnetwork/lnd/peer/brontide.go:645 +0x91f
```

**Comment by Crypt-iQ** [comment]
@LNBIG-COM we'll have a fix out shortly, probably in a new 0.17.2 branch. In the meantime, you can either revert back to 0.17.0 or cherry-pick this patch https://github.com/lightningnetwork/lnd/pull/8186/commits/7556402ea44048393bda99d257f60853521e077e on top of 0.17.1

**Comment by LNBIG-COM** [comment]
I think to be need to urgently release an update to version 0.17.1.

The current version is very unstable and crashes not only at startup, but also during operation!

Perhaps this is also due to the fact that I made each node (out of seven) a watchtower, and each server works as a watchtower client with six towers added. Now I see in the logs a large number of messages about placing a channel backup in the queue for any watchtower. If the bug was a long time ago, then perhaps the addition of six towers to each server provoked such a situation.

**Comment by LNBIG-COM** [comment]
> @LNBIG-COM we'll have a fix out shortly, probably in a new 0.17.2 branch. In the meantime, you can either revert back to 0.17.0 or cherry-pick this patch [7556402](https://github.com/lightningnetwork/lnd/commit/7556402ea44048393bda99d257f60853521e077e) on top of 0.17.1

I tried to apply patch to v0.17.1 as cherry-pick but I got conflict:

```
error: could not apply 7556402ea... peer: send reestablish, shutdown messages before starting writeHandler
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
bitcoin@host:~/go/src/github.com/lightningnetwork/lnd$ git status
HEAD detached at 744feb04e
You are currently cherry-picking commit 7556402ea.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   peer/brontide.go

no changes added to commit (use "git add" and/or "git commit -a")
bitcoin@host:~/go/src/github.com/lightningnetwork/lnd$ git diff
diff --cc peer/brontide.go
index 1810f44c2,d7d93f4fa..000000000
--- a/peer/brontide.go
+++ b/peer/brontide.go
@@@ -640,18 -703,9 +640,12 @@@ func (p *Brontide) Start() error 
  
        p.startTime = time.Now()
  
++<<<<<<< HEAD
 +      p.wg.Add(5)
-       go p.queueHandler()
-       go p.writeHandler()
-       go p.readHandler()
-       go p.channelManager()
-       go p.pingHandler()
- 
-       // Signal to any external processes that the peer is now active.
-       close(p.activeSignal)
- 
-       // Now that the peer has started up, we send any channel sync messages
-       // that must be resent for borked channels.
++=======
+       // Before launching the writeHandler goroutine, we send any channel
+       // sync messages that must be resent for borked channels. We do this to
+       // avoid data races with WriteMessage & Flush calls.
        if len(msgs) > 0 {
                p.log.Infof("Sending %d channel sync messages to peer after "+
                        "loading active channels", len(msgs))
@@@ -667,6 -720,20 +660,22 @@@
                }
        }
  
+       err = p.pingManager.Start()
+       if err != nil {
+               return fmt.Errorf("could not start ping manager %w", err)
+       }
+ 
+       p.wg.Add(4)
++>>>>>>> 7556402ea... peer: send reestablish, shutdown messages before starting writeHandler
+       go p.queueHandler()
+       go p.writeHandler()
 -      go p.channelManager()
+       go p.readHandler()
++      go p.channelManager()
++      go p.pingHandler()
+ 
+       // Signal to any external processes that the peer is now active.
+       close(p.activeSignal)
+ 
        // Node announcements don't propagate very well throughout the network
        // as there isn't a way to efficiently query for them through their
        // timestamp, mostly affecting nodes that were offline during the time
```

**Comment by Crypt-iQ** [comment]
My bad, abort your current cherry-pick and try this one: https://github.com/Crypt-iQ/lnd/commit/d597dcccc4169e63563313ae0ab135b9d9697e9a

**Comment by LNBIG-COM** [comment]
> My bad, abort your current cherry-pick and try this one: [Crypt-iQ@d597dcc](https://github.com/Crypt-iQ/lnd/commit/d597dcccc4169e63563313ae0ab135b9d9697e9a)

I decided to revert the v0.17.0 version already...
