### ISSUE TITLE
[bug]: Golangs grpc-streamer might not recycle bad connections causing a deadlock when runnning lnd with an active HTLC Interceptor

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#8318]
### Background

A noderunner was suffering from random situations where a lot of HTLCs (>200) would pile up on this side not getting resolved occasionally. After analysing his goroutine dump during this situation I was able to locate the reason why the HTLCs where not getting resolved. It seems like the GRPC stream connection does not realize that its broken or whatsoever, but this leads to a situation where everything dependant on the HTLCInterceptor piles up and prevents any further operations on incoming htlcs.

The HTLCInterceptor server seems to not be able to Send the msg to the client and hangs for 60 minutes:

```
goroutine 7699590 [select, 60 minutes]: 1 times: [[7699590]
google.golang.org/grpc/internal/transport.(*writeQuota).get(...)
        google.golang.org/grpc@v1.56.3/internal/transport/flowcontrol.go:59
google.golang.org/grpc/internal/transport.(*http2Server).Write(0xc1fd748340, 0xc1fc9f0120, {0xc030cd9b30, 0x5, 0x5}, {0xc03f29c600, 0x5ab, 0x5ab}, 0x0?)
        google.golang.org/grpc@v1.56.3/internal/transport/http2_server.go:1114 +0x205
google.golang.org/grpc.(*serverStream).SendMsg(0xc001bb05a0, {0x1d68fe0?, 0xc02b880320})
        google.golang.org/grpc@v1.56.3/stream.go:1651 +0x2a8
github.com/grpc-ecosystem/go-grpc-prometheus.(*monitoredServerStream).SendMsg(0xc1fc9cded8, {0x1d68fe0?, 0xc02b880320?})
        github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:156 +0x2d
github.com/lightningnetwork/lnd/lnrpc/routerrpc.(*routerHtlcInterceptorServer).Send(0x1d7dc60?, 0x1e64a42?)
        github.com/lightningnetwork/lnd/lnrpc/routerrpc/router_grpc.pb.go:918 +0x28
github.com/lightningnetwork/lnd/lnrpc/routerrpc.(*forwardInterceptor).onIntercept(_, {{{0xc5bfa, 0x5c9, 0x0}, 0x38ee6}, {0xc3da6, 0x1fe, 0x0}, {0x20, 0x4d, ...}, ...})
        github.com/lightningnetwork/lnd/lnrpc/routerrpc/forward_interceptor.go:96 +0x262
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).sendForward(0xc000796e80, {0x21f6418?, 0xc0202f96c0?})
        github.com/lightningnetwork/lnd/htlcswitch/interceptable_switch.go:325 +0x91
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).forward(0xc000796e80, {0x21f6418, 0xc0202f96c0}, 0x0)
        github.com/lightningnetwork/lnd/htlcswitch/interceptable_switch.go:551 +0x2a5
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).interceptForward(0xc000796e80, 0xc03e0a56b0, 0xf0?)
        github.com/lightningnetwork/lnd/htlcswitch/interceptable_switch.go:495 +0x13f
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).run(0xc000796e80)
        github.com/lightningnetwork/lnd/htlcswitch/interceptable_switch.go:258 +0x4a6
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).Start.func1()
        github.com/lightningnetwork/lnd/htlcswitch/interceptable_switch.go:214 +0x53
created by github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).Start in goroutine 1
        github.com/lightningnetwork/lnd/htlcswitch/interceptable_switch.go:211 +0xa6
```

This causes us to never serve new incoming htlc requests because we hang here:

https://github.com/lightningnetwork/lnd/blob/master/htlcswitch/interceptable_switch.go#L258

And now a lot of HTLC are piling up see:

```
goroutine 96395093 [select, 29 minutes]: 235 times: [[96395093, 89860664, 72396356, 109878069, 112119008, 98465203, 129926369, 90125866, 135943496, 112326953, 71286471, 92190357, 80853607, 104860664, 63093377, 92125420, 159342471, 86334639, 142736732, 159342474, 78135802, 139816111, 105556963, 86874339, 133980226, 109768029, 89955860, 63116118, 139013045, 123477618, 116916025, 121278838, 159342473, 116196449, 74463575, 92068939, 78222799, 67445637, 139016734, 137312308, 159342478, 114118493, 124351881, 141747906, 108602579, 84159266, 75706105, 63111674, 138925001, 138615185, 89705126, 107474503, 89718542, 67287394, 78281413, 89699934, 153454842, 72823481, 152237782, 116702141, 109201305, 87991295, 135433635, 101867165, 95392426, 112119001, 122851617, 114657444, 72662932, 149661153, 80107001, 72458723, 153971732, 78074060, 140079964, 63078584, 160817368, 135930801, 105556965, 107478710, 105556966, 149661132, 148672102, 139018443, 159342476, 107110107, 72756536, 153511128, 84726296, 63076547, 89624366, 150963572, 159342480, 157162676, 155500808, 69535034, 155500807, 123016604, 135647801, 67448668, 79008065, 102057726, 96978902, 67479775, 67439078, 99564584, 107572237, 137305656, 156396516, 84874775, 140103273, 159342475, 76522228, 125634428, 141861356, 63076784, 72438240, 121771656, 135537941, 77540065, 150551680, 72548186, 153646938, 63259009, 146483731, 72513997, 95338047, 96050582, 105556960, 87019084, 66838764, 93191461, 105395417, 78287937, 84310560, 149661131, 145914451, 159342468, 67489391, 140254273, 67507872, 95898121, 130295476, 156615131, 112201833, 93256561, 122596849, 89687738, 63082329, 121578176, 91237428, 145687440, 67439299, 78071065, 141314336, 83817171, 81856555, 110186962, 121433206, 63100123, 123509518, 78140789, 158872615, 84241461, 100809022, 63094104, 67745412, 149661134, 120557395, 155717771, 113394852, 86988087, 105556959, 78526693, 105556964, 157861431, 84218177, 84387935, 159342472, 114457284, 84282345, 141345454, 95101945, 144627584, 70532394, 134265142, 105556958, 150401661, 67396818, 141505114, 105556962, 91909846, 69494551, 68110906, 63074209, 81060197, 95500338, 72982887, 109083924, 78266309, 159342479, 140748259, 122057782, 72377210, 115591458, 116876612, 105556961, 121284984, 130455922, 160659171, 146202393, 110261154, 156615130, 143525790, 150040188, 159342470, 140906147, 134481463, 138483681, 156374862, 152020028, 159342477, 149661136, 156615132, 149661133, 128971605, 133918125, 129357420, 152706358, 139092569, 140069267, 128059413, 159342469, 134905913, 149661135]
github.com/lightningnetwork/lnd/htlcswitch.(*InterceptableSwitch).ForwardPackets(0xc000796e80, 0xc01268f500, 0x0, {0xc016904aa8, 0x1, 0x1})
        github.com/lightningnetwork/lnd/htlcswitch/interceptable_switch.go:423 +0x11e
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).forwardBatch(0xc009a54580, 0x80?, {0xc120c1ee00, 0x1, 0x0?})
        github.com/lightningnetwork/lnd/htlcswitch/link.go:3371 +0x175
created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).processRemoteSettleFails in goroutine 36532189
        github.com/lightningnetwork/lnd/htlcswitch/link.go:2916 +0x576
```

As a consequence blocking a lot of payments because all the above htlcs are mostly payments not forwards:

```
goroutine 91899632 [select, 33 minutes]: 372 times: [[91899632, 83393321, 106513618, 80785413, 67322884, 78172046, 116630862, 74825325, 134859481, 120917735, 71911871, 63044487, 99283338, 123378202, 62918079, 107319162, 89692589, 103452984, 77311686, 62996791, 67387427, 80032552, 90706301, 161019306, 83103934, 139617841, 33949737, 33952549, 83712273, 71953509, 137255713, 121917186, 152119657, 77692839, 62630941, 63070658, 145306100, 33947509, 77815423, 71819695, 33946445, 71958838, 83480528, 62640540, 101526552, 77348977, 33951843, 69200607, 33945958, 63065477, 67183109, 67324535, 33946590, 121192957, 33951491, 33951848, 33951199, 158662033, 67283530, 33951148, 78378709, 77214393, 95802838, 160040109, 72224650, 74064925, 83969297, 108855986, 67268314, 62879729, 79985402, 141117326, 150917232, 124092574, 87957233, 105333099, 111847269, 33945926, 63055261, 77586441, 72033424, 84146687, 92068865, 86276195, 115485594, 33952334, 159683908, 33947122, 135820315, 138355732, 122033457, 86793167, 33951823, 110139639, 89912923, 33950927, 33945080, 33948144, 153438844, 120443186, 77312191, 89789452, 140855507, 106943841, 33950198, 67391250, 139813333, 77300075, 89630913, 161210487, 123352875, 119984368, 95242270, 109887742, 72354263, 33945702, 62770917, 33947164, 62767244, 33947914, 143343645, 114561308, 160204821, 67175383, 33949749, 33946218, 33948042, 83857765, 73911454, 84226392, 33951348, 152609258, 159819246, 89674860, 95335282, 94955082, 84755097, 33948002, 33946884, 101795132, 120867447, 33951585, 33947591, 33944975, 155460906, 77909184, 33947597, 81798182, 33946250, 92129368, 69443591, 67215080, 33946593, 149541138, 33946028, 33946456, 62822833, 33948288, 133564738, 139010756, 33949040, 115467341, 33948667, 67303177, 127829849, 33952356, 138439838, 135569073, 160088185, 63055564, 33948933, 63007502, 33947066, 33946055, 33945094, 89654055, 33949800, 92971540, 33944991, 125433787, 33951319, 33947967, 122649315, 62825645, 62693690, 62850237, 33944969, 33950552, 33950621, 62821186, 33946158, 33948902, 33946703, 33947709, 33951040, 108453450, 33950118, 72035606, 33950745, 33949170, 139000296, 33946620, 33947279, 109227068, 139017334, 67427151, 89607870, 148286626, 141094720, 89104640, 129368881, 33947468, 33947039, 33951474, 33950683, 33946887, 33952250, 69491955, 121666863, 33950063, 33944985, 33945962, 62809411, 67333991, 72168071, 33950489, 77800463, 33947823, 135441421, 33950375, 33952032, 33948185, 33951838, 71935431, 33946728, 156262331, 135839469, 33949363, 66284350, 33949730, 161122897, 72143587, 33947204, 33951238, 74080641, 114264193, 33946828, 116864310, 33946507, 144395730, 77933929, 33949836, 58570332, 33946150, 33949825, 33948588, 33947677, 160338845, 100628571, 61507557, 33949670, 33945399, 33945754, 33952536, 79565616, 85596543, 134644157, 72108574, 33949620, 113184226, 91896419, 33946854, 33949230, 160900461, 63001753, 133680773, 67125532, 70816311, 33949931, 33950954, 62851956, 84606024, 67406260, 67401340, 33951982, 33910848, 137244597, 62993682, 33945786, 107456827, 153383816, 33952340, 80890388, 145000716, 108063971, 33950270, 67290704, 112170625, 33944955, 93217966, 97293690, 33948182, 141717916, 81865624, 94789017, 116413240, 87916151, 89521443, 95139187, 72259417, 67220477, 96362195, 70498917, 72060802, 78032269, 62950648, 149950405, 71958179, 71958468, 138837560, 156931091, 152631320, 92240967, 77809647, 76150065, 87040556, 72244080, 122921009, 127923402, 67219337, 63031761, 129693285, 86933645, 63068859, 160435297, 95957245, 63011659, 75676064, 139088565, 62994663, 77251790, 67243024, 153549916, 146276641, 150426760, 67210560, 86208820, 63041290, 157340282, 159980140, 109672630, 151752884, 140057203, 141659419, 159708722, 140618952, 160587657, 160605762, 130395091, 140231293, 139685646, 160126800, 142643473, 141171830, 145919574, 152903996, 134400979, 128794428, 133944538, 160251251, 159791823, 160926349]
github.com/lightningnetwork/lnd/htlcswitch.(*Switch).GetAttemptResult.func1()
        github.com/lightningnetwork/lnd/htlcswitch/switch.go:482 +0x107
created by github.com/lightningnetwork/lnd/htlcswitch.(*Switch).GetAttemptResult in goroutine 91899567
        github.com/lightningnetwork/lnd/htlcswitch/switch.go:478 +0x1be
```

I am currently not sure why the connection is not recycled but will ask with the golang-rpc devs. Raising this issue here nonetheless as a reference if other people experience the same.

### Your environment

* version of `lnd`: 0.17.3
* which operating system (`uname -a` on *Nix):SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
* version of `btcd`, `bitcoind`, or other backend: bitcoind 0.25
* any other relevant environment details

GoDumpFile: 
[deadlock_gprc_stream.txt](https://github.com/lightningnetwork/lnd/files/13787727/deadlock_gprc_stream.txt)

Thanks for the data @KnockOnWoodNode

**Comment by ziggie1984** [comment]
opened a question on the grpc lib side as well: https://github.com/grpc/grpc-go/issues/6895

**Comment by KnockOnWoodNode** [comment]
To complete the scenario, I was running circuitbreaker, and I still am. Cannot pinpoint the version but I didn't update it since I first cloned it on the node, which was around march maybe? I just fetched the latest content of its repo and restarted the service,

**Comment by SunnySarahNode** [comment]
I'll add a few small details:

1) Stopping or restarting the interceptor (Circuitbreaker) corrects this situation and HTLCs immediately begin to be processed as usual.

2) The problem does not depend on the load level and occurs even in very lightly loaded nodes.

**Comment by KnockOnWoodNode** [comment]
I can confirm, restarting CB just solved the issue for me.

**Comment by Roasbeef** [comment]
I wonder if we need to set some config value here ourselves for read/write timeout for a stream?
