### ISSUE TITLE
[bug]: Potential Deadlock when Receiving `ReplyChannelRange` msg

### ISSUE THREAD

**Issue by ziggie1984** [lightningnetwork/lnd#8398]
Since LND 0.18 we use the `QueryChannelRange` to get the latest update of the network. But there is potential deadlock which manifests itself when receiving the reply:

In [FilterKnownChanIDs](https://github.com/lightningnetwork/lnd/blob/master/channeldb/graph.go#L2089) we aquire the channel.db mutex:

https://github.com/lightningnetwork/lnd/blob/ba4021cad98887b2a63be6b61bf0ad46b07c221a/channeldb/graph.go#L2094-L2101

However this function also later want to aquire the mutex lock of `ChannelGraph cacheMu`:

https://github.com/lightningnetwork/lnd/blob/ba4021cad98887b2a63be6b61bf0ad46b07c221a/channeldb/graph.go#L2145-L2148

https://github.com/lightningnetwork/lnd/blob/ba4021cad98887b2a63be6b61bf0ad46b07c221a/channeldb/graph.go#L3621-L3625

This causes the deadlock.

An example goroutine dump which shows this can be found here:

[deadlock_7_dedup.txt](https://github.com/lightningnetwork/lnd/files/13979374/deadlock_7_dedup.txt)

**Comment by ziggie1984** [comment]
Infos from the dump:

This holds the db lock and wants to access the `ChannelGraph` mutex

```
goroutine 9894412 [sync.Mutex.Lock, 20 minutes]: 1 times: [[9894412]
sync.runtime_SemacquireMutex(0xc1617a3d55e61707?, 0xb4?, 0x2c72e00?)
        runtime/sema.go:77 +0x28
sync.(*Mutex).lockSlow(0x4000633510)
        sync/mutex.go:171 +0x174
sync.(*Mutex).Lock(...)
        sync/mutex.go:90
sync.(*RWMutex).Lock(0x4000633510)
        sync/rwmutex.go:147 +0x70
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).markEdgeLive(0x4000633500, {0x1cbe6c8, 0x40123fff80}, 0xc38890008a60000)
        github.com/lightningnetwork/lnd/channeldb/graph.go:3622 +0x4c
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).FilterKnownChanIDs.func1({0x1cbe6c8, 0x40123fff80})
        github.com/lightningnetwork/lnd/channeldb/graph.go:2146 +0x25c
github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0x4001b71ba8?, 0x4014af6040, 0x40?)
        github.com/btcsuite/btcwallet/walletdb@v1.4.0/bdb/db.go:429 +0x98
github.com/lightningnetwork/lnd/kvdb.Update(...)
        github.com/lightningnetwork/lnd/kvdb@v1.4.4/interface.go:16
github.com/lightningnetwork/lnd/channeldb.(*ChannelGraph).FilterKnownChanIDs(0x4000633500, {0x401ba20000, 0xe56f, 0x10500}, 0x400881e350)
        github.com/lightningnetwork/lnd/channeldb/graph.go:2094 +0x12c
github.com/lightningnetwork/lnd/discovery.(*ChanSeries).FilterKnownChanIDs(0x0?, {0x6f, 0xe2, 0x8c, 0xa, 0xb6, 0xf1, 0xb3, 0x72, 0xc1, ...}, ...)
        github.com/lightningnetwork/lnd/discovery/chan_series.go:207 +0x24
github.com/lightningnetwork/lnd/discovery.(*GossipSyncer).processChanRangeReply(0x4002fa7860, 0x400c98aa80)
        github.com/lightningnetwork/lnd/discovery/syncer.go:902 +0x724
github.com/lightningnetwork/lnd/discovery.(*GossipSyncer).channelGraphSyncer(0x4002fa7860)
        github.com/lightningnetwork/lnd/discovery/syncer.go:542 +0x7f4
created by github.com/lightningnetwork/lnd/discovery.(*GossipSyncer).Start.func1 in goroutine 4377
        github.com/lightningnetwork/lnd/discovery/syncer.go:462 +0x100
```

Tho this holds the `ChannelGraph ` mutex and wants to aquire the db lock:

```
goroutine 21519683 [sync.Mutex.Lock, 20 minutes]: 9 times: [[21519683, 21520084, 21519896, 21519750, 21519526, 21524214, 21520134, 21524209, 21519348]                                     sync.runtime_SemacquireMutex(0x4003f424e8?, 0x54?, 0x1bf08eb000?)
        runtime/sema.go:77 +0x28
sync.(*Mutex).lockSlow(0x400097e1b8)
        sync/mutex.go:171 +0x174
sync.(*Mutex).Lock(...)
        sync/mutex.go:90
go.etcd.io/bbolt.(*DB).beginRWTx(0x400097e000)
        go.etcd.io/bbolt@v1.3.7/db.go:755 +0x98
go.etcd.io/bbolt.(*DB).Begin(0x4003f425d8?, 0x48?)
        go.etcd.io/bbolt@v1.3.7/db.go:697 +0x20
github.com/btcsuite/btcwallet/walletdb/bdb.(*db).beginTx(0x10?, 0xa0?)
        github.com/btcsuite/btcwallet/walletdb@v1.4.0/bdb/db.go:323 +0x1c
github.com/btcsuite/btcwallet/walletdb/bdb.(*db).BeginReadWriteTx(...)
        github.com/btcsuite/btcwallet/walletdb@v1.4.0/bdb/db.go:335
github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0x14c9e40?, 0x400f045c68, 0x1ca3d10?)
        github.com/btcsuite/btcwallet/walletdb@v1.4.0/bdb/db.go:417 +0x48
github.com/lightningnetwork/lnd/kvdb.Update(...)
        github.com/lightningnetwork/lnd/kvdb@v1.4.4/interface.go:16
github.com/lightningnetwork/lnd/batch.(*batch).run(0x400748e500)
        github.com/lightningnetwork/lnd/batch/batch.go:54 +0x194                                                                                                                           sync.(*Once).doSlow(0x0?, 0x81924?)
        sync/once.go:74 +0x100
sync.(*Once).Do(...)
        sync/once.go:65
github.com/lightningnetwork/lnd/batch.(*batch).trigger(...)
        github.com/lightningnetwork/lnd/batch/batch.go:32
created by time.goFunc
        time/sleep.go:176 +0x38
```
