### ISSUE TITLE
[bug]: lnd crashes with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by greenart7c3** [lightningnetwork/lnd#9399]
### Background

lnd crashes with panic: runtime error: invalid memory address or nil pointer dereference

### Your environment

lnd 0.18.4-beta
Ubuntu
bitcoind

### Steps to reproduce

Don't know how to reproduce this but its happening a lot today. The service starts and after a while a get this error

```

Dec 31 18:44:24 greenart7c3-desktop lnd[820440]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x497698]
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]: goroutine 30519 [running]:
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]: sync.(*RWMutex).Lock(0xc000273180?)
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]:         sync/rwmutex.go:146 +0x18
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]: github.com/lightningnetwork/lnd/lnwallet/chainfee.(*filterManager).updateMedian(0xc0041e6f00, {0xc00237b500, 0x8, 0x8})
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]:         github.com/lightningnetwork/lnd/lnwallet/chainfee/filtermanager.go:208 +0x5f
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]: github.com/lightningnetwork/lnd/lnwallet/chainfee.(*filterManager).fetchPeerFilters(0xc0041e6f00)
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]:         github.com/lightningnetwork/lnd/lnwallet/chainfee/filtermanager.go:87 +0xc5
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]: created by github.com/lightningnetwork/lnd/lnwallet/chainfee.(*filterManager).Start in goroutine 1
Dec 31 18:44:24 greenart7c3-desktop lnd[820440]:         github.com/lightningnetwork/lnd/lnwallet/chainfee/filtermanager.go:60 +0x65

```

**Comment by JhovanEscobidal** [comment]
…

**Comment by Crypt-iQ** [comment]
@greenart7c3 what Go version are you using?

**Comment by greenart7c3** [comment]
go version go1.23.1 linux/amd64

**Comment by Crypt-iQ** [comment]
@greenart7c3 did you compile `lnd` yourself or did you use some sort of installer? I ask because the crashing line number in `sync.rwmutex.go` seems a little off if the go version used was `go1.23.1` but I could be missing something.

**Comment by Crypt-iQ** [comment]
I looked it up and the compiled version uses `go1.22.6` and it looks like the mutex is `nil` for some reason

**Comment by ellemouton** [comment]
@Crypt-iQ  - is it not that the actual `filterManager` is nil? I dont think the mutex can be nil (it is not a pointer)

**Comment by ziggie1984** [comment]
@greenart7c3 is your LND permanently in restart mode, because of this error, or does it only happen occasionally ? Would you be able to run a customized LND version with more DEBUG logs to trace down your problem ?

**Comment by ziggie1984** [comment]
Ok I think the problem is here:

User runs the binary compiled with GOLANG 1.22.6 but uses it in the runtime of GOLANG 1.23, where the sync package completely changed. That's why there are all this effects. Basically you cannot run the precompiled binary which a newer golang version.

**Comment by ziggie1984** [comment]
Closing this solutions you have:

- Compiling golang from source, which then uses your local golang 1.23

- running it docker with the golang version 1.22.6

- downgrading your golang of your current system to 1.22.6 if you still want to use the compiled version.

**Comment by ziggie1984** [comment]
waiting for your confirmation before closing.

**Comment by ziggie1984** [comment]
which bitcoind version are you running ?

**Comment by ziggie1984** [comment]
do you still have the logs available ?

**Comment by greenart7c3** [comment]
I don't have the logs anymore
Bitcoind version is 28

**Comment by lord-cow** [comment]
I'm getting possibly the same issue. Just upgraded bitcoind and lnd to:

bitcoin-28.0
0.18.99-beta

FreeBSD 13.4
go121-1.21.13

All built from source.

After starting lnd:

2025-01-12 00:43:26.852 [INF] CHDB: Applying migration #32
2025-01-12 00:43:26.852 [INF] CHDB: Migrating Mission Control store to use a more minimal encoding for routes
2025-01-12 00:43:26.877 [INF] LTND: Shutdown complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2c91140]

goroutine 1 [running]:
github.com/lightningnetwork/lnd/channeldb/migration/lnwire21.EncodeFailureMessage({0xb9aac0, 0x9350c1680}, {0x0, 0x0}, 0x0)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration/lnwire21/onion_error.go:1354 +0x40
github.com/lightningnetwork/lnd/channeldb/migration32.encodeFailureMessage({0xb9aac0, 0x9350c1650}, {0x4b3600?, 0x9350c15b0}, 0x9350c15c0?)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/mission_control_store.go:327 +0x76
github.com/lightningnetwork/lnd/channeldb/migration32.(*failureMessage).Record.func1()
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/mission_control_store.go:312 +0x55
github.com/lightningnetwork/lnd/tlv.(*Record).Size(...)
        /home/lightning/go/pkg/mod/github.com/lightningnetwork/lnd/tlv@v1.3.0/record.go:86
github.com/lightningnetwork/lnd/tlv.(*Stream).Encode(0x9356ea2a0, {0xb9aac0, 0x9350c15c0})
        /home/lightning/go/pkg/mod/github.com/lightningnetwork/lnd/tlv@v1.3.0/stream.go:98 +0xc9
github.com/lightningnetwork/lnd/channeldb/migration/lnwire21.EncodeRecordsTo({0xb9aac0?, 0x9350c15c0?}, {0x9356ec070?, 0x874498008?, 0x2?})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration/lnwire21/custom_records.go:224 +0x156
github.com/lightningnetwork/lnd/channeldb/migration32.encodePaymentFailureInfo({0xb9aac0, 0x9350c15c0}, {0x3feec0?, 0x9350c1598?}, 0x9350c1560?)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/mission_control_store.go:266 +0xa9
github.com/lightningnetwork/lnd/channeldb/migration32.(*paymentFailureInfo).Record.func1()
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/mission_control_store.go:251 +0x55
github.com/lightningnetwork/lnd/tlv.(*Record).Size(...)
        /home/lightning/go/pkg/mod/github.com/lightningnetwork/lnd/tlv@v1.3.0/record.go:86
github.com/lightningnetwork/lnd/tlv.(*Stream).Encode(0x9356ea280, {0xb9aac0, 0x9350c1560})
        /home/lightning/go/pkg/mod/github.com/lightningnetwork/lnd/tlv@v1.3.0/stream.go:98 +0xc9
github.com/lightningnetwork/lnd/channeldb/migration/lnwire21.EncodeRecordsTo({0xb9aac0?, 0x9350c1560?}, {0x9353c2ac0?, 0x3fee00?, 0x1?})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration/lnwire21/custom_records.go:224 +0x156
github.com/lightningnetwork/lnd/channeldb/migration32.encodePaymentFailure({0xb9aac0, 0x9350c1560}, {0x3fee60?, 0x9353c22c8?}, 0x9350c0db0?)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/mission_control_store.go:203 +0x19b
github.com/lightningnetwork/lnd/channeldb/migration32.(*paymentFailure).Record.func1()
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/mission_control_store.go:182 +0x55
github.com/lightningnetwork/lnd/tlv.(*Record).Size(...)
        /home/lightning/go/pkg/mod/github.com/lightningnetwork/lnd/tlv@v1.3.0/record.go:86
github.com/lightningnetwork/lnd/tlv.(*Stream).Encode(0x9356ea0a0, {0xb9aac0, 0x9350c0db0})
        /home/lightning/go/pkg/mod/github.com/lightningnetwork/lnd/tlv@v1.3.0/stream.go:98 +0xc9
github.com/lightningnetwork/lnd/channeldb/migration/lnwire21.EncodeRecordsTo({0xb9aac0?, 0x9350c0db0?}, {0x93561bce0?, 0x0?, 0x4?})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration/lnwire21/custom_records.go:224 +0x156
github.com/lightningnetwork/lnd/channeldb/migration32.serializeNewResult(0x93561bc00)
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/mission_control_store.go:734 +0x287
github.com/lightningnetwork/lnd/channeldb/migration32.MigrateMCRouteSerialisation.func1({0x89e793060, 0x31, 0x31}, {0x89e793091?, 0x18?, 0x8281785b8?})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/migration.go:39 +0x65
go.etcd.io/bbolt.(*Bucket).ForEach(0x874052d78?, 0x93409e078)
        /home/lightning/go/pkg/mod/go.etcd.io/bbolt@v1.3.11/bucket.go:397 +0x90
github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).ForEach(0x874052dc8?, 0x3689540?)
        /home/lightning/go/pkg/mod/github.com/btcsuite/btcwallet/walletdb@v1.4.4/bdb/db.go:190 +0x17
github.com/lightningnetwork/lnd/channeldb/migration32.MigrateMCRouteSerialisation({0xbc3160, 0x874210248})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/migration32/migration.go:27 +0xc6
github.com/lightningnetwork/lnd/channeldb.(*DB).syncVersions.func1({0xbc3160, 0x874210248})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/db.go:1520 +0x139
github.com/btcsuite/btcwallet/walletdb/bdb.(*db).Update(0x8747a0488, 0x93584e000, 0x874052f18?)
        /home/lightning/go/pkg/mod/github.com/btcsuite/btcwallet/walletdb@v1.4.4/bdb/db.go:429 +0x9f
github.com/lightningnetwork/lnd/kvdb.Update(...)
        /home/lightning/go/pkg/mod/github.com/lightningnetwork/lnd/kvdb@v1.4.12/interface.go:16
github.com/lightningnetwork/lnd/channeldb.(*DB).syncVersions(0x934b400c0, {0x365f820, 0x21, 0x87455c000?})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/db.go:1511 +0x53b
github.com/lightningnetwork/lnd/channeldb.CreateWithBackend({0xbc0310, 0x8747a0488}, {0x874053348, 0x5, 0x3bec80?})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/channeldb/db.go:412 +0x239
github.com/lightningnetwork/lnd.(*DefaultDatabaseBuilder).BuildDatabase(0x874224000, {0xbb5318, 0x8743380f0})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/config_builder.go:1061 +0xa6f
github.com/lightningnetwork/lnd.Main(0x8742c6008, {{0x0?, 0x874053ee8?, 0x1e9a010?}}, 0x8743f8000, {0x8740ac2a0, 0x8740b0360, 0x8740b03c0, 0x8740b0420, {0x0}})
        /home/lightning/go/src/github.com/lightningnetwork/lnd/lnd.go:471 +0x1c6a
main.main()
        /home/lightning/go/src/github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x205

**Comment by saubyk** [comment]
Closing this issue as it is still missing reproduction
