### ISSUE TITLE
Invoice creation lnd crash with huge expiry

### ISSUE THREAD

**Issue by juscamarena** [lightningnetwork/lnd#972]
### Background

Describe your issue here.

### Your environment

* version of `lnd` 87d77a1b87595945c640e2d21f2baaa559f5f752
* which operating system (`uname -a` on *Nix) x86_64 GNU/Linux Ubuntu
* version of `btcd`, `bitcoind`, or other backend btcd
* any other relevant environment details
None of the above is really relevant other than commit hash

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.
create an invoice with --expiry 99999999999999999

lncli addinvoice --amt 1337000 --expiry 99999999999999999
[lncli] rpc error: code = Unavailable desc = transport is closing

boom lnd crashes

### Expected behaviour
Not crashing crashing or error out invoice creation instead of lnd.

Can see this only really being a problem if expiry is exposed and set externally without limits.

Tell us what should happen
### Actual behaviour

Tell us what happens instead

**Comment by Roasbeef** [comment]
Panic trace:
```
goroutine 8708 [running]:
github.com/lightningnetwork/lnd/zpay32.uint64ToBase32(0xffffffff68bcca3d, 0xc43085cb18, 0xc43085cb2a, 0x2)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/zpay32/invoice.go:1085 +0x110
github.com/lightningnetwork/lnd/zpay32.writeTaggedFields(0xc430cfcd20, 0xc430a88500, 0x7, 0x7)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/zpay32/invoice.go:945 +0x881
github.com/lightningnetwork/lnd/zpay32.(*Invoice).Encode(0xc430a88500, 0xc43071d8d8, 0xbdcd9b9ce8ba05cc, 0x5e45b8cce1a3b454, 0xbe38cd5a7e52048c, 0xbea77125cec85e46)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/zpay32/invoice.go:408 +0x427
main.(*rpcServer).AddInvoice(0xc430b531d0, 0x1c9b120, 0xc420304a80, 0xc42025e240, 0xc430b531d0, 0xc430c8c1c0, 0xc4202583f0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/rpcserver.go:2171 +0x407
github.com/lightningnetwork/lnd/lnrpc._Lightning_AddInvoice_Handler.func1(0x1c9b120, 0xc420304a80, 0x1a56e20, 0xc42025e240, 0x1, 0x1, 0x0, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:5642 +0x86
github.com/lightningnetwork/lnd/macaroons.(*Service).UnaryServerInterceptor.func1(0x1c9b120, 0xc420304a80, 0x1a56e20, 0xc42025e240, 0xc430c8c1a0, 0xc430c8c1c0, 0xc430ac4ab0, 0x1012e48, 0x50, 0x1a2ef80)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/macaroons/service.go:115 +0x156
github.com/lightningnetwork/lnd/lnrpc._Lightning_AddInvoice_Handler(0x1a87440, 0xc430b531d0, 0x1c9b120, 0xc420304a80, 0xc430a92500, 0xc430a728e0, 0x0, 0x0, 0xc420046f88, 0xc420046f00)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/lnrpc/rpc.pb.go:5644 +0x167
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420344000, 0x1ca0360, 0xc430d9cd80, 0xc420306100, 0xc430b53320, 0x215f878, 0xc430cfe120, 0x0, 0x0)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:781 +0x9c8
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420344000, 0x1ca0360, 0xc430d9cd80, 0xc420306100, 0xc430cfe120)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1318
github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc430bc48c0, 0xc420344000, 0x1ca0360, 0xc430d9cd80, 0xc420306100)
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:551 +0x9f
created by github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/google.golang.org/grpc/server.go:549 +0xa1
```
